objects/Account.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <description>The key in a key/value relationship of a list-of-values (LOV) lookup table.  The Code should be unique within a record type.</description>
        <label>Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EPA_Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used in FTTA Application</description>
        <label>Record Id</label>
        <referenceTo>EPA_Agreement__c</referenceTo>
        <relationshipLabel>Collaborator/Partner</relationshipLabel>
        <relationshipName>Partner</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Foreign_Domestic__c</fullName>
        <description>FTTA License. Created to capture the Foreign/Domestic input from user.</description>
        <label>Foreign/Domestic</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Domestic</fullName>
                </value>
                <value>
                    <fullName>International</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>Used in FTTA Application</description>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>OA</fullName>
                </value>
                <value>
                    <fullName>OAR</fullName>
                </value>
                <value>
                    <fullName>OARM</fullName>
                </value>
                <value>
                    <fullName>OCFO</fullName>
                </value>
                <value>
                    <fullName>OECA</fullName>
                </value>
                <value>
                    <fullName>OEI</fullName>
                </value>
                <value>
                    <fullName>OGC</fullName>
                </value>
                <value>
                    <fullName>OIA</fullName>
                </value>
                <value>
                    <fullName>OIG</fullName>
                </value>
                <value>
                    <fullName>OPPTS</fullName>
                </value>
                <value>
                    <fullName>ORD</fullName>
                </value>
                <value>
                    <fullName>OSWER</fullName>
                </value>
                <value>
                    <fullName>OW</fullName>
                </value>
                <value>
                    <fullName>REG 1</fullName>
                </value>
                <value>
                    <fullName>REG 2</fullName>
                </value>
                <value>
                    <fullName>REG 3</fullName>
                </value>
                <value>
                    <fullName>REG 4</fullName>
                </value>
                <value>
                    <fullName>REG 5</fullName>
                </value>
                <value>
                    <fullName>REG 6</fullName>
                </value>
                <value>
                    <fullName>REG 7</fullName>
                </value>
                <value>
                    <fullName>REG 8</fullName>
                </value>
                <value>
                    <fullName>REG 9</fullName>
                </value>
                <value>
                    <fullName>REG 10</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Short_Description__c</fullName>
        <description>Short description.  As a text field instead of text area, it can be viewed in a list.  The standard Description field cannot display in table format.</description>
        <label>Short Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Size_of_Business__c</fullName>
        <description>Used in FTTA Application</description>
        <label>Size of Business</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Small Business (less than 500)</fullName>
                </value>
                <value>
                    <fullName>Medium Business (500 - 999)</fullName>
                </value>
                <value>
                    <fullName>Large Business (greater than 1,000)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Startup_5_yrs__c</fullName>
        <description>Used in FTTA Application</description>
        <label>Startup (&lt; 5 yrs)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No (over 5 years)</fullName>
                </value>
                <value>
                    <fullName>Yes (less than 5 years)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Submitted_by__c</fullName>
        <description>Used in FTTA Application</description>
        <label>Submitted by</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Center</fullName>
                </value>
                <value>
                    <fullName>EPA</fullName>
                </value>
                <value>
                    <fullName>EPA/Partner</fullName>
                </value>
                <value>
                    <fullName>Partner</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>FTTA_Partner_POC</fullName>
        <active>true</active>
        <description>FTTA Partner POC</description>
        <label>FTTA Partner POC</label>
    </recordTypes>
</CustomObject>

objects/EPA_Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used in FTTA Application</description>
        <inlineHelpText>Related Amendments</inlineHelpText>
        <label>Parent Record</label>
        <referenceTo>EPA_Agreement__c</referenceTo>
        <relationshipLabel>Amendment/s</relationshipLabel>
        <relationshipName>EPA_Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>FTTA Application</description>
        <label>Region</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>EPA Agreements (Region)</relationshipLabel>
        <relationshipName>EPA_Agreements1</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>Information on an EPA Agreement, initially used for FTTA, but also available for other uses.  (Note that the similarly named Agreement object has a Master-Detail relationship with Project, which limits the breadth of its potential use, whereas this object has no such Master-Detail relationship, so it can be used in more situations.)</description>
    <label>EPA Agreement</label>
    <nameField>
        <displayFormat>EPA-{0000000}</displayFormat>
        <label>Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EPA Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EPAFileNumberCS__c.object
<CustomObject>
    <fields>
        <fullName>SequenceNumber__c</fullName>
        <description>FTTA Application. It holds the MIn,Max and current sequence for agreements, licenses and patents.</description>
        <label>SequenceNumber</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>FTTA Application. This custom setting is used for ftta agreements, licenses and patents to auto generate Epa file number sequence.</description>
    <label>EPAFileNumberCS</label>
</CustomObject>

classes/FTTA_OnStatusUpdatehelper.cls
/**********************************************************************
Name: FTTA_OnStatusUpdatehelper()
======================================================
======================================================
Purpose: FTTA Applictaion. Created for the auto generation of the amendment Id and adding the parent Partners and POCs for the amendments.
-------
======================================================
======================================================
History
-------
VERSION AUTHOR        DATE      DETAIL               FEATURES/CSR/TTP
1.0 -   Mounika Suram 9/27/2018 Initial Development  FTTA 
1.0     Mounika Suram 10/1/2018 Upadted              FTTA 
1.0     Mounika Suram 10/24/2018 Added generation for the fiscal year FTTA License
***********************************************************************/
public class FTTA_OnStatusUpdatehelper {
    private static final Integer LICENCE_MIN = Integer.valueOf(EPAFileNumberCS__c.getInstance('LicenseMin').SequenceNumber__c);
    private static final Integer LICENCE_MAX = Integer.valueOf(EPAFileNumberCS__c.getInstance('LicenseMax').SequenceNumber__c);
    private static final Integer AGREEMENT_MIN = Integer.valueOf(EPAFileNumberCS__c.getInstance('AgreementMin').SequenceNumber__c);
    private static final Integer AGREEMENT_MAX = Integer.valueOf(EPAFileNumberCS__c.getInstance('AgreementMax').SequenceNumber__c);
    private static EPAFileNumberCS__c agreementCurrent = EPAFileNumberCS__c.getInstance('AgreementCurrent');
    private static EPAFileNumberCS__c licenseCurrent = EPAFileNumberCS__c.getInstance('LicenseCurrent');
    
    public static String generateEPAFileNumber(Boolean lOra){
        string epaFileNumber;
        String code;
        integer year = (Date.Today()).Month() > 9 ? Date.Today().Year() + 1:Date.Today().Year();
        if(lOra){
            licenseCurrent.SequenceNumber__c
                =(licenseCurrent.SequenceNumber__c == 0)?LICENCE_MIN:licenseCurrent.SequenceNumber__c+1;
            update licenseCurrent;
            code = String.valueOf(Integer.valueOf(licenseCurrent.SequenceNumber__c));
        }
        else{
            agreementCurrent.SequenceNumber__c
                =(agreementCurrent.SequenceNumber__c == 0)?AGREEMENT_MIN:agreementCurrent.SequenceNumber__c+1;
            update agreementCurrent;
            code = String.valueOf(Integer.valueOf(agreementCurrent.SequenceNumber__c));
        }
        epaFileNumber = code +' - '+string.valueof(year).right(2);
        return epaFileNumber;
    }
  
    public static string getParentFileNumber(String lastFileNumber, String name,Integer index){
        System.debug('Is FTTA_OnStatusUpdatehelper : getParentFileNumber');
        List<String> letteringSystem = new List<String>{'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z'};
        String lastLetter; 
        String agreementNumber;
        String parentFileNumber;
        String agreementFileNumber;
        if(lastFileNumber != null){
            System.debug('lastFileNumber'+lastFileNumber);
            String ladtLetter1 = lastFileNumber.substringBeforeLast('-');
            lastLetter = ladtLetter1.substringAfterLast('-').trim(); 
            index = letteringSystem.indexOf(lastLetter);
            System.debug('Current Index'+index);
            index ++;
            System.debug('Next Index'+index);
        }  
        String letter = letteringSystem.get(index);
        integer year = (Date.Today()).Month() > 9 ? Date.Today().Year() + 1:Date.Today().Year();
        agreementNumber = letter + ' - ' + string.valueof(year).right(2);
        parentFileNumber = name.substringBefore('-');
        agreementFileNumber = parentFileNumber +' - '+ agreementNumber;
        System.debug('agreementFileNumber'+agreementFileNumber);
        return agreementFileNumber;
    }
    
    public static void createPartnerforAmendment(EPA_Agreement__C agreement, List<Account> partners){
        try{
            System.debug('Is FTTA_OnStatusUpdatehelper : createPartneforAmendment');
            List<Account> amendmentPartners = new List<Account>();
            for(Account partner : partners){
                Account amendmentPartner =  new Account();
                amendmentPartner.name = (partner.Name <> null)? partner.Name : null;
                amendmentPartner.Short_Description__c = (partner.Short_Description__c <> null)? partner.Short_Description__c : null;
                amendmentPartner.Type = (partner.Type <> null)? partner.Type : null;
                amendmentPartner.Size_of_Business__c = (partner.Size_of_Business__c <> null)? partner.Size_of_Business__c : null;
                amendmentPartner.Description = (partner.Description <> null)? partner.Description : null;
                amendmentPartner.Submitted_by__c = (partner.Submitted_by__c <> null)? partner.Submitted_by__c : null;
                amendmentPartner.Code__c = (partner.Code__c <> null)? partner.Code__c : null;
                amendmentPartner.Phone = (partner.Phone <> null)? partner.Phone : null;
                amendmentPartner.Fax = (partner.Fax <> null)? partner.Fax : null;
                amendmentPartner.Region__c = (partner.Region__c <> null)? partner.Region__c : null;
                amendmentPartner.Foreign_Domestic__c = (partner.Foreign_Domestic__c <> null)? partner.Foreign_Domestic__c : null;
                amendmentPartner.NumberOfEmployees = (partner.NumberOfEmployees <> null)? partner.NumberOfEmployees : null;
                amendmentPartner.Startup_5_yrs__c = (partner.Startup_5_yrs__c <> null)? partner.Startup_5_yrs__c : null;
                amendmentPartner.RecordTypeId = (partner.RecordTypeId <> null)? partner.RecordTypeId : null;
                amendmentPartner.EPA_Agreement__c = agreement.id;
                amendmentPartners.add(amendmentPartner);            
             }
            insert amendmentPartners;
            System.debug('amendmentPartners'+amendmentPartners);
            
       }
       catch(exception ex){
        system.debug('Exception occured in the FTTA_OnStatusUpdatehelper' + ex.getMessage() + ex.getLineNumber());
       }
       
    }
    
    public static void createPartnePocsforAmendment(EPA_Agreement__C agreement){
        try{
            System.debug('Is FTTA_OnStatusUpdatehelper : createPartneforAmendment');
            List<Account> amendmentPartners = [select id, Name,Short_Description__c,Type,Size_of_Business__c,Region__c,Foreign_Domestic__c,NumberOfEmployees,Startup_5_yrs__c,
                               RecordTypeId, BillingCity,BillingCountry,BillingGeocodeAccuracy,
                               BillingLatitude,BillingLongitude,BillingPostalCode,BillingState, BillingStreet 
                               from Account where EPA_Agreement__c =:agreement.Agreement__c];
            System.debug('amendmentPartners'+amendmentPartners);
            List<Contact> amendmentPOCs = new List<Contact>();
            Id fttaPartnerPOCRTId = [select id from RecordType where developerName= 'FTTA_Partner_POC'].Id;
            for(Account partner : amendmentPartners){
                 for(Contact poc : [select Id,Salutation,FirstName,MiddleName,Suffix,LastName,Email,Phone,MobilePhone,Fax,AccountId,RecordTypeId from contact where AccountId = :partner.Id]){
                        Contact amendmentPoc = new Contact();
                        amendmentPoc.Salutation = (poc.Salutation <> null)? poc.Salutation : null;
                        amendmentPoc.FirstName = (poc.FirstName <> null)? poc.FirstName : null;
                        amendmentPoc.MiddleName = (poc.MiddleName <> null)? poc.MiddleName : null;
                        amendmentPoc.LastName = (poc.LastName <> null)? poc.LastName : null;
                        amendmentPoc.Suffix = (poc.Suffix <> null)? poc.Suffix : null;
                        amendmentPoc.Email = (poc.Email <> null)? poc.Email : null;
                        amendmentPoc.Phone = (poc.Phone <> null)? poc.Phone : null;
                        amendmentPoc.MobilePhone = (poc.MobilePhone <> null)? poc.MobilePhone : null;
                        amendmentPoc.Fax = (poc.Fax <> null)? poc.Fax : null;
                        amendmentPoc.AccountId=[select id from Account where name=:partner.Name and EPA_Agreement__c=:agreement.id ].id;
                        amendmentPoc.RecordTypeId =fttaPartnerPOCRTId;
                        amendmentPOCs.add(amendmentPoc);
                     
                  }
            }  
            insert amendmentPOCs;
            System.debug('amendmentPOCs'+amendmentPOCs);
        }
        catch(exception ex){
         system.debug('Exception occured in the createPartneforAmendment' + ex.getMessage() + ex.getLineNumber());
        }
       
    }
    
    public static void createProductsForAmendment(EPA_Agreement__C agreement){
        System.debug('Is FTTA_OnStatusUpdatehelper : createProductsForAmendment');
        List<Line_Item__C> products= [Select id,Item_Name__c,Product_Type__c,URL__C,
                                      Software_Developed__c, recordTypeId from Line_item__C where EPA_Agreement__c = :agreement.Agreement__c];
        List<Line_Item__c> productsForAmendment = new List<Line_Item__c>();
        if(!products.isEmpty()){
            for(Line_Item__C product: products){
                Line_Item__C productForAmendment = new Line_Item__C();
                productForAmendment.Item_Name__c = (product.Item_Name__c <> null)?product.Item_Name__c: null;
                productForAmendment.recordTypeId= (product.RecordTypeId <> null)?product.RecordTypeId: null;
                productForAmendment.Product_Type__c= (product.Product_Type__c <> null)?product.Product_Type__c: null;
                productForAmendment.URL__c= (product.URL__c <> null)?product.URL__c: null;
                productForAmendment.Software_Developed__c= (product.Software_Developed__c <> null)?product.Software_Developed__c: null;
                productForAmendment.EPA_Agreement__c= agreement.Id;
                productsForAmendment.add(productForAmendment);
            }
            insert productsForAmendment;
            System.debug('productsForAmendment'+productsForAmendment);
        }
        
    }
    
}