objects/Account.object
<CustomObject>
    <fields>
        <fullName>EPA_Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used in FTTA Application</description>
        <label>Record Id</label>
        <referenceTo>EPA_Agreement__c</referenceTo>
        <relationshipLabel>Collaborator/Partner</relationshipLabel>
        <relationshipName>Partner</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/EPA_Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Agreement_Type__c</fullName>
        <description>Used in FTTA Application.</description>
        <label>Agreement Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Amendment</fullName>
                </value>
                <value>
                    <fullName>CRADA</fullName>
                </value>
                <value>
                    <fullName>Funded MTA</fullName>
                </value>
                <value>
                    <fullName>Materials CRADA</fullName>
                </value>
                <value>
                    <fullName>MTA</fullName>
                </value>
                <value>
                    <fullName>NDA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used in FTTA Application</description>
        <inlineHelpText>Related Amendments</inlineHelpText>
        <label>Parent Record</label>
        <referenceTo>EPA_Agreement__c</referenceTo>
        <relationshipLabel>Amendment/s</relationshipLabel>
        <relationshipName>EPA_Agreements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Generic Description Field</description>
        <inlineHelpText>Generic Description Field</inlineHelpText>
        <label>Description</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>EPA_File_2__c</fullName>
        <description>FTTA Application.</description>
        <externalId>true</externalId>
        <label>EPA File #</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>License_Type__c</fullName>
        <description>FTTA License. Created to capture the license type.</description>
        <inlineHelpText>Please select the license type.</inlineHelpText>
        <label>License Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Co-exclusive</fullName>
                    <default>true</default>
                    <label>Co-exclusive</label>
                </value>
                <value>
                    <fullName>Exclusive</fullName>
                </value>
                <value>
                    <fullName>Non-exclusive</fullName>
                </value>
                <value>
                    <fullName>Research</fullName>
                </value>
                <value>
                    <fullName>Government</fullName>
                </value>
                <value>
                    <fullName>Amendment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OGC_Review_Needed__c</fullName>
        <description>FTTA. Created to capture user input if OGC review is needed</description>
        <inlineHelpText>Please Select if OGC Review is needed</inlineHelpText>
        <label>OGC Review Needed</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Used in FTTA Application</description>
        <inlineHelpText>Agreement Status</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                    <color>#E27001</color>
                    <default>true</default>
                    <label>Created</label>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                    <color>#78C953</color>
                    <label>Assigned</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Review in process</fullName>
                </value>
                <value>
                    <fullName>OGC review</fullName>
                    <color>#66E9BD</color>
                    <label>OGC review</label>
                </value>
                <value>
                    <fullName>OGC Concurrence</fullName>
                    <color>#A53711</color>
                    <label>OGC Concurrence</label>
                </value>
                <value>
                    <fullName>Signature Prep</fullName>
                </value>
                <value>
                    <fullName>At Signature</fullName>
                    <color>#0B24BE</color>
                    <label>At Signature</label>
                </value>
                <value>
                    <fullName>Out for Sign</fullName>
                </value>
                <value>
                    <fullName>Signed</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <color>#0B6FCE</color>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Not Pursued</fullName>
                    <color>#F3D904</color>
                    <label>Not Pursued</label>
                </value>
                <value>
                    <fullName>Expired</fullName>
                    <color>#A845DC</color>
                    <label>Expired</label>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                    <color>#641CCF</color>
                    <label>Terminated</label>
                </value>
                <value>
                    <fullName>Active-Amending</fullName>
                    <isActive>false</isActive>
                    <label>Active-Amending</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Termination_Date__c</fullName>
        <description>FTTA. Created to capture the termination date if the termination date when the agreement is terminated.</description>
        <inlineHelpText>Termination date of the EPA Agreement.</inlineHelpText>
        <label>Termination Date</label>
        <type>Date</type>
    </fields>
    <description>Information on an EPA Agreement, initially used for FTTA, but also available for other uses.  (Note that the similarly named Agreement object has a Master-Detail relationship with Project, which limits the breadth of its potential use, whereas this object has no such Master-Detail relationship, so it can be used in more situations.)</description>
    <label>EPA Agreement</label>
    <nameField>
        <displayFormat>EPA-{0000000}</displayFormat>
        <label>Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EPA Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>FTTA_EPA_Agreement</fullName>
        <active>true</active>
        <label>FTTA Agreement/Amendment</label>
    </recordTypes>
    <recordTypes>
        <fullName>FTTA_License</fullName>
        <active>true</active>
        <description>FTTA License</description>
        <label>FTTA License</label>
    </recordTypes>
</CustomObject>

classes/FTTA_OnStatusUpdateTest.cls
/**********************************************************************
Name: FTTA_OnStatusUpdateTest()
======================================================
======================================================
Purpose: Created to test the class FTTA_RecordLockOnStatusTerminated
-------
======================================================
======================================================
History
-------
VERSION AUTHOR        DATE      DETAIL              FEATURES/CSR/TTP
1.0 -   Mounika Suram 8/15/2018 Initial Development FTTA
***********************************************************************/
@isTest(SeeAllData=true)
public class FTTA_OnStatusUpdateTest {
    
private static id agreementRecordTypeId = [select id from RecordType where sobjectType='EPA_Agreement__C' and developerName='FTTA_EPA_Agreement'].id;
private static id licenseRecordTypeId = [select id from RecordType where sobjectType='EPA_Agreement__C' and developerName='FTTA_License'].id;
    @isTest
    private static void WhenAmendment(){
        system.debug('In FTTA_OnStatusUpdateTest:InsertAgreement');
        EPA_Agreement__C agreement = new EPA_Agreement__C();
        agreement.RecordTypeId=agreementRecordTypeId;
        agreement.Status__c='Created';
        agreement.Termination_Date__c=null;
        insert agreement;
        
        Account partner = new Account();
        partner.name ='Test Account';
        partner.EPA_Agreement__c = agreement.id;
        insert partner;
        
        Contact poc = new Contact();
        poc.LastName='test';
        poc.AccountId=partner.id;
        insert poc;
        
        Line_Item__C product = new Line_Item__C();
        product.Software_Developed__c=true;
        product.EPA_Agreement__c= agreement.id;
        insert product;
        
        EPA_Agreement__C amendment = new EPA_Agreement__C();
        amendment.RecordTypeId=agreementRecordTypeId;
        amendment.Status__c='Created';
        amendment.Agreement_Type__c='Amendment';
        amendment.Agreement__c = agreement.id;
        insert amendment;
        EPA_Agreement__C amendment2 = new EPA_Agreement__C();
        amendment2.RecordTypeId=agreementRecordTypeId;
        amendment2.Status__c='Created';
        amendment2.Agreement_Type__c='Amendment';
        amendment2.Agreement__c = agreement.id;
        insert amendment2;
        system.assert([select id,EPA_File_2__c from EPA_Agreement__C where id=:amendment.Id].EPA_File_2__c <> null);
    }
    @isTest
    private static void WhenStatusTerminated(){
        system.debug('In FTTA_OnStatusUpdateTest:InsertAgreement');
        
        EPA_Agreement__C agreement = new EPA_Agreement__C();
        agreement.RecordTypeId=agreementRecordTypeId;
        agreement.Status__c='Created';
        agreement.Termination_Date__c=null;
        insert agreement;
        system.debug('Status'+agreement.Status__c);
        agreement.Status__c='Terminated';
        agreement.Description__c='test';
        update agreement;
        system.debug(' Updated Status'+agreement.Status__c);
        system.debug(' Updated agreement'+agreement);
    }
    // Mounika 2/15/2019 Temporarily commented for the ftta workflow.
    //@isTest
    //private static void WhenStatusAtSignature(){
    //     try{
    //        system.debug('In FTTA_RecordLockOnStatusTerminatedTest:WhenStatusAtSignature');
    //        EPA_Agreement__C agreement = new EPA_Agreement__C();
    //        agreement.RecordTypeId=agreementRecordTypeId;
    //        agreement.Status__c='Created';
    //        agreement.OGC_Review_Needed__c='Yes';
    //        insert agreement;
   //         system.debug('Status'+agreement.Status__c);
    //        agreement.Status__c='At Signature';
   //         agreement.Description__c='test';
    //        update agreement;             
  //          system.debug(' Updated Status'+agreement.Status__c);
  //          system.debug(' Updated agreement'+agreement);  
  //      }
   //     catch(Exception e){
       
  //          Boolean expectedExceptionThrown = (e.getMessage().contains('Status not saved. Please complete OGC Review and Concurrence'))? true : false;
            
  //         System.AssertEquals(expectedExceptionThrown, true);
        
  //      } 
  //  }
    @isTest
    private static void WhenStatusPending(){
         try{
            system.debug('In FTTA_RecordLockOnStatusTerminatedTest:WhenStatusPending');
            EPA_Agreement__C agreement = new EPA_Agreement__C();
            agreement.RecordTypeId=agreementRecordTypeId;
            agreement.Status__c='Created';
            agreement.OGC_Review_Needed__c='Yes';
            insert agreement;
            system.debug('Status'+agreement.Status__c);
            agreement.Status__c='Pending';
            agreement.Description__c='test';
            update agreement;             
            system.debug('Updated Status'+agreement.Status__c);
            system.debug('Updated agreement'+agreement);  
        }
        catch(Exception e){
        
            Boolean expectedExceptionThrown = (e.getMessage().contains('Status not saved. Please add Partner/Collaborator'))? true : false;
            
            System.AssertEquals(expectedExceptionThrown, true);
        
        } 
    }
    @isTest
    private static void WhenStatusIsNull(){
         try{
            system.debug('In FTTA_RecordLockOnStatusTerminatedTest:WhenStatusIsNull');
            EPA_Agreement__C agreement = new EPA_Agreement__C();
            agreement.RecordTypeId=agreementRecordTypeId;
            agreement.Status__c='Created';
            agreement.OGC_Review_Needed__c='Yes';
            insert agreement;
            system.debug('Status'+agreement.Status__c);
            agreement.Status__c='fake';
            agreement.Description__c=null;
            update agreement;             
            system.debug(' Updated Status'+agreement.Status__c);
            system.debug(' Updated agreement'+agreement);  
        }
        catch(Exception ex){
        
            System.debug('Error occured while handling WhenStatusIsNull'+
                           ex.getMessage() + ex.getLineNumber()+ ex.getCause()); 
        
        } 
    }
    @isTest
    private static void WhenLicense(){
            EPA_Agreement__C license = new EPA_Agreement__C();
            license.RecordTypeId=licenseRecordTypeId;
            license.License_Type__c='exclusive';
            license.OGC_Review_Needed__c='Yes';
            insert license;
    }
}