objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>GAS Vendor Data</description>
        <inlineHelpText>Active Vendors are CHECKED by default.</inlineHelpText>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>Vendor</fullName>
        <active>true</active>
        <description>Outside organizations that do business with the EPA.</description>
        <label>Vendor</label>
    </recordTypes>
</CustomObject>

objects/eOrder_Item__c.object
<CustomObject>
    <fields>
        <fullName>Order_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Request</label>
        <referenceTo>Order_Request__c</referenceTo>
        <relationshipLabel>Order Request Items</relationshipLabel>
        <relationshipName>eOrder_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Code__c</fullName>
        <formula>Product__r.Product_Code__c</formula>
        <label>Product Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Choose a Product by searching for Product details</description>
        <inlineHelpText>Choose a Product by searching for Product details</inlineHelpText>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>EPA_Product__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>EPA_Product__c.Vendor__r.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>EPA_Product__c</referenceTo>
        <relationshipLabel>eOrder Items</relationshipLabel>
        <relationshipName>eOrder_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <description>Number of cylinders requested</description>
        <inlineHelpText>Number of cylinders requested</inlineHelpText>
        <label>Quantity</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The current state of this item</description>
        <inlineHelpText>The current state of this item</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New Order</fullName>
                    <default>true</default>
                    <label>New Order</label>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Request Approved</fullName>
                </value>
                <value>
                    <fullName>Added to Order</fullName>
                </value>
                <value>
                    <fullName>Order Placed</fullName>
                </value>
                <value>
                    <fullName>Order Received</fullName>
                </value>
                <value>
                    <fullName>Order Delivered</fullName>
                </value>
                <value>
                    <fullName>Added to 1900-63</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vendor_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Vendor Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>eOrder Items</relationshipLabel>
        <relationshipName>eOrder_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>eOrder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>eOrder</label>
        <referenceTo>eOrders__c</referenceTo>
        <relationshipLabel>eOrder Items</relationshipLabel>
        <relationshipName>eOrder_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>Specific or detailed items within an order tracked in the eOrders document, initially for the GAS application.  (Similar to Line Items, into which this item might be merged someday.)</description>
    <label>eOrder Item</label>
    <nameField>
        <displayFormat>EPA-EOI-{000000000}</displayFormat>
        <label>eOrder Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>eOrder Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/eOrders__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <description>Comments to help describe the needs, uses, and etc. of the eOrder</description>
        <inlineHelpText>Comments to help describe the needs, uses, and etc. of the eOrder</inlineHelpText>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Order_Amount__c</fullName>
        <description>Total Cost of the sum of associated eOrder Items</description>
        <inlineHelpText>Total Cost of the sum of associated eOrder Items</inlineHelpText>
        <label>Order Amount</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Order_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Request</label>
        <referenceTo>Order_Request__c</referenceTo>
        <relationshipLabel>eOrders</relationshipLabel>
        <relationshipName>eOrders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Organization_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>GAS application.</description>
        <inlineHelpText>Choose the Organization for which you want to create an eOrder.</inlineHelpText>
        <label>Organization Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>eOrders (Organization Name)</relationshipLabel>
        <relationshipName>eOrders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The current state of the eOrder</description>
        <inlineHelpText>The current state of the eOrder</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <color>#0B6FCE</color>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Activated</fullName>
                    <color>#78C953</color>
                    <label>Activated</label>
                </value>
                <value>
                    <fullName>Return Order Placed</fullName>
                    <color>#CC33CC</color>
                    <label>Return Order Placed</label>
                </value>
                <value>
                    <fullName>Order Placed</fullName>
                    <color>#E27001</color>
                    <label>Order Placed</label>
                </value>
                <value>
                    <fullName>Partial Order Received</fullName>
                    <color>#F3D904</color>
                    <label>Partial Order Received</label>
                </value>
                <value>
                    <fullName>Full Order Received</fullName>
                    <color>#A845DC</color>
                    <label>Full Order Received</label>
                </value>
                <value>
                    <fullName>Order Closed</fullName>
                    <color>#A53711</color>
                    <label>Order Closed</label>
                </value>
                <value>
                    <fullName>Return Order Closed</fullName>
                    <color>#333333</color>
                    <label>Return Order Closed</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vendor_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Choose the Vendor for which you want to create an eOrder</description>
        <inlineHelpText>Choose the Vendor for which you want to create an eOrder</inlineHelpText>
        <label>Vendor Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>GAS Vendors</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>eOrders</relationshipLabel>
        <relationshipName>eOrders</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>Custom Object to Capture Orders placed for GAS Order Management Application.</description>
    <label>eOrder</label>
    <nameField>
        <displayFormat>EPA-EO-{000000000}</displayFormat>
        <label>eOrder ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>eOrders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/EPA_Product__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>List_Price__c</fullName>
        <label>Unit Price</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_Code__c</fullName>
        <description>Product Code</description>
        <inlineHelpText>Product Code</inlineHelpText>
        <label>Product Code</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <label>Product Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Vendors MUST be Active and Valid Account Record Type.</errorMessage>
            <filterItems>
                <field>Account.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>GAS Vendors</value>
            </filterItems>
            <infoMessage>Vendors MUST be Active.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>Products being acquired, products being generated by a process or system, or other kinds of objects being tracked, managed, reported on, etc.  Used initially for gas cylinder products being procured in the GAS application.</description>
    <label>Product</label>
    <nameField>
        <displayFormat>EPA-P-{0000000000}</displayFormat>
        <label>Product ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Order_Request__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <description>Comments to help describe the needs, uses, and etc. of the Order Request</description>
        <inlineHelpText>Comments to help describe the needs, uses, and etc. of the Order Request</inlineHelpText>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Requester_Org__c</fullName>
        <description>GAS Order Management</description>
        <formula>Owner:User.Department</formula>
        <inlineHelpText>Requester Name typically the user who logged in and placing an order</inlineHelpText>
        <label>Requester Org</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <description>Current state of the Order Request</description>
        <inlineHelpText>Current state of the Order Request</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New Order</fullName>
                    <default>true</default>
                    <label>New Order</label>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Request Approved</fullName>
                </value>
                <value>
                    <fullName>Order Placed</fullName>
                </value>
                <value>
                    <fullName>Partial Order Received</fullName>
                </value>
                <value>
                    <fullName>Full Order Received</fullName>
                </value>
                <value>
                    <fullName>Order Fulfilled</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vendor_Name__c</fullName>
        <description>PCOR Application.Created to capture the name of the vendor.</description>
        <label>Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <description>Requests for orders to be placed.  Initially used in the GAS application, then in PCORS, and available for other uses.  Used not only in native licensed access ("Type 3 interface" in BAP parlance) but also in "Type 1" interface (unlicensed guest access).</description>
    <label>Order Request</label>
    <nameField>
        <displayFormat>EPA-OR-{000000000}</displayFormat>
        <label>Order Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ORDGAS_eOrderClassTest.cls
/*
*    Author : mondal.javed@epa.gov
*    CreatedDate : 1-May-2018
*    Class Name : ORDGAS_eOrderClassTest
*    Test Class for ORDGAS_eOrderClassTest
**/

@isTest
Public Class ORDGAS_eOrderClassTest{
    private static Id recordTypeId = Schema.SObjectType.Line_Item__c.getRecordTypeInfosByName().get('GAS Cylinders').getRecordTypeId();
    private static Id recordTypeIdVendor = Schema.SObjectType.Account.getRecordTypeInfosByName().get('GAS Vendors').getRecordTypeId();
    private static Id recordTypeIdeOrderAdmin = Schema.SObjectType.eOrders__c.getRecordTypeInfosByName().get('GAS eOrder Admin').getRecordTypeId();
    private static Id recordTypeIdeOrderReturn = Schema.SObjectType.eOrders__c.getRecordTypeInfosByName().get('GAS eOrder Return').getRecordTypeId();
    private static Id recordTypeIdOrderRequest = Schema.SObjectType.Order_Request__C.getRecordTypeInfosByName().get('GAS Order Request').getRecordTypeId();
    private static Id recordTypeIdeOrderItem = Schema.SObjectType.eOrder_Item__c.getRecordTypeInfosByName().get('GAS eOrder Item').getRecordTypeId();
    private static Id recordTypeIdReturn =Schema.SObjectType.Line_Item__c.getRecordTypeInfosByName().get('GAS Cylinders Return').getRecordTypeId();
     private static Id recordTypeIdProduct =Schema.SObjectType.EPA_Product__c.getRecordTypeInfosByName().get('GAS Order Product').getRecordTypeId();
    static testMethod void afterInsert(){
        
        User u =[select id from user where UserName='GAS2@test.org'];
        system.runAs(u){
            account acc= new account();
            acc.name = 'Conde Nast';
            acc.Active__c = TRUE;
            acc.RecordTypeId = recordTypeIdVendor;
            insert acc;
            
            // Mounika Suram 10/15/2018 Updated the test code for the added feature in ORDGAS_eorder
            Order_Request__c order = [select id, Requester_Org__c from order_request__c where recordTypeId = :recordTypeIdOrderRequest order by Name limit 1];
            Account org= [Select id, name from Account where name =:order.Requester_Org__c];
            
            EPA_Product__c product =new EPA_Product__c ();
            product.recordTypeId =recordTypeIdProduct;
            product.Product_Name__c = 'test';
            product.Product_Code__c = 'TT';
            product.List_Price__c = 5.00;
            product.Active__c = TRUE;
            product.Vendor__c = acc.id;
            insert Product;
            
            eOrders__c eorder = new eOrders__c();
            eorder.Description__c = 'test';
            eorder.Order_Amount__c= 50.0;
            eorder.Status__c  = 'Draft';
            eorder.RecordTypeId = recordTypeIdeOrderAdmin;
            eorder.Vendor_Name__c = acc.Id;
            eorder.Organization_Name__c = org.Id;
            
            eOrder_Item__c item = new eOrder_Item__c ();
            item.recordTypeId =recordTypeIdeOrderItem;
            item.Product__c = product.Id;
            item.Quantity__c = 400.0;
            item.Status__c = 'Request Approved';
            item.product__c = product.Id;
            item.Order_Request__c= order.Id;        
            test.StartTest();
            Insert item;
            insert eorder;
            test.StopTest();
        }
        
    }
    static testMethod void NegativeTest(){
        try {
            map<Id,eOrders__c> eOrderOldMap = new map<Id,eOrders__c> ();
            //id testId = 'Test';
             User u =[select id from user where UserName='GAS2@test.org'];
       			system.runAs(u){
            
                    
                    account acc= new account();
                    acc.name = 'Conde Nast';
                    acc.Active__c = TRUE;
                    acc.RecordTypeId = recordTypeIdVendor;
                    insert acc;
                    account acc1 = new Account(name='Vermonte', Active__C = true,RecordTypeId = recordTypeIdVendor);
                    insert acc1;
                     // Mounika Suram 10/15/2018 Updated the test code for the added feature in ORDGAS_eorder
                    Order_Request__c order = [select id, Requester_Org__c from order_request__c where recordTypeId = :recordTypeIdOrderRequest order by Name limit 1];
                    Account org= [Select id, name from Account where name =:order.Requester_Org__c];
                    
                    EPA_Product__c product =new EPA_Product__c ();
                    product.recordTypeId =recordTypeIdProduct;
                    product.Product_Name__c = 'test';
                    product.Product_Code__c = 'TT';
                    product.List_Price__c = 5.00;
                    product.Active__c = TRUE;
                    product.Vendor__c = acc.Id;
                    insert Product;
                    
                    eOrders__c eorder = new eOrders__c();
                    eorder.Description__c = 'test';
                    eorder.RecordTypeId = recordTypeIdeOrderAdmin;
                    eorder.Order_Amount__c= 50.0;
                    eorder.Status__c  = 'Activated';
                    eorder.Vendor_Name__c = acc1.Id;
                    eorder.Organization_Name__c = acc1.Id;
                    insert eorder;
                    
                    eorders__c eorder1 = new eorders__c();
                    eorder1.Description__c = 'test';
                    eorder1.Order_Amount__c= 50.0;
                    eorder1.Status__c  = 'Activated';
                    eorder.Status__c  = null;
                    update eorder;
                    
                    eOrderOldMap.put(eorder.Id,eorder1);
                    
                    eOrder_Item__c item = new eOrder_Item__c ();
                    //item.Product__c = product.Id;
                    item.recordTypeId =recordTypeIdeOrderItem;
                    item.Quantity__c = 400.0;
                    item.Status__c = 'Added to Order';
                    item.eOrder__c  = eorder.Id;
                    item.product__c = product.Id;
                    item.Order_Request__c= order.Id; 
                    test.StartTest();
                    ORDGAS_eOrderClass.ActivatedStatus(eorder,eOrderOldMap);
                    test.StopTest();
                   }
            }
            Catch(Exception Ex){
                    System.assert(Ex.getMessage().Contains('eOrder cannot be created. The chosen Vendor and Organization has no open Order Requests associated with it'));
                }
         
    	
    }
    static testMethod void afterUpdateTrigger(){
        User u =[select id from user where UserName='GAS2@test.org'];
       		system.runAs(u){
            account acc= new account();
            acc.name = 'Conde Nast';
            acc.Active__c = TRUE;
            acc.RecordTypeId = recordTypeIdVendor;
            insert acc;
            EPA_Product__c product =new EPA_Product__c ();
            product.recordTypeId =recordTypeIdProduct;
            product.Product_Name__c = 'test';
            product.Product_Code__c = 'TT';
            product.List_Price__c = 5.00;
            product.Active__c = TRUE;
            product.Vendor__c = acc.id;
            insert Product;
                
            eOrders__c eorder = new eOrders__c();
            eorder.RecordTypeId = recordTypeIdeOrderAdmin;
            eorder.Description__c = 'test';
            eorder.Order_Amount__c= 50.0;
            eorder.Status__c  = 'Activated';
            eorder.Vendor_Name__c = acc.Id;
            insert eorder;
                
            eOrder_Item__c item = new eOrder_Item__c ();
          	item.recordTypeId =recordTypeIdeOrderItem;
            item.Product__c = product.Id;
            item.eOrder__c = eorder.id;
            item.Quantity__c = 400.0;
            item.Status__c = 'Order Placed';
            Insert item;
            // Mounika Suram 10/15/2018 Updated the test code for the added feature in ORDGAS_eorder
            eorder.Status__c  = 'Order Placed';
            test.StartTest();
            update eorder;
            test.StopTest();
        }
        
    }
    static testMethod void afterInsertTrigger(){
       User u =[select id from user where UserName='GAS2@test.org'];
       		system.runAs(u){
            
            account acc= new account();
            acc.name = 'Conde Nast';
            acc.Active__c = TRUE;
            acc.RecordTypeId = recordTypeIdVendor;
            insert acc;
            
            // Mounika Suram 10/15/2018 Updated the test code for the added feature in ORDGAS_eorder
            Order_Request__c order = [select id, Requester_Org__c from order_request__c where recordTypeId = :recordTypeIdOrderRequest order by Name limit 1];
            Account org= [Select id, name from Account where name =:order.Requester_Org__c];
            
            EPA_Product__c product =new EPA_Product__c ();
            product.recordTypeId =recordTypeIdProduct;
            product.Product_Name__c = 'test';
            product.Product_Code__c = 'TT';
            product.List_Price__c = 5.00;
            product.Active__c = TRUE;
            product.Vendor__c = acc.id;
            insert Product;
            eOrder_Item__c item = new eOrder_Item__c ();
            item.recordTypeId =recordTypeIdeOrderItem;
            item.Product__c = product.Id;
            item.Quantity__c = 400.0;
            item.Status__c = 'Request Approved';
            //item.eOrder__c = eorder.id; 
            item.Order_Request__c= order.Id;  
            Insert item;
                
            eOrders__c eorder = new eOrders__c();
            eorder.RecordTypeId = recordTypeIdeOrderAdmin;
            eorder.Description__c = 'test';
            eorder.Order_Amount__c= 50.0;
            eorder.Status__c  = 'Draft';
            eorder.Vendor_Name__c = acc.Id;
            eorder.Organization_Name__c = org.Id;
            insert eorder;
            
            test.StartTest();
            eorder.Status__c  = 'Order Placed';
            update eorder;
            eorder.Status__c  = 'Full Order Received';
            update eorder;
            test.StopTest();
        
    	}
    }
    
    static testMethod void afterInsertReturnTrigger(){
     User u =[select id from user where UserName='GAS2@test.org'];
       		system.runAs(u){                
            account acc= new account();
            acc.name = 'Conde Nast';
            acc.Active__c = TRUE;
            acc.RecordTypeId = recordTypeIdVendor;
            insert acc;
             // Mounika Suram 10/15/2018 Updated the test code for the added feature in ORDGAS_eorder
            Order_Request__c order = [select id, Requester_Org__c from order_request__c where recordTypeId = :recordTypeIdOrderRequest order by Name limit 1];
            Account org= [Select id, name from Account where name =:order.Requester_Org__c];
            
            EPA_Product__c product =new EPA_Product__c ();
            product.recordTypeId =recordTypeIdProduct;
            product.Product_Name__c = 'test';
            product.Product_Code__c = 'TT';
            product.List_Price__c = 5.00;
            product.Active__c = TRUE;
            product.Vendor__c = acc.id;
            insert Product;
            
            eOrders__c eorder = new eOrders__c();
            eorder.RecordTypeId = recordTypeIdeOrderReturn;
            eorder.Description__c = 'test';
            eorder.Order_Amount__c= 50.0;
            eorder.Status__c  = 'Order Placed';
            eorder.Vendor_Name__c = acc.Id;
            eorder.Organization_Name__c = org.Id;
            
            eOrder_Item__c item = new eOrder_Item__c ();
            item.recordTypeId =recordTypeIdeOrderItem;
            item.Product__c = product.Id;
            item.Quantity__c = 400.0;
            item.Status__c = 'Added to Order';
            item.eOrder__c = eorder.id; 
            item.Order_Request__c= order.Id;   
            
            Line_Item__c  line = new Line_Item__c ();
            line.recordTypeId=recordTypeIdReturn;
            line.Product__c = product.Id;
            line.Quantity__c = 400.0;
            line.Status__c = 'Cylinder Return Request';
            line.eOrder_Return__c = eorder.id; 
            line.Order_Request__c= order.Id; 
            Insert line;
            test.StartTest();
            insert eorder;
            test.StopTest();
            }
        
    }
    @TestSetup
    private static void setup()
    {
        // Create a sample form statement object and then submit it for approval.
            
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
		
        // Create User Record
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com',
        EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
        LocaleSidKey='en_US', ProfileId = p.Id,
        CompanyName='OEI',Department='OEI',
        TimeZoneSidKey='America/Los_Angeles',
        UserName='GAS2@test.org');
        insert u;
        
        

        PermissionSet ps = [SELECT ID From PermissionSet WHERE Name = 'GAS_Application_Admin'];
        insert new PermissionSetAssignment(AssigneeId = u.id, PermissionSetId = ps.Id ); 
        system.runas(u){
            account a = new account();
            a.Name='OEI';
            insert a;
            Order_Request__c request =new Order_Request__c();
            request.Stage__c = 'New Order';
            request.RecordTypeId=recordTypeIdOrderRequest;
            insert request;
        }
    }
}