objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>GAS Vendor Data</description>
        <inlineHelpText>Active Vendors are CHECKED by default.</inlineHelpText>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/eOrder_Item__c.object
<CustomObject>
    <fields>
        <fullName>Delivery_Date__c</fullName>
        <description>GAS Application</description>
        <inlineHelpText>Delivery Date by Vendor</inlineHelpText>
        <label>Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Order_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Request</label>
        <referenceTo>Order_Request__c</referenceTo>
        <relationshipLabel>Order Request Items</relationshipLabel>
        <relationshipName>eOrder_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Code__c</fullName>
        <formula>Product__r.Product_Code__c</formula>
        <label>Product Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Choose a Product by searching for Product details</description>
        <inlineHelpText>Choose a Product by searching for Product details</inlineHelpText>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>EPA_Product__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>EPA_Product__c.Vendor__r.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>EPA_Product__c</referenceTo>
        <relationshipLabel>eOrder Items</relationshipLabel>
        <relationshipName>eOrder_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <description>Number of cylinders requested</description>
        <inlineHelpText>Number of cylinders requested</inlineHelpText>
        <label>Quantity</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <description>Specific or detailed items within an order tracked in the eOrders document, initially for the GAS application.  (Similar to Line Items, into which this item might be merged someday.)</description>
    <label>eOrder Item</label>
    <nameField>
        <displayFormat>EPA-EOI-{000000000}</displayFormat>
        <label>eOrder Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>eOrder Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/eOrders__c.object
<CustomObject>
    <fields>
        <fullName>Order_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Request</label>
        <referenceTo>Order_Request__c</referenceTo>
        <relationshipLabel>eOrders</relationshipLabel>
        <relationshipName>eOrders</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>Custom Object to Capture Orders placed for GAS Order Management Application.</description>
    <label>eOrder</label>
    <nameField>
        <displayFormat>EPA-EO-{000000000}</displayFormat>
        <label>eOrder ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>eOrders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/EPA_Product__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>List_Price__c</fullName>
        <label>Unit Price</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_Code__c</fullName>
        <description>Product Code</description>
        <inlineHelpText>Product Code</inlineHelpText>
        <label>Product Code</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <label>Product Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Vendors MUST be Active and Valid Account Record Type.</errorMessage>
            <filterItems>
                <field>Account.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>GAS Vendors</value>
            </filterItems>
            <infoMessage>Vendors MUST be Active.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>Products being acquired, products being generated by a process or system, or other kinds of objects being tracked, managed, reported on, etc.  Used initially for gas cylinder products being procured in the GAS application.</description>
    <label>Product</label>
    <nameField>
        <displayFormat>EPA-P-{0000000000}</displayFormat>
        <label>Product ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Order_Request__c.object
<CustomObject>
    <fields>
        <fullName>Branch_Chief_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Personnel responsible for Approving your Order Request</description>
        <inlineHelpText>Personnel responsible for Approving your Order Request</inlineHelpText>
        <label>Branch Chief Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Requests2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Delivery_Date__c</fullName>
        <description>Gas</description>
        <inlineHelpText>Potential Delivery Date</inlineHelpText>
        <label>Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Delivery_facilities__c</fullName>
        <description>GAS</description>
        <inlineHelpText>Choose a Building for delivery of GAS Cylinders</inlineHelpText>
        <label>Building</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HSF</fullName>
                    <color>#0B6FCE</color>
                    <label>Human Studies Facility</label>
                </value>
                <value>
                    <fullName>Page Rd</fullName>
                    <color>#78C953</color>
                    <label>Page Road</label>
                </value>
                <value>
                    <fullName>RTP</fullName>
                    <color>#E27001</color>
                    <label>Research Triangle Park</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Facility_Location__c</fullName>
        <description>GAS</description>
        <inlineHelpText>Choose the specific Delivery/Pick-up Location within the Building</inlineHelpText>
        <label>Delivery/Pick-up Location</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Delivery_facilities__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Annex - A045</fullName>
                    <color>#0B6FCE</color>
                    <label>Annex - A045</label>
                </value>
                <value>
                    <fullName>Bldg A - 164 Shop</fullName>
                    <color>#78C953</color>
                    <label>Bldg A - 164 Shop</label>
                </value>
                <value>
                    <fullName>Bldg A - 165</fullName>
                    <color>#E27001</color>
                    <label>Bldg A - 165</label>
                </value>
                <value>
                    <fullName>Bldg A - 280C</fullName>
                    <color>#A845DC</color>
                    <label>Bldg A - 280C</label>
                </value>
                <value>
                    <fullName>Bldg B - 151A</fullName>
                    <color>#F3D904</color>
                    <label>Bldg B - 151A</label>
                </value>
                <value>
                    <fullName>Bldg B - 154</fullName>
                    <color>#A53711</color>
                    <label>Bldg B - 154</label>
                </value>
                <value>
                    <fullName>Bldg B - 175</fullName>
                    <color>#66E9BD</color>
                    <label>Bldg B - 175</label>
                </value>
                <value>
                    <fullName>Bldg B - 251</fullName>
                    <color>#0B24BE</color>
                    <label>Bldg B - 251</label>
                </value>
                <value>
                    <fullName>Bldg B - 254A</fullName>
                    <color>#419249</color>
                    <label>Bldg B - 254A</label>
                </value>
                <value>
                    <fullName>Bldg B - 255 SC</fullName>
                    <color>#B6E32E</color>
                    <label>Bldg B - 255 SC</label>
                </value>
                <value>
                    <fullName>Bldg B - 261A</fullName>
                    <color>#641CCF</color>
                    <label>Bldg B - 261A</label>
                </value>
                <value>
                    <fullName>Bldg B - 261C</fullName>
                    <color>#F96FB7</color>
                    <label>Bldg B - 261C</label>
                </value>
                <value>
                    <fullName>Bldg B - 263A</fullName>
                    <color>#2F5D85</color>
                    <label>Bldg B - 263A</label>
                </value>
                <value>
                    <fullName>Bldg B - 266A</fullName>
                    <color>#AFCADF</color>
                    <label>Bldg B - 266A</label>
                </value>
                <value>
                    <fullName>Bldg B - 266B</fullName>
                    <color>#8F6429</color>
                    <label>Bldg B - 266B</label>
                </value>
                <value>
                    <fullName>Bldg B - 266C</fullName>
                    <color>#EFAE73</color>
                    <label>Bldg B - 266C</label>
                </value>
                <value>
                    <fullName>Bldg B - 275A</fullName>
                    <color>#57F17C</color>
                    <label>Bldg B - 275A</label>
                </value>
                <value>
                    <fullName>Bldg B - 278</fullName>
                    <color>#0B6FCE</color>
                    <label>Bldg B - 278</label>
                </value>
                <value>
                    <fullName>Bldg B - 278C</fullName>
                    <color>#78C953</color>
                    <label>Bldg B - 278C</label>
                </value>
                <value>
                    <fullName>Bldg B - 280</fullName>
                    <color>#E27001</color>
                    <label>Bldg B - 280</label>
                </value>
                <value>
                    <fullName>Bldg B - 280A</fullName>
                    <color>#A845DC</color>
                    <label>Bldg B - 280A</label>
                </value>
                <value>
                    <fullName>Bldg B - 284A</fullName>
                    <color>#F3D904</color>
                    <label>Bldg B - 284A</label>
                </value>
                <value>
                    <fullName>Bldg B - 286A</fullName>
                    <color>#A53711</color>
                    <label>Bldg B - 286A</label>
                </value>
                <value>
                    <fullName>Bldg B - 287A</fullName>
                    <color>#66E9BD</color>
                    <label>Bldg B - 287A</label>
                </value>
                <value>
                    <fullName>Bldg B - 289</fullName>
                    <color>#0B24BE</color>
                    <label>Bldg B - 289</label>
                </value>
                <value>
                    <fullName>Bldg B - 291A</fullName>
                    <color>#419249</color>
                    <label>Bldg B - 291A</label>
                </value>
                <value>
                    <fullName>Bldg B - 299B</fullName>
                    <color>#B6E32E</color>
                    <label>Bldg B - 299B</label>
                </value>
                <value>
                    <fullName>Bldg B - 299C</fullName>
                    <color>#641CCF</color>
                    <label>Bldg B - 299C</label>
                </value>
                <value>
                    <fullName>Bldg B - 352</fullName>
                    <color>#F96FB7</color>
                    <label>Bldg B - 352</label>
                </value>
                <value>
                    <fullName>Bldg B - 353</fullName>
                    <color>#2F5D85</color>
                    <label>Bldg B - 353</label>
                </value>
                <value>
                    <fullName>HSF - 209</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <description>Current state of the Order Request</description>
        <inlineHelpText>Current state of the Order Request</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New Order</fullName>
                    <default>true</default>
                    <label>New Order</label>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Request Approved</fullName>
                </value>
                <value>
                    <fullName>Order Placed</fullName>
                </value>
                <value>
                    <fullName>Partial Order Received</fullName>
                </value>
                <value>
                    <fullName>Full Order Received</fullName>
                </value>
                <value>
                    <fullName>Order Fulfilled</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Requests for orders to be placed.  Initially used in the GAS application, then in PCORS, and available for other uses.  Used not only in native licensed access ("Type 3 interface" in BAP parlance) but also in "Type 1" interface (unlicensed guest access).</description>
    <label>Order Request</label>
    <nameField>
        <displayFormat>EPA-OR-{000000000}</displayFormat>
        <label>Order Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ORDGAS_OrderRequest_TotalsTest.cls
/*
*    Author : mondal.javed@epa.gov
*    CreatedDate : 10-August-2018
*    Class Name : ORDGAS_OrderRequest_TotalsTest
*    Test Class for ORDGAS_OrderRequest_Totals
**/

@isTest
Public Class ORDGAS_OrderRequest_TotalsTest{
	 private static Id recordTypeId = Schema.SObjectType.Line_Item__c.getRecordTypeInfosByName().get('GAS Cylinders').getRecordTypeId();
    private static Id recordTypeIdVendor = Schema.SObjectType.Account.getRecordTypeInfosByName().get('GAS Vendors').getRecordTypeId();
    private static Id recordTypeIdeOrderAdmin = Schema.SObjectType.eOrders__c.getRecordTypeInfosByName().get('GAS eOrder Admin').getRecordTypeId();
    private static Id recordTypeIdeOrderReturn = Schema.SObjectType.eOrders__c.getRecordTypeInfosByName().get('GAS eOrder Return').getRecordTypeId();
    private static Id recordTypeIdOrderRequest = Schema.SObjectType.Order_Request__C.getRecordTypeInfosByName().get('GAS Order Request').getRecordTypeId();
    private static Id recordTypeIdeOrderItem = Schema.SObjectType.eOrder_Item__c.getRecordTypeInfosByName().get('GAS eOrder Item').getRecordTypeId();
    private static Id recordTypeIdReturn =Schema.SObjectType.Line_Item__c.getRecordTypeInfosByName().get('GAS Cylinders Return').getRecordTypeId();
    private static Id recordTypeIdProduct =Schema.SObjectType.EPA_Product__c.getRecordTypeInfosByName().get('GAS Order Product').getRecordTypeId();
    
    static testMethod void afterUpdateTrigger(){
       
        
        User u =[select id from user where UserName='GAS3@test.org'];
        system.runAs(u){
            //Create Gas Organization
            account acc= new account();
            acc.name = 'Conde Nast';
            acc.Active__c = TRUE;
            acc.RecordTypeId = recordTypeIdVendor;
            insert acc;
            
            //Create Product
            EPA_Product__c product =new EPA_Product__c ();
            product.recordTypeId =recordTypeIdProduct;
            product.Product_Name__c = 'test';
            product.Product_Code__c = 'TT';
            product.List_Price__c = 5.00;
            product.Active__c = TRUE;
            product.Vendor__c = acc.id;
            insert Product;
            
            //Create Order Request
            Order_Request__c orderreq = new Order_Request__c();
            orderreq.RecordTypeId = recordTypeIdOrderRequest;
            orderreq.Delivery_facilities__c = 'HSF';
            orderreq.Facility_Location__c = 'HSF - 209';
            orderreq.Delivery_Date__c = Date.newInstance(2019, 5, 22);
            orderreq.Branch_Chief_Name__c = u.id;
            insert orderreq;
            
            //Create eOrder Item
            eOrder_Item__c item = new eOrder_Item__c ();
           	item.recordTypeId =recordTypeIdeOrderItem;
            item.Product__c = product.Id;
            item.Order_Request__c = orderreq.id;
            item.Quantity__c = 4.0;
            Insert item;
            
            //Update Order Request
            orderreq.Stage__c  = 'Request Approved';
            
            test.StartTest();
            update orderreq;
            test.StopTest();
        } 
    }
    @TestSetup
    private static void setup()
    {
        // Create a sample form statement object and then submit it for approval.
            
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
		
        // Create User Record
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com',
        EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
        LocaleSidKey='en_US', ProfileId = p.Id,
        CompanyName='OEI',Department='OEI',
        TimeZoneSidKey='America/Los_Angeles',
        UserName='GAS3@test.org');
        insert u;
        
        

        PermissionSet ps = [SELECT ID From PermissionSet WHERE Name = 'GAS_Application_Admin'];
        insert new PermissionSetAssignment(AssigneeId = u.id, PermissionSetId = ps.Id ); 
        system.runas(u){
            account a = new account();
            a.Name='OEI';
            insert a;
            Order_Request__c request =new Order_Request__c();
            request.Stage__c = 'New Order';
            request.RecordTypeId=recordTypeIdOrderRequest;
            insert request;
        }
    }
    
}