objects/Account.object
<CustomObject>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts_User2</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Award__c.object
<CustomObject>
    <fields>
        <fullName>Authorizing_Official__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Requesting official's supervisor. Responsible for the award's first level of approval.</description>
        <label>Authorizing Official</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Awards_Authorizing_Official</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Budget__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Budget that the award will be allocated toward.</description>
        <label>Budget</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Document__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Document - Award Budget</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Document__c</referenceTo>
        <relationshipLabel>Awards</relationshipLabel>
        <relationshipName>Budgeted_Awards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cash_Award_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Amount of award given to employee (monetary awards only).</description>
        <inlineHelpText>Cash Awards over $2,000 require AO approval. Collective awards over $5,000 for an awardee require two levels of approval.</inlineHelpText>
        <label>Cash Award Amount</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Extent_of_Contribution__c</fullName>
        <description>Extent of Contribution as defined on EPA's recommendation for incentive award form.</description>
        <label>Extent of Contribution</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Limited</fullName>
                </value>
                <value>
                    <fullName>Extended</fullName>
                </value>
                <value>
                    <fullName>Broad</fullName>
                </value>
                <value>
                    <fullName>General</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HR_Reviewed_Date__c</fullName>
        <label>HR Reviewed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Outside_ORD__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if the award is going to an individual outside of the RPIO.</description>
        <inlineHelpText>Please check if the Awardee is outside of ORD. If you do not check this field for non-ORD employees, the award will be at risk of not being processed.</inlineHelpText>
        <label>Outside ORD</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Planned_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Planned Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Requesting_Official__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Requesting Official Contact Lookup</description>
        <inlineHelpText>Requesting Official. The individual submitting the award. Please note, the budget is assigned based on the RO's organization.</inlineHelpText>
        <label>Requesting Official</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Awards (Contact)</relationshipLabel>
        <relationshipName>Awards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Planned</fullName>
                    <default>true</default>
                    <label>Planned</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Pending Direct Supervisor Approval</fullName>
                </value>
                <value>
                    <fullName>HR Review</fullName>
                </value>
                <value>
                    <fullName>Sent for Union Review</fullName>
                </value>
                <value>
                    <fullName>Ready for FPPS</fullName>
                </value>
                <value>
                    <fullName>Entered into FPPS</fullName>
                </value>
                <value>
                    <fullName>Ready for Bulk Upload</fullName>
                </value>
                <value>
                    <fullName>Bulk Uploaded</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                    <isActive>false</isActive>
                    <label>Approved</label>
                </value>
                <value>
                    <fullName>Awaiting Funding</fullName>
                    <isActive>false</isActive>
                    <label>Awaiting Funding</label>
                </value>
                <value>
                    <fullName>Funded</fullName>
                    <isActive>false</isActive>
                    <label>Funded</label>
                </value>
                <value>
                    <fullName>Partially Paid</fullName>
                    <isActive>false</isActive>
                    <label>Partially Paid</label>
                </value>
                <value>
                    <fullName>Ready for SSC</fullName>
                    <isActive>false</isActive>
                    <label>Ready for SSC</label>
                </value>
                <value>
                    <fullName>Ready for Work Codes</fullName>
                    <isActive>false</isActive>
                    <label>Ready for Work Codes</label>
                </value>
                <value>
                    <fullName>Received by OARS/Approved</fullName>
                    <isActive>false</isActive>
                    <label>Received by OARS/Approved</label>
                </value>
                <value>
                    <fullName>Reference</fullName>
                    <isActive>false</isActive>
                    <label>Reference</label>
                </value>
                <value>
                    <fullName>To SSC</fullName>
                    <isActive>false</isActive>
                    <label>To SSC</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Supervisor_Justification__c</fullName>
        <inlineHelpText>If using the group award functionality, this field will automatically assume the justification of the group award.</inlineHelpText>
        <label>Supervisor Justification</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Type_of_Benefit__c</fullName>
        <label>Type of Benefit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Tangible</fullName>
                </value>
                <value>
                    <fullName>Intangible</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Value_and_Application__c</fullName>
        <description>Combined Value of Benefit and Extent of Application field with corresponding amount ranges.</description>
        <inlineHelpText>Select the applicable Value of Benefit and Extent of Application combination. The Cash Award amount will be restricted based on the corresponding amount range.</inlineHelpText>
        <label>Value and Application</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>MODERATE VALUE &amp; LIMITED APPLICATION ($25-125)</fullName>
                </value>
                <value>
                    <fullName>MODERATE VALUE &amp; EXTENDED APPLICATION ($125-325)</fullName>
                </value>
                <value>
                    <fullName>MODERATE VALUE &amp; BROAD APPLICATION ($325-650)</fullName>
                </value>
                <value>
                    <fullName>MODERATE VALUE &amp; GENERAL APPLICATION ($650-1,300)</fullName>
                </value>
                <value>
                    <fullName>SUBSTANTIAL VALUE &amp; LIMITED APPLICATION ($125-325)</fullName>
                </value>
                <value>
                    <fullName>SUBSTANTIAL VALUE &amp; EXTENDED APPLICATION ($325-650)</fullName>
                </value>
                <value>
                    <fullName>SUBSTANTIAL VALUE &amp; BROAD APPLICATION ($650-1,300)</fullName>
                </value>
                <value>
                    <fullName>SUBSTANTIAL VALUE &amp; GENERAL APPLICATION ($1,300-3,100)</fullName>
                </value>
                <value>
                    <fullName>HIGH VALUE &amp; LIMITED APPLICATION ($325-650)</fullName>
                </value>
                <value>
                    <fullName>HIGH VALUE &amp; EXTENDED APPLICATION ($650-1,300)</fullName>
                </value>
                <value>
                    <fullName>HIGH VALUE &amp; BROAD APPLICATION ($1,300-3,150)</fullName>
                </value>
                <value>
                    <fullName>HIGH VALUE &amp; GENERAL APPLICATION ($3,150-5,000)</fullName>
                </value>
                <value>
                    <fullName>EXCEPTIONAL VALUE &amp; LIMITED APPLICATION ($650-1,300)</fullName>
                </value>
                <value>
                    <fullName>EXCEPTIONAL VALUE &amp; EXTENDED APPLICATION ($1,300-3,150)</fullName>
                </value>
                <value>
                    <fullName>EXCEPTIONAL VALUE &amp; BROAD APPLICATION ($3,150-6,000)</fullName>
                </value>
                <value>
                    <fullName>EXCEPTIONAL VALUE &amp; BROAD APPLICATION ($3,150-5,000)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Value_of_Benefit__c</fullName>
        <description>Value of Benefit as defined on EPA's recommendation for incentive award form.</description>
        <label>Value of Benefit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Moderate</fullName>
                </value>
                <value>
                    <fullName>Substantial</fullName>
                </value>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Exceptional</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Award given to employee (or eventually to other recipients).  First used in AART.</description>
    <label>Award</label>
    <nameField>
        <displayFormat>AWARD-{0000000}</displayFormat>
        <label>Award Internal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Awards</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Supervisor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Approving Supervisor.  The end user may edit his approving supervisor from the "Edit My Approvers" page.</description>
        <label>Approving Supervisor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contact_Supervisor</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Supervisor__c</fullName>
        <description>Deprecated.  Use the Contact's Approving Supervisor instead.</description>
        <inlineHelpText>Deprecated.  Use the Contact's Approving Supervisor instead.</inlineHelpText>
        <label>(Deprecated) Approving Supervisor</label>
        <relationshipName>Supervisor</relationshipName>
        <restrictedAdminField>false</restrictedAdminField>
        <type>Hierarchy</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/ARTTAwardPlannerComponentController_Test.cls
/**
 * Created by justin.dove on 2019-04-30.
 */

@IsTest
public with sharing class ARTTAwardPlannerComponentController_Test {
    static Id AWARD_CASH_RECORDTYPE_ID = Schema.SObjectType.Award__c.getRecordTypeInfosByName().get('Cash Award').getRecordTypeId();
    static String VALUE_APPLICATION_EXCEPTIONAL = 'EXCEPTIONAL VALUE & EXTENDED APPLICATION ($1,300-3,150)';

    @TestSetup
    public static void testData() {
        Account hrOrg = AwardTestUtilities.createOrganization('ORD-OARS');
        insert hrOrg;

        List<Contact> employees = new List<Contact>();
        for (Integer i = 0; i < 3; i++) {
            Contact employee = AwardTestUtilities.createEmployee(hrOrg);
            employee.LastName = employee.LastName + i;

            employees.add(employee);
        }
        insert employees;

        Document__c budget = new Document__c();
        budget.RecordTypeId = Schema.SObjectType.Document__c.getRecordTypeInfosByName().get(AwardConstants.AWARD_BUDGET_DOCUMENT_RECORDTYPE_NAME).getRecordTypeId();
        budget.Award_Total_Budget__c = 10000;
        budget.Award_Budget_Start_Date__c = System.today();
        insert budget;

        List<Award__c> awards = new List<Award__c>();
        for (Integer i = 0; i < employees.size(); i++) {
            Award__c award = AwardTestUtilities.createAward(employees[i]);
            award.RecordTypeId = AWARD_CASH_RECORDTYPE_ID;
            award.Budget__c = budget.Id;
            award.Planned_Date__c = System.today();
            award.OwnerId = UserInfo.getUserId();

            awards.add(award);
        }
        insert awards;
    }

    @IsTest
    public static void getAwardAndBudget() {
        Contact employee = [SELECT Id FROM Contact LIMIT 1];

        Account hrOrg = AwardTestUtilities.createOrganization('ORD-OARS');
        insert hrOrg;

        Document__c budget = new Document__c();
        budget.RecordTypeId = Schema.SObjectType.Document__c.getRecordTypeInfosByName().get(AwardConstants.AWARD_BUDGET_DOCUMENT_RECORDTYPE_NAME).getRecordTypeId();
        budget.Award_Total_Budget__c = 10000;
        budget.Award_Budget_Start_Date__c = System.today();
        budget.Award_Budget_Org__c = hrOrg.Id;
        insert budget;

        Award__c award = AwardTestUtilities.createAward(employee);
        award.RecordTypeId = AWARD_CASH_RECORDTYPE_ID;
        award.Budget__c = budget.Id;
        award.Planned_Date__c = System.today();
        award.OwnerId = UserInfo.getUserId();
        insert award;

        test.startTest();
        List<Document__c> budgets = ARTTAwardPlannerComponentController.getBudgets();
        List<Award__c> awards = ARTTAwardPlannerComponentController.getAwards();
        List<Award__c> filteredAwards = ARTTAwardPlannerComponentController.getFilteredAwards(hrOrg.Name);

        award.Cash_Award_Amount__c = 300;
        ARTTAwardPlannerComponentController.saveAwards(new List<Award__c>{ award });
        test.stopTest();

        System.assertNotEquals(null, budgets, 'Should have returned inserted budgets.');
        System.assertNotEquals(null, awards, 'Should have returned inserted awards.');
        System.assertNotEquals(null, filteredAwards, 'Should have returned an award filtered by HR Org name.');
    }

    @IsTest
    public static void testSubmitAwards() {
        Contact employee = [SELECT Id FROM Contact LIMIT 1];
        Document__c budget = [SELECT Id FROM Document__c LIMIT 1];
        Account budgetOrg = [SELECT Id FROM Account LIMIT 1];

        // IOAA Supervisor User on the award.
        User testIoaaSupervisor = AwardTestUtilities.createTestUser();
        testIoaaSupervisor.LastName = 'IOAA Supervisor';
        testIoaaSupervisor.Username = 'test.ioaasupervisor@epa.gov.test';
        insert testIoaaSupervisor;

        // User's supervisor related on the User's related contact.
        User testUserSupervisor = AwardTestUtilities.createTestUser();
        testUserSupervisor.LastName = 'User Supervisor';
        testUserSupervisor.Username = 'test.usersupervisor@epa.gov.test';
        testUserSupervisor.DelegatedApproverId = testIoaaSupervisor.Id;
        insert testUserSupervisor;

        Contact roContact = AwardTestUtilities.createEmployee(budgetOrg);
        roContact.User__c = UserInfo.getUserId();
        roContact.Supervisor__c = testUserSupervisor.Id;
        insert roContact;

        // User who is listed as the awardee's supervisor.
        User testAwardeeSupervisor = AwardTestUtilities.createTestUser();
        testAwardeeSupervisor.LastName = 'User Supervisor';
        testAwardeeSupervisor.Username = 'test.awardeesupervisor@epa.gov.test';
        testAwardeeSupervisor.DelegatedApproverId = testUserSupervisor.Id;
        insert testAwardeeSupervisor;

        Award__c award = AwardTestUtilities.createAward(employee);
        award.Cash_Award_Amount__c = 3000;
        award.Budget__c = budget.Id;
        award.Value_and_Application__c = AwardTestUtilities.VALUE_APPLICATION;
        award.Extent_of_Contribution__c = AwardTestUtilities.EXTENT_OF_CONTRIBUTION;
        award.Value_of_Benefit__c = AwardTestUtilities.VALUE_OF_BENEFIT;
        award.Type_of_Benefit__c = AwardTestUtilities.TYPE_OF_BENEFIT;
        award.Supervisor_Justification__c = AwardTestUtilities.SUPERVISOR_JUSTIFICATION;
        award.Value_and_Application__c = VALUE_APPLICATION_EXCEPTIONAL;
        award.RecordTypeId = AWARD_CASH_RECORDTYPE_ID;
        award.Authorizing_Official__c = UserInfo.getUserId();
        award.Requesting_Official__c = roContact.Id;
        award.Status__c = 'Planned';
        award.HR_Reviewed_Date__c = System.today();
        insert award;

        test.startTest();
        ARTTAwardPlannerComponentController.submitAwardsForApproval(new List<Award__c>{ award });
        test.stopTest();
    }

    @IsTest
    public static void testOutsideOrdAwardSubmit() {
        Contact employee = [SELECT Id FROM Contact LIMIT 1];
        Document__c budget = [SELECT Id FROM Document__c LIMIT 1];
        Account budgetOrg = [SELECT Id FROM Account LIMIT 1];

        Account outsideOrdOrg = AwardTestUtilities.createOrganization('AO-OES');
        insert outsideOrdOrg;

        Contact outsideOrdEmployee = AwardTestUtilities.createEmployee(outsideOrdOrg);
        insert outsideOrdEmployee;

        // IOAA Supervisor User on the award.
        User testIoaaSupervisor = AwardTestUtilities.createTestUser();
        testIoaaSupervisor.LastName = 'IOAA Supervisor';
        testIoaaSupervisor.Username = 'test.ioaasupervisor@epa.gov.test';
        insert testIoaaSupervisor;

        // User's supervisor related on the User's related contact.
        User testUserSupervisor = AwardTestUtilities.createTestUser();
        testUserSupervisor.LastName = 'User Supervisor';
        testUserSupervisor.Username = 'test.usersupervisor@epa.gov.test';
        testUserSupervisor.DelegatedApproverId = testIoaaSupervisor.Id;
        insert testUserSupervisor;

        Contact roContact = AwardTestUtilities.createEmployee(budgetOrg);
        roContact.User__c = UserInfo.getUserId();
        roContact.Supervisor__c = testUserSupervisor.Id;
        insert roContact;

        // User who is listed as the awardee's supervisor.
        User testAwardeeSupervisor = AwardTestUtilities.createTestUser();
        testAwardeeSupervisor.LastName = 'User Supervisor';
        testAwardeeSupervisor.Username = 'test.awardeesupervisor@epa.gov.test';
        testAwardeeSupervisor.DelegatedApproverId = testUserSupervisor.Id;
        insert testAwardeeSupervisor;

        Award__c award = AwardTestUtilities.createAward(outsideOrdEmployee);
        award.Cash_Award_Amount__c = 3000;
        award.Budget__c = budget.Id;
        award.Value_and_Application__c = AwardTestUtilities.VALUE_APPLICATION;
        award.Extent_of_Contribution__c = AwardTestUtilities.EXTENT_OF_CONTRIBUTION;
        award.Value_of_Benefit__c = AwardTestUtilities.VALUE_OF_BENEFIT;
        award.Type_of_Benefit__c = AwardTestUtilities.TYPE_OF_BENEFIT;
        award.Supervisor_Justification__c = AwardTestUtilities.SUPERVISOR_JUSTIFICATION;
        award.Value_and_Application__c = VALUE_APPLICATION_EXCEPTIONAL;
        award.RecordTypeId = AWARD_CASH_RECORDTYPE_ID;
        award.Authorizing_Official__c = UserInfo.getUserId();
        award.Requesting_Official__c = roContact.Id;
        award.Status__c = 'Planned';
        award.HR_Reviewed_Date__c = System.today();
        award.Outside_ORD__c = true;
        insert award;

        test.startTest();
        ARTTAwardPlannerComponentController.submitAwardsForApproval(new List<Award__c>{ award });
        test.stopTest();
    }

}