objects/Accounting_Line__c.object
<CustomObject>
    <fields>
        <fullName>EPA_License__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>EPA License</label>
        <referenceTo>EPA_Agreement__c</referenceTo>
        <relationshipLabel>Royalties</relationshipLabel>
        <relationshipName>Royalties</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Amount__c</fullName>
        <description>FTTA License. Created to capture the payment amount assigned to the royalties.</description>
        <label>Payment Amount</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <description>Detailed financial line of accounting, first used in DCR &amp; PCORS applications.  Similar to Line Items, but more oriented toward providing financial details, e.g., commitments, obligations, &amp; payments detail lines associated with a financial document.</description>
    <label>Accounting Line</label>
    <nameField>
        <displayFormat>EPA-AL-{000000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accounting Lines</pluralLabel>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>FTTA_Royalties</fullName>
        <active>true</active>
        <label>FTTA Royalties</label>
    </recordTypes>
</CustomObject>

objects/EPA_Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Total_Royalties__c</fullName>
        <description>FTTA License. Created to capture the total royalties amount.</description>
        <inlineHelpText>Total Royalties Amount</inlineHelpText>
        <label>Total Royalties Amount</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <description>Information on an EPA Agreement, initially used for FTTA, but also available for other uses.  (Note that the similarly named Agreement object has a Master-Detail relationship with Project, which limits the breadth of its potential use, whereas this object has no such Master-Detail relationship, so it can be used in more situations.)</description>
    <label>EPA Agreement</label>
    <nameField>
        <displayFormat>EPA-{0000000}</displayFormat>
        <label>Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EPA Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>FTTA_License</fullName>
        <active>true</active>
        <description>FTTA License</description>
        <label>FTTA License</label>
    </recordTypes>
</CustomObject>

classes/FTTA_CalculateTotalRoyaltiesAmountTest.cls
/**********************************************************************
Name: FTTA_CalculateTotalRoyaltiesAmountTest()
======================================================
======================================================
Purpose: Unit testing of FTTA_CalculateTotalRoyaltiesAmount trigger.
-------
======================================================
======================================================
History
-------
VERSION AUTHOR        DATE       DETAIL              FEATURES/CSR/TTP
1.0 -   Mounika Suram 09/26/2018 INITIAL DEVELOPMENT CSR: FTTA License
***********************************************************************/
@isTest(SeeAllData=true)
public class FTTA_CalculateTotalRoyaltiesAmountTest {
    @isTest
    private static void whenAccountingLinesAdded(){
        id fttaRoyaltiesRTId = [select id, developerName from RecordType where developerName='FTTA_Royalties'].id;
        id fttaLicenseId = [select id, developerName from RecordType where developerName='FTTA_License'].id;
        // Create mock data
        // Insert epa license
        EPA_Agreement__c license = [select id,Total_Royalties__c from EPA_Agreement__c where recordTypeId=:fttaLicenseId Limit 1];
        //Create accounting lines and associate with license
        List<Accounting_Line__c> acList= new List<Accounting_Line__c>();
        Accounting_Line__c ac1 = new Accounting_Line__c();
        ac1.EPA_License__c=license.id;
        ac1.Payment_Amount__c=200.0;
        ac1.RecordTypeId=fttaRoyaltiesRTId;
        acList.add(ac1);
        Accounting_Line__c ac2 = new Accounting_Line__c();
        ac2.EPA_License__c=license.id;
        ac2.Payment_Amount__c=300.0;
        ac2.RecordTypeId=fttaRoyaltiesRTId;
        acList.add(ac2);
        Accounting_Line__c ac3 = new Accounting_Line__c();
        ac3.EPA_License__c=license.id;
        ac3.Payment_Amount__c=100.0;
        ac3.RecordTypeId=fttaRoyaltiesRTId;
        acList.add(ac3);
        Test.startTest();
        insert acList;
        ac1.Payment_Amount__c=100.0;
        Decimal totalRoyalties=[select id,Total_Royalties__c from EPA_Agreement__c where id=:license.id].Total_Royalties__c ;
        update ac1;
        system.assertEquals(totalRoyalties - 100.0, 
                            [select id,Total_Royalties__c from EPA_Agreement__c where id=:license.id].Total_Royalties__c);
        delete ac1;
        Test.stopTest();
        
    }
}