objects/Account.object
<CustomObject>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts_User2</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Award__c.object
<CustomObject>
    <fields>
        <fullName>Authorizing_Official__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Requesting official's supervisor. Responsible for the award's first level of approval.</description>
        <label>Authorizing Official</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Awards_Authorizing_Official</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Awardee_Direct_Supervisor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Awardee's Direct Supervisor. Used when a requesting official submits an award for someone outside of his/her organization.</description>
        <label>Awardee Direct Supervisor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Awards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Budget__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Budget that the award will be allocated toward.</description>
        <label>Budget</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Document__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Document - Award Budget</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Document__c</referenceTo>
        <relationshipLabel>Awards</relationshipLabel>
        <relationshipName>Budgeted_Awards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cash_Award_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Amount of award given to employee (monetary awards only).</description>
        <inlineHelpText>Cash Awards over $2,000 require AO approval. Collective awards over $5,000 for an awardee require two levels of approval.</inlineHelpText>
        <label>Cash Award Amount</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Extent_of_Contribution__c</fullName>
        <description>Extent of Contribution as defined on EPA's recommendation for incentive award form.</description>
        <label>Extent of Contribution</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Limited</fullName>
                </value>
                <value>
                    <fullName>Extended</fullName>
                </value>
                <value>
                    <fullName>Broad</fullName>
                </value>
                <value>
                    <fullName>General</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IOAA_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The designated person with IOAA who would need to approve the award request, if necessary.</description>
        <inlineHelpText>Approver for awards that are over $5,000 or take the awardee over a total of $5,000 for cash awards within the fiscal year.</inlineHelpText>
        <label>IOAA Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>IOAA_Awards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Outside_ORD__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if the award is going to an individual outside of the RPIO.</description>
        <inlineHelpText>Please check if the Awardee is outside of ORD. If you do not check this field for non-ORD employees, the award will be at risk of not being processed.</inlineHelpText>
        <label>Outside ORD</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Requesting_Official__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Requesting Official Contact Lookup</description>
        <inlineHelpText>Requesting Official. The individual submitting the award. Please note, the budget is assigned based on the RO's organization.</inlineHelpText>
        <label>Requesting Official</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Awards (Contact)</relationshipLabel>
        <relationshipName>Awards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Supervisor_Justification__c</fullName>
        <inlineHelpText>If using the group award functionality, this field will automatically assume the justification of the group award.</inlineHelpText>
        <label>Supervisor Justification</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Type_of_Benefit__c</fullName>
        <label>Type of Benefit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Tangible</fullName>
                </value>
                <value>
                    <fullName>Intangible</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Value_and_Application__c</fullName>
        <description>Combined Value of Benefit and Extent of Application field with corresponding amount ranges.</description>
        <inlineHelpText>Select the applicable Value of Benefit and Extent of Application combination. The Cash Award amount will be restricted based on the corresponding amount range.</inlineHelpText>
        <label>Value and Application</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>MODERATE VALUE &amp; LIMITED APPLICATION ($25-125)</fullName>
                </value>
                <value>
                    <fullName>MODERATE VALUE &amp; EXTENDED APPLICATION ($125-325)</fullName>
                </value>
                <value>
                    <fullName>MODERATE VALUE &amp; BROAD APPLICATION ($325-650)</fullName>
                </value>
                <value>
                    <fullName>MODERATE VALUE &amp; GENERAL APPLICATION ($650-1,300)</fullName>
                </value>
                <value>
                    <fullName>SUBSTANTIAL VALUE &amp; LIMITED APPLICATION ($125-325)</fullName>
                </value>
                <value>
                    <fullName>SUBSTANTIAL VALUE &amp; EXTENDED APPLICATION ($325-650)</fullName>
                </value>
                <value>
                    <fullName>SUBSTANTIAL VALUE &amp; BROAD APPLICATION ($650-1,300)</fullName>
                </value>
                <value>
                    <fullName>SUBSTANTIAL VALUE &amp; GENERAL APPLICATION ($1,300-3,100)</fullName>
                </value>
                <value>
                    <fullName>HIGH VALUE &amp; LIMITED APPLICATION ($325-650)</fullName>
                </value>
                <value>
                    <fullName>HIGH VALUE &amp; EXTENDED APPLICATION ($650-1,300)</fullName>
                </value>
                <value>
                    <fullName>HIGH VALUE &amp; BROAD APPLICATION ($1,300-3,150)</fullName>
                </value>
                <value>
                    <fullName>HIGH VALUE &amp; GENERAL APPLICATION ($3,150-5,000)</fullName>
                </value>
                <value>
                    <fullName>EXCEPTIONAL VALUE &amp; LIMITED APPLICATION ($650-1,300)</fullName>
                </value>
                <value>
                    <fullName>EXCEPTIONAL VALUE &amp; EXTENDED APPLICATION ($1,300-3,150)</fullName>
                </value>
                <value>
                    <fullName>EXCEPTIONAL VALUE &amp; BROAD APPLICATION ($3,150-6,000)</fullName>
                </value>
                <value>
                    <fullName>EXCEPTIONAL VALUE &amp; BROAD APPLICATION ($3,150-5,000)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Value_of_Benefit__c</fullName>
        <description>Value of Benefit as defined on EPA's recommendation for incentive award form.</description>
        <label>Value of Benefit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Moderate</fullName>
                </value>
                <value>
                    <fullName>Substantial</fullName>
                </value>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Exceptional</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Award given to employee (or eventually to other recipients).  First used in AART.</description>
    <label>Award</label>
    <nameField>
        <displayFormat>AWARD-{0000000}</displayFormat>
        <label>Award Internal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Awards</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Supervisor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Approving Supervisor.  The end user may edit his approving supervisor from the "Edit My Approvers" page.</description>
        <label>Approving Supervisor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contact_Supervisor</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Supervisor__c</fullName>
        <description>Deprecated.  Use the Contact's Approving Supervisor instead.</description>
        <inlineHelpText>Deprecated.  Use the Contact's Approving Supervisor instead.</inlineHelpText>
        <label>(Deprecated) Approving Supervisor</label>
        <relationshipName>Supervisor</relationshipName>
        <restrictedAdminField>false</restrictedAdminField>
        <type>Hierarchy</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/SubmitForApprovalController_Test.cls
/**
 * Methods for testing
 */
@IsTest
public with sharing class SubmitForApprovalController_Test {
    static Id AWARD_RECORDTYPE_ID = Schema.SObjectType.Award__c.getRecordTypeInfosByName().get('Standard Award').getRecordTypeId();
    static Id AWARD_CASH_RECORDTYPE_ID = Schema.SObjectType.Award__c.getRecordTypeInfosByName().get('Cash Award').getRecordTypeId();


    @TestSetup
    public static void setupTestData() {
        Account hrOrg = AwardTestUtilities.createOrganization('ORD-OARS');
        insert hrOrg;

        // User that owns the award.
        User testAwardOwner = AwardTestUtilities.createTestUser();
        insert testAwardOwner;

        User testAwardeeSupervisor = AwardTestUtilities.createTestUser();
        testAwardeeSupervisor.LastName = 'User Supervisor';
        testAwardeeSupervisor.Username = 'test.awardeesupervisor@epa.gov.test';
        insert testAwardeeSupervisor;

        User testInactiveAwardeeSupervisor = AwardTestUtilities.createTestUser();
        testInactiveAwardeeSupervisor.LastName = 'User Supervisor';
        testInactiveAwardeeSupervisor.Username = 'test.inactiveawardeesupervisor@epa.gov.test';
        testInactiveAwardeeSupervisor.IsActive = false;
        insert testInactiveAwardeeSupervisor;

        User testIoaaSupervisor = AwardTestUtilities.createTestUser();
        testIoaaSupervisor.LastName = 'IOAA Supervisor';
        testIoaaSupervisor.Username = 'test.ioaasupervisor@epa.gov.test';
        insert testIoaaSupervisor;

        Contact awardeeSupervisorContact = AwardTestUtilities.createEmployee(hrOrg);
        awardeeSupervisorContact.User__c = UserInfo.getUserId();
        insert awardeeSupervisorContact;

        Contact employee = AwardTestUtilities.createEmployee(hrOrg);
        employee.Supervisor__c = testAwardeeSupervisor.Id;
        insert employee;

        Document__c budget = AwardTestUtilities.createBudget(hrOrg, 20000);
        insert budget;

        Award__c award = AwardTestUtilities.createAward(employee);
        award.RecordTypeId = AWARD_CASH_RECORDTYPE_ID;
        award.Awardee_Direct_Supervisor__c = testAwardeeSupervisor.Id;
        award.OwnerId = testAwardOwner.Id;
        award.IOAA_Approver__c = testIoaaSupervisor.Id;
        award.Authorizing_Official__c = testAwardeeSupervisor.Id;
        award.Requesting_Official__c = awardeeSupervisorContact.Id;
        award.Extent_of_Contribution__c = AwardTestUtilities.EXTENT_OF_CONTRIBUTION;
        award.Value_of_Benefit__c = AwardTestUtilities.VALUE_OF_BENEFIT;
        award.Type_of_Benefit__c = AwardTestUtilities.TYPE_OF_BENEFIT;
        award.Supervisor_Justification__c = AwardTestUtilities.SUPERVISOR_JUSTIFICATION;
        award.Value_and_Application__c = 'MODERATE VALUE & GENERAL APPLICATION ($650-1,300)';
        award.Budget__c = budget.Id;
        award.Cash_Award_Amount__c = 1000;
        insert award;
    }

    @IsTest
    public static void testSubmit() {
        Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController([SELECT Id FROM Award__c]);
        SubmitForApprovalController controller = new SubmitForApprovalController(sc);
        controller.submitSingleAward();
        Test.stopTest();
    }

    @IsTest
    public static void testSubmittingOutsideOrdAward() {
        Award__c award = [SELECT Id FROM Award__c];
        award.Outside_ORD__c = true;
        update award;

        Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController([SELECT Id FROM Award__c]);
        SubmitForApprovalController controller = new SubmitForApprovalController(sc);
        controller.submitSingleAward();
        Test.stopTest();
    }

    @IsTest
    public static void testSubmittingAwardWithoutJustification() {
        Award__c award = [SELECT Id FROM Award__c];
        award.Supervisor_Justification__c = null;
        update award;

        Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController([SELECT Id FROM Award__c]);
        SubmitForApprovalController controller = new SubmitForApprovalController(sc);
        controller.submitSingleAward();
        Test.stopTest();

        System.assertNotEquals(null, ApexPages.getMessages(), 'Justification error should have been thrown and added to page.');
    }

//    @IsTest
//    public static void testSubmittingAwardWithoutBudget() {
//        Award__c award = [SELECT Id FROM Award__c];
//        award.Budget__c = null;
//        update award;
//
//        Test.startTest();
//        ApexPages.StandardController sc = new ApexPages.StandardController([SELECT Id FROM Award__c]);
//        SubmitForApprovalController controller = new SubmitForApprovalController(sc);
//        controller.submitSingleAward();
//        Test.stopTest();
//
//        System.assertNotEquals(null, ApexPages.getMessages(), 'Budget error should have been thrown and added to page.');
//    }

    @IsTest
    public static void testSubmittingAwardWithMissingApprover() {
        Award__c award = [SELECT Id FROM Award__c];
        award.Cash_Award_Amount__c = 1000;
        award.Authorizing_Official__c = null;
        update award;

        Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController([SELECT Id FROM Award__c]);
        SubmitForApprovalController controller = new SubmitForApprovalController(sc);
        controller.submitSingleAward();
        Test.stopTest();

        System.assertNotEquals(null, ApexPages.getMessages(), 'Should have received an error when submitting an award with no approver.');
    }
}