objects/Account.object
<CustomObject>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts_User2</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>LAN_ID__c</fullName>
        <externalId>true</externalId>
        <label>LAN ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Supervisor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Approving Supervisor.  The end user may edit his approving supervisor from the "Edit My Approvers" page.</description>
        <label>Approving Supervisor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contact_Supervisor</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact_Approvers__c.object
<CustomObject>
    <fields>
        <fullName>Use_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Use Contact</label>
        <type>Checkbox</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Checkbox --  if checked, code uses Contact fields for Approval process, if not checked, code uses User fields for Approval process.</description>
    <label>Contact Approvers</label>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>LAN_ID__c</fullName>
        <externalId>true</externalId>
        <label>LAN ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Session_Environment__c</fullName>
        <label>Session Environment</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Session_IP__c</fullName>
        <label>Session IP</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Session_Timestamp__c</fullName>
        <label>Session Timestamp</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Session_Token__c</fullName>
        <label>Session Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Supervisor__c</fullName>
        <description>Deprecated.  Use the Contact's Approving Supervisor instead.</description>
        <inlineHelpText>Deprecated.  Use the Contact's Approving Supervisor instead.</inlineHelpText>
        <label>(Deprecated) Approving Supervisor</label>
        <relationshipName>Supervisor</relationshipName>
        <restrictedAdminField>false</restrictedAdminField>
        <type>Hierarchy</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TestPurchaseCardRecordTypeForm.cls
//5-17-2018 - Test class edited to no longer user "the current user" as the main user for a record - Trellis Sherman GDIT

@isTest
public class TestPurchaseCardRecordTypeForm {
    @isTest static void TestCreationOfPurchaseCardRecordTypeForm(){
        
        //insert user
        User u = new User(
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator'].Id,
            FirstName = 'Test',
            LastName = 'User',
            Email = 'Test=User@test.com',
            Username = 'Test=User@tetest.com',
            CompanyName = 'TEST',
            Title = 'Test',
            Alias = 'Test',
            TimeZoneSidKey = 'America/Los_Angeles',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            Supervisor__c = Userinfo.getUserId(),
            Session_Token__c = '123ABC',
            Session_IP__c = '111-111-1111',
            Session_Environment__c = 'chrome',
            Session_Timestamp__c = datetime.now().addMinutes(-1),
            Lan_ID__c = 'thetest'
        );
        
        insert u;
        
        Account testAccount = new Account(Name='Test Account');
        testAccount.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('General Accounts').getRecordTypeId();
        insert testAccount;
        
        Contact testContact = new Contact();
        testContact.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('EPA Person').getRecordTypeId();
        testContact.Salutation = 'Prof.';
        testContact.LastName = 'Pudding';
        testContact.Email = 'Test=User@test.com';
        testContact.LAN_ID__c = 'thetest';
        testContact.AccountId = testAccount.Id;
        testContact.User__c = u.Id;
        insert testContact;
        
        insert new Contact_Approvers__c(name='Use Contact Fields', Use_Contact__c = false); 
        
        ID pcPermissionSetId = [select id, label from permissionset where label = 'Purchase Card Team' limit 1].id;
        
        system.runAs(u){
        insert new PermissionSetAssignment(AssigneeId=u.id,PermissionSetID=pcPermissionSetId);
        }
        
        Forms__c myPurchaseCard = new Forms__c();
        myPurchaseCard.Service_Comp_Date_MM_YYYY__c = '12/2003';
        myPurchaseCard.Approver_1__c = u.Id;
        myPurchaseCard.Approver_2__c = u.id;
        myPurchaseCard.Unauthenticated_Owner__c = u.id;
        myPurchaseCard.Account_Type__c = 'COOP';
        myPurchaseCard.Email_Address__c = 'Test=User@test.com';
        myPurchaseCard.Cardholder_AO_Name__c = testContact.Id;
        
        //Trellis 3.6.18
        RecordType RT = [select id, name from recordtype where name like 'Purchase Card:%' limit 1];
        myPurchaseCard.RecordTypeId = RT.Id;
        
        insert myPurchaseCard;
    }
    
    @isTest static void TestCreationOfPurchaseCardRecordTypeFormNoCardHolderChosen(){
        //insert user
        User u = new User(
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator'].Id,
            FirstName = 'Test',
            LastName = 'User2',
            Email = 'Test=User2@test.com',
            Username = 'Test=User2@tetest.com',
            CompanyName = 'TEST',
            Title = 'Test',
            Alias = 'Test',
            TimeZoneSidKey = 'America/Los_Angeles',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            Supervisor__c = Userinfo.getUserId(),
            Session_Token__c = '123ABC',
            Session_IP__c = '111-111-1111',
            Session_Environment__c = 'chrome',
            Session_Timestamp__c = datetime.now().addMinutes(-1),
            Lan_ID__c = 'thetest'
        );
        
        insert u;
        
        Account testAccount = new Account(Name='Test Account');
        testAccount.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('General Accounts').getRecordTypeId();
        insert testAccount;
        
        Contact testContact = new Contact();
        testContact.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('EPA Person').getRecordTypeId();
        testContact.Salutation = 'Prof.';
        testContact.LastName = 'Pudding';
        testContact.AccountId = testAccount.Id;
        testContact.User__c = u.Id;
        testContact.Email = 'Test=User2@test.com';
        testContact.LAN_ID__c = 'thetest';
        insert testContact;
       
        
        insert new Contact_Approvers__c(name='Use Contact Fields', Use_Contact__c = false); 
        
        ID pcPermissionSetId = [select id, label from permissionset where label = 'Purchase Card Team' limit 1].id;
        system.runAs(u){
            insert new PermissionSetAssignment(AssigneeId=u.id,PermissionSetID=pcPermissionSetId);
        }
        
        Forms__c myPurchaseCard = new Forms__c();
        myPurchaseCard.Service_Comp_Date_MM_YYYY__c = '12/2003';
        myPurchaseCard.Approver_1__c = userinfo.getUserId();
        myPurchaseCard.Approver_2__c = userinfo.getUserId();
        myPurchaseCard.Unauthenticated_Owner__c = u.id;
        myPurchaseCard.Account_Type__c = 'COOP';
        myPurchaseCard.Cardholder_AO_Name__c = null;
        myPurchaseCard.Email_Address__c = 'Test=User2@test.com';
        
        //3.6.18 Trellis Sherman
        RecordType RT = [select id, name from recordtype where name like 'Purchase Card:%' limit 1];
        myPurchaseCard.RecordTypeId = RT.Id;
        insert myPurchaseCard;
    }


}