objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>GAS Vendor Data</description>
        <inlineHelpText>Active Vendors are CHECKED by default.</inlineHelpText>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/eOrder_Item__c.object
<CustomObject>
    <fields>
        <fullName>Item_Price__c</fullName>
        <formula>Product__r.List_Price__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Item Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Order_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Request</label>
        <referenceTo>Order_Request__c</referenceTo>
        <relationshipLabel>Order Request Items</relationshipLabel>
        <relationshipName>eOrder_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Choose a Product by searching for Product details</description>
        <inlineHelpText>Choose a Product by searching for Product details</inlineHelpText>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>EPA_Product__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>EPA_Product__c.Vendor__r.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>EPA_Product__c</referenceTo>
        <relationshipLabel>eOrder Items</relationshipLabel>
        <relationshipName>eOrder_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <description>Number of cylinders requested</description>
        <inlineHelpText>Number of cylinders requested</inlineHelpText>
        <label>Quantity</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The current state of this item</description>
        <inlineHelpText>The current state of this item</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New Order</fullName>
                    <default>true</default>
                    <label>New Order</label>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Request Approved</fullName>
                </value>
                <value>
                    <fullName>Added to Order</fullName>
                </value>
                <value>
                    <fullName>Order Placed</fullName>
                </value>
                <value>
                    <fullName>Order Received</fullName>
                </value>
                <value>
                    <fullName>Order Delivered</fullName>
                </value>
                <value>
                    <fullName>Added to 1900-63</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Price__c</fullName>
        <formula>Product__r.List_Price__c * Quantity__c</formula>
        <label>Total Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>eOrder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>eOrder</label>
        <referenceTo>eOrders__c</referenceTo>
        <relationshipLabel>eOrder Items</relationshipLabel>
        <relationshipName>eOrder_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>Specific or detailed items within an order tracked in the eOrders document, initially for the GAS application.  (Similar to Line Items, into which this item might be merged someday.)</description>
    <label>eOrder Item</label>
    <nameField>
        <displayFormat>EPA-EOI-{000000000}</displayFormat>
        <label>eOrder Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>eOrder Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/eOrders__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <description>Comments to help describe the needs, uses, and etc. of the eOrder</description>
        <inlineHelpText>Comments to help describe the needs, uses, and etc. of the eOrder</inlineHelpText>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Order_Amount__c</fullName>
        <description>Total Cost of the sum of associated eOrder Items</description>
        <inlineHelpText>Total Cost of the sum of associated eOrder Items</inlineHelpText>
        <label>Order Amount</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Order_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Request</label>
        <referenceTo>Order_Request__c</referenceTo>
        <relationshipLabel>eOrders</relationshipLabel>
        <relationshipName>eOrders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The current state of the eOrder</description>
        <inlineHelpText>The current state of the eOrder</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <color>#0B6FCE</color>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Activated</fullName>
                    <color>#78C953</color>
                    <label>Activated</label>
                </value>
                <value>
                    <fullName>Return Order Placed</fullName>
                    <color>#CC33CC</color>
                    <label>Return Order Placed</label>
                </value>
                <value>
                    <fullName>Order Placed</fullName>
                    <color>#E27001</color>
                    <label>Order Placed</label>
                </value>
                <value>
                    <fullName>Partial Order Received</fullName>
                    <color>#F3D904</color>
                    <label>Partial Order Received</label>
                </value>
                <value>
                    <fullName>Full Order Received</fullName>
                    <color>#A845DC</color>
                    <label>Full Order Received</label>
                </value>
                <value>
                    <fullName>Order Closed</fullName>
                    <color>#A53711</color>
                    <label>Order Closed</label>
                </value>
                <value>
                    <fullName>Return Order Closed</fullName>
                    <color>#333333</color>
                    <label>Return Order Closed</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Quantity__c</fullName>
        <label>Total Quantity</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <description>Custom Object to Capture Orders placed for GAS Order Management Application.</description>
    <label>eOrder</label>
    <nameField>
        <displayFormat>EPA-EO-{000000000}</displayFormat>
        <label>eOrder ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>eOrders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Order_Request__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <description>Comments to help describe the needs, uses, and etc. of the Order Request</description>
        <inlineHelpText>Comments to help describe the needs, uses, and etc. of the Order Request</inlineHelpText>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <description>Current state of the Order Request</description>
        <inlineHelpText>Current state of the Order Request</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New Order</fullName>
                    <default>true</default>
                    <label>New Order</label>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Request Approved</fullName>
                </value>
                <value>
                    <fullName>Order Placed</fullName>
                </value>
                <value>
                    <fullName>Partial Order Received</fullName>
                </value>
                <value>
                    <fullName>Full Order Received</fullName>
                </value>
                <value>
                    <fullName>Order Fulfilled</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Quantity__c</fullName>
        <label>Total Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <description>Requests for orders to be placed.  Initially used in the GAS application, then in PCORS, and available for other uses.  Used not only in native licensed access ("Type 3 interface" in BAP parlance) but also in "Type 1" interface (unlicensed guest access).</description>
    <label>Order Request</label>
    <nameField>
        <displayFormat>EPA-OR-{000000000}</displayFormat>
        <label>Order Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ORDGAS_CylinderTotalsTest.cls
/*
*    Author : mondal.javed@epa.gov
*    CreatedDate : 1-May-2018
*    Class Name : ORDGAS_CylinderTotalsTest
*    Test Class for ORDGAS_CylinderTotals
**/

@isTest
public class ORDGAS_CylinderTotalsTest{
    private static Id recordTypeId = Schema.SObjectType.Line_Item__c.getRecordTypeInfosByName().get('GAS Cylinders').getRecordTypeId();
    private static Id recordTypeIdVendor = Schema.SObjectType.Account.getRecordTypeInfosByName().get('GAS Vendors').getRecordTypeId();
    private static Id recordTypeIdeOrderAdmin = Schema.SObjectType.eOrders__c.getRecordTypeInfosByName().get('GAS eOrder Admin').getRecordTypeId();
    private static Id recordTypeIdOrderRequest = Schema.SObjectType.Order_Request__C.getRecordTypeInfosByName().get('GAS Order Request').getRecordTypeId();
    private static Id recordTypeIdeOrderItem = Schema.SObjectType.eOrder_Item__c.getRecordTypeInfosByName().get('GAS eOrder Item').getRecordTypeId();
    static testMethod void PositiveTests(){
        User u =[select id from user where UserName='GAS1@test.org'];
        system.runas(u){
            account acc= new account();
            acc.name = 'Conde Nast';
            acc.Active__c = TRUE;
            acc.RecordTypeId = recordTypeIdVendor;
            insert acc;
            Order_Request__c request =new Order_Request__c();
            request.Stage__c = 'New Order';
            request.RecordTypeId=recordTypeIdOrderRequest;
            insert request;
            eOrders__c eorder = new eOrders__c();
            eorder.Description__c = 'test';
            eorder.Order_Amount__c= 50.0;
            eorder.Status__c  = 'Draft';
            eorder.Total_Quantity__c = 1.0;
            eorder.RecordTypeId = recordTypeIdeOrderAdmin;
            insert eorder;
            eOrder_Item__c item = new eOrder_Item__c ();
            //item.Product__c = product.Id;
            item.Quantity__c = 1.0;
            item.Status__c = 'Added to Order';
            item.eOrder__c  = eorder.Id;
            item.Order_Request__c = request.id;
            item.RecordTypeId = recordTypeIdeOrderItem;
            //item.Total_Price__c = 1000.0;
            Insert item;
            Line_Item__c lineItem = new Line_Item__c();
            //lineItem.Product__c = eorderItem.Product__c;
            lineItem.Status__c='Open';
            //lineItem.Item_Price__c = eorderItem.Item_Price__c;
            //lineItem.Order_Request__c = eorderItem.Order_Request__c;
            lineItem.eOrder_Item__c = item.id;
            lineItem.eOrder__c = eOrder.id;
            lineItem.RecordTypeId = recordTypeId;
            insert lineItem;
            lineItem.Serial_Number__c  = '2121214';
            lineItem.Serial_Number_Confirmation__c  = '1214';
            test.StartTest();
            update lineItem;
            test.StopTest();
        }
        
    }
    static testMethod void requestPopulatedTests(){
        User u =[select id from user where UserName='GAS1@test.org'];
        system.runas(u){
            account acc= new account();
            acc.name = 'Conde Nast';
            acc.Active__c = TRUE;
            acc.RecordTypeId = recordTypeIdVendor;
            insert acc;
            Order_Request__c request =new Order_Request__c();
            request.Stage__c = 'New Order';
            request.RecordTypeId=recordTypeIdOrderRequest;
            insert request;
            eOrders__c eorder = new eOrders__c();
            eorder.Description__c = 'test';
            eorder.Order_Amount__c= 50.0;
            eorder.Status__c  = 'Draft';
            eorder.Total_Quantity__c = 2.0;
            eorder.RecordTypeId = recordTypeIdeOrderAdmin;
            insert eorder;
            eOrder_Item__c item = new eOrder_Item__c ();
            item.Quantity__c = 2.0;
            item.Status__c = 'Added to Order';
            item.eOrder__c  = eorder.Id;
            item.Order_Request__c = request.id;
            Insert item;
            Line_Item__c lineItem = new Line_Item__c();
            lineItem.Status__c='Open';
            lineItem.eOrder_Item__c = item.id;
            lineItem.eOrder__c = eOrder.id;
            lineItem.RecordTypeId = recordTypeId;
            insert lineItem;
            lineItem.Serial_Number__c  = '2121214';
            lineItem.Serial_Number_Confirmation__c  = '1214';
            
            Line_Item__c lineItem2 = new Line_Item__c();
            lineItem2.Status__c='Open';
            lineItem2.eOrder_Item__c = item.id;
            lineItem2.eOrder__c = eOrder.id;
            lineItem2.RecordTypeId = recordTypeId;
            insert lineItem2;
            
            test.StartTest();
            update lineItem;
            test.StopTest();
        }
        
    }
    @TestSetup
    private static void setup()
    {
        // Create a sample form statement object and then submit it for approval.
            
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
		
        // Create User Record
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com',
        EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
        LocaleSidKey='en_US', ProfileId = p.Id,
        TimeZoneSidKey='America/Los_Angeles',
        UserName='GAS1@test.org');
        insert u;

        PermissionSet ps = [SELECT ID From PermissionSet WHERE Name = 'GAS_Application_Admin'];
        insert new PermissionSetAssignment(AssigneeId = u.id, PermissionSetId = ps.Id ); 
    }
}