objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>Application_Name__c</fullName>
        <label>Application Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AutoReply_Text__c</fullName>
        <description>Text to include in the BAP Auto-reply email</description>
        <inlineHelpText>Text to include in the BAP Auto-reply email</inlineHelpText>
        <label>AutoReply Text</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Included_in_Support__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this application included in the BAP Auto-reply email</description>
        <inlineHelpText>Is this application included in the BAP Auto-reply email</inlineHelpText>
        <label>Included in Support</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Support_Email__c</fullName>
        <description>Field to allow linking to an email or url, AIM, 04.11.19</description>
        <label>Support Link</label>
        <length>256</length>
        <type>LongTextArea</type>
    </fields>
    <description>Software applications and instances of applying for something.  First used in the Application Inventory Management system within the BAP, but also available for other purposes.  (As with all objects, various kinds of data can be stored, differentiated by record type.)</description>
    <label>Application</label>
    <nameField>
        <displayFormat>EPA-APP-{000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/BAPAutoReply_Test.cls
@isTest
public class BAPAutoReply_Test {
    public static Id aimRt = Schema.SObjectType.Application__c.getRecordTypeInfosByName().get('Software Application').getRecordTypeId();
    
    public static testMethod void someMethod_Test()
    {
        Application__c app = New Application__c();
        app.Application_Name__c = 'Test';
        app.AutoReply_Text__c = 'Test';
        app.Support_email__c = 'test@test.com';
        app.Included_in_Support__c	= true;
        //app.Send_as_Record__c = false;
        //app.Retention__c = SObjectType.application__c.Fields.Retention__c.PicklistValues[0].getValue(); 
        //app.Sensitivity__c = SObjectType.application__c.Fields.Sensitivity__c.PicklistValues[0].getValue(); 
        //app.Date_Event__c = SObjectType.application__c.Fields.Date_Event__c.PicklistValues[0].getValue();
        app.RecordTypeId=aimRt;
        insert app;
        
        //System.assertEquals(1,e.getAccount.size());
        BAPAutoReply c = new BAPAutoReply();
        System.assertEquals(1,c.getAccount().size());
        
    }
}