objects/Award__c.object
<CustomObject>
    <fields>
        <fullName>Authorizing_Official_Name__c</fullName>
        <formula>Authorizing_Official__r.FirstName + " " + Authorizing_Official__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Authorizing Official Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Authorizing_Official_Title__c</fullName>
        <description>Authorizing official's title from the record Owner's related Contact record.</description>
        <formula>Owner_Contact__r.Supervisor__r.Title</formula>
        <label>Authorizing Official Title</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Awardee_Direct_Supervisor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Awardee's Direct Supervisor. Used when a requesting official submits an award for someone outside of his/her organization.</description>
        <label>Awardee Direct Supervisor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Awards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cash_Award_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Amount of award given to employee (monetary awards only).</description>
        <inlineHelpText>Cash Awards over $2,000 require AO approval. Collective awards over $5,000 for an awardee require two levels of approval.</inlineHelpText>
        <label>Cash Award Amount</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Cincinnati_Office_Justification__c</fullName>
        <description>Required for Cincinnati Union Employees. Justification specific to the Cinc. Union form.</description>
        <inlineHelpText>Required for Awardees in the Cinc. Union. Press and hold the Ctrl key to select multiple options.</inlineHelpText>
        <label>Cincinnati Office Justification</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Substantially surpasses performance goals</fullName>
                </value>
                <value>
                    <fullName>Improved performance over the prior period</fullName>
                </value>
                <value>
                    <fullName>Reduced costs, expert performance, increased efficiencies</fullName>
                </value>
                <value>
                    <fullName>Makes significant contributions to the EPA</fullName>
                </value>
                <value>
                    <fullName>Exemplifies core values of the EPA</fullName>
                </value>
                <value>
                    <fullName>Achieves Specific Scientific Advancements</fullName>
                </value>
                <value>
                    <fullName>Prepares outstanding publications</fullName>
                </value>
                <value>
                    <fullName>Improves service to the public</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Emp_ID__c</fullName>
        <description>Awardee's Employee ID</description>
        <formula>Emp_Name__r.Employee_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Emp ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Emp_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Awardee's Name</description>
        <label>Emp Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Awards (Emp Name)</relationshipLabel>
        <relationshipName>Employee</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Extent_of_Contribution__c</fullName>
        <description>Extent of Contribution as defined on EPA's recommendation for incentive award form.</description>
        <label>Extent of Contribution</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Limited</fullName>
                </value>
                <value>
                    <fullName>Extended</fullName>
                </value>
                <value>
                    <fullName>Broad</fullName>
                </value>
                <value>
                    <fullName>General</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Grade__c</fullName>
        <description>Grade of the Awardee.</description>
        <formula>Emp_Name__r.Grade__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Grade</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_Award_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Group Award object to determine which awards are part of a group award. The individual awards, though, are processed as normal.</description>
        <inlineHelpText>Create Group Award Names or leverage existing names in order to tag and organize group awards.</inlineHelpText>
        <label>Group Award Name</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Group_Award__c.CreatedBy.Id</field>
                <operation>equals</operation>
                <valueField>$User.Id</valueField>
            </filterItems>
            <infoMessage>Please choose a group award that you have created.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Group_Award__c</referenceTo>
        <relationshipLabel>Awards</relationshipLabel>
        <relationshipName>Awards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IOAA_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The designated person with IOAA who would need to approve the award request, if necessary.</description>
        <inlineHelpText>Approver for awards that are over $5,000 or take the awardee over a total of $5,000 for cash awards within the fiscal year.</inlineHelpText>
        <label>IOAA Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>IOAA_Awards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OTS_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>The Cash Award Amount will automatically be calculated based on the OTS Amount entered.</inlineHelpText>
        <label>OTS Amount</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Outside_ORD__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if the award is going to an individual outside of the RPIO.</description>
        <inlineHelpText>Please check if the Awardee is outside of ORD. If you do not check this field for non-ORD employees, the award will be at risk of not being processed.</inlineHelpText>
        <label>Outside ORD</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Outside_Org__c</fullName>
        <description>Evaluates to true if the requesting Official is not the Awardee's Direct Supervisor</description>
        <formula>Requesting_Official__r.Employee_Number__c &lt;&gt;  Awardee_Direct_Supervisor__r.EmployeeNumber</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Checked if the Requesting Official is not the Awardee's Direct Supervisor</inlineHelpText>
        <label>Outside Org</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Position_Title__c</fullName>
        <formula>Emp_Name__r.Position_Title__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Position Title</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Requesting_Official_Supervisor_Title__c</fullName>
        <formula>Requesting_Official__r.Title</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Requesting Official Supervisor Title</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Requesting_Official_Supervisor__c</fullName>
        <formula>Requesting_Official__r.FirstName  + " " +  Requesting_Official__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Requesting Official Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Requires_IOAA_Approval__c</fullName>
        <defaultValue>false</defaultValue>
        <description>True if the saved award requires IOAA approval. The box should be read-only in the permission set and layout and should only be updated by Apex logic.</description>
        <label>Requires IOAA Approval</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Requires_Supervisor_Approval__c</fullName>
        <defaultValue>false</defaultValue>
        <description>True if the saved award requires Supervisor approval. The box should be read-only in the permission set and page layout and should be updated solely by Apex logic.</description>
        <label>Requires Supervisor Approval</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Submitted_Date__c</fullName>
        <label>Submitted Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Supervisor_Approval_Date__c</fullName>
        <description>Date Supervisor approves the record. If the record is automatically approved (doesn't require Supervisor approval), approval date will equal submitted date.</description>
        <label>AO Approval Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Supervisor_Justification__c</fullName>
        <inlineHelpText>If using the group award functionality, this field will automatically assume the justification of the group award.</inlineHelpText>
        <label>Supervisor Justification</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Time_Off_Amount__c</fullName>
        <description>Amount of time-off hours given to employee.</description>
        <inlineHelpText>Time Off awards greater than 10 hours require AO approval.</inlineHelpText>
        <label>Time Off Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type_of_Benefit__c</fullName>
        <label>Type of Benefit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Tangible</fullName>
                </value>
                <value>
                    <fullName>Intangible</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Value_and_Application__c</fullName>
        <description>Combined Value of Benefit and Extent of Application field with corresponding amount ranges.</description>
        <inlineHelpText>Select the applicable Value of Benefit and Extent of Application combination. The Cash Award amount will be restricted based on the corresponding amount range.</inlineHelpText>
        <label>Value and Application</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>MODERATE VALUE &amp; LIMITED APPLICATION ($25-125)</fullName>
                </value>
                <value>
                    <fullName>MODERATE VALUE &amp; EXTENDED APPLICATION ($125-325)</fullName>
                </value>
                <value>
                    <fullName>MODERATE VALUE &amp; BROAD APPLICATION ($325-650)</fullName>
                </value>
                <value>
                    <fullName>MODERATE VALUE &amp; GENERAL APPLICATION ($650-1,300)</fullName>
                </value>
                <value>
                    <fullName>SUBSTANTIAL VALUE &amp; LIMITED APPLICATION ($125-325)</fullName>
                </value>
                <value>
                    <fullName>SUBSTANTIAL VALUE &amp; EXTENDED APPLICATION ($325-650)</fullName>
                </value>
                <value>
                    <fullName>SUBSTANTIAL VALUE &amp; BROAD APPLICATION ($650-1,300)</fullName>
                </value>
                <value>
                    <fullName>SUBSTANTIAL VALUE &amp; GENERAL APPLICATION ($1,300-3,100)</fullName>
                </value>
                <value>
                    <fullName>HIGH VALUE &amp; LIMITED APPLICATION ($325-650)</fullName>
                </value>
                <value>
                    <fullName>HIGH VALUE &amp; EXTENDED APPLICATION ($650-1,300)</fullName>
                </value>
                <value>
                    <fullName>HIGH VALUE &amp; BROAD APPLICATION ($1,300-3,150)</fullName>
                </value>
                <value>
                    <fullName>HIGH VALUE &amp; GENERAL APPLICATION ($3,150-5,000)</fullName>
                </value>
                <value>
                    <fullName>EXCEPTIONAL VALUE &amp; LIMITED APPLICATION ($650-1,300)</fullName>
                </value>
                <value>
                    <fullName>EXCEPTIONAL VALUE &amp; EXTENDED APPLICATION ($1,300-3,150)</fullName>
                </value>
                <value>
                    <fullName>EXCEPTIONAL VALUE &amp; BROAD APPLICATION ($3,150-6,000)</fullName>
                </value>
                <value>
                    <fullName>EXCEPTIONAL VALUE &amp; BROAD APPLICATION ($3,150-5,000)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Work_Code__c</fullName>
        <formula>IF( NOT( ISBLANK( RO_HR_Org2__c ) ), RO_HR_Org2__r.Code__c, NULL )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Work Code</label>
        <type>Text</type>
    </fields>
    <description>Award given to employee (or eventually to other recipients).  First used in AART.</description>
    <label>Award</label>
    <nameField>
        <displayFormat>AWARD-{0000000}</displayFormat>
        <label>Award Internal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Awards</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Grade__c</fullName>
        <label>Grade</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Position_Title__c</fullName>
        <label>Position Title</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Grade__c</fullName>
        <label>Grade</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Position_Title__c</fullName>
        <label>Position Title</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/PDFFormCreatorController.cls
public with sharing class PDFFormCreatorController {
    private final Id awardId;
    public String awardInternalId {get; set;}
    public String employeeName {get; set;}
    public String employeeId {get; set;}
    public String employeePosition {get; set;}
    public String employeeGrade {get; set;}
    public String employeeOrganization {get; set;}
    public String employeePhoneNumber {get; set;}
    public String awardWorkCode {get; set;}
    public Decimal cashAwardAmount {get; set;}
    public Decimal OTSAwardAmount {get; set;}
    public Decimal awardAmount {get; set;}
    public Decimal timeOffAmount {get; set;}
    public Boolean tangibleBenefit {get; set;}
    public Boolean intangibleBenefit {get; set;}
    public Boolean onTheSpotAward {get; set;}
    public Boolean groupCashAward {get; set;}
    public Boolean individualCashAward {get; set;}
    public Boolean groupTimeOff {get; set;}
    public Boolean timeOffAward {get; set;}
    public Boolean moderate {get; set;}
    public Boolean substantial {get; set;}
    public Boolean high {get; set;}
    public Boolean exceptional {get; set;}
    public Boolean limited {get; set;}
    public Boolean extended {get; set;}
    public Boolean broad {get; set;}
    public Boolean general {get; set;}
    public String justification {get; set;}
    public String requestingOfficialName {get; set;}
    public String requestingOfficialTitle {get; set;}
    public String authorizingOfficialName {get; set;}
    public String authorizingOfficialTitle {get; set;}
    public Datetime currentDatetime {get; set;}
    public String currentDate {get; set;}
    public String submittedDate {get; set;}
    public String employeeAchievement {get; set;}
    public String materialImprovement {get; set;}
    public String unitCostReduction {get; set;}
    public String significantContribution {get; set;}
    public String exhibitsBehavior {get; set;}
    public String scientificAdvancement {get; set;}
    public String noteworthyPublication {get; set;}
    public String improvesService {get; set;}
    public Boolean requiresSupervisorApproval {get; set;}
    public Boolean requiresIOAAApproval {get; set;}
    public Boolean outsideOrg {get; set;}
    public Boolean outsideOrd {get; set;}
    public String awardeeDirSuperName {get; set;}
    public String awardeeDirSuperTitle {get; set;}
    public String aoApprovalDate {get; set;}
    public String ioaaApproverName {get; set;}
    public String ioaaApproverTitle {get; set;}
    public List<ProcessInstanceStep> approvalHistory {get; set;}

    public PDFFormCreatorController(ApexPages.StandardController stdController) {
        this.awardId = stdController.getId();
        Award__c currentAward = getCurrentAward(this.awardId);
        awardInternalId = currentAward.Name;

        // If the Cincinnati Justification is not blank, parse it
        if(currentAward.Cincinnati_Office_Justification__c != null) {
            parseCincinnatiJustification(currentAward);
        }

        // Get the approval history related to this award
        approvalHistory = getApprovalHistory(this.awardId);

        // Set Employee Information
        this.employeeName = currentAward.Emp_Name__r.Name;
        this.employeeId = currentAward.Emp_ID__c;
        this.employeePosition = currentAward.Emp_Name__r.Position_Title__c;
        this.employeeGrade = currentAward.Emp_Name__r.Grade__c;
        this.employeeOrganization = currentAward.Emp_Name__r.Account.Name;
        this.employeePhoneNumber = currentAward.Emp_Name__r.Phone;
        this.awardWorkCode = currentAward.Work_Code__c;
        this.cashAwardAmount = currentAward.Cash_Award_Amount__c;
        this.timeOffAmount = currentAward.Time_Off_Amount__c;
        this.OTSAwardAmount = currentAward.OTS_Amount__c;
        this.justification = currentAward.Supervisor_Justification__c;
        this.requestingOfficialName = currentAward.Requesting_Official_Supervisor__c;
        this.requestingOfficialTitle = currentAward.Requesting_Official_Supervisor_Title__c;
        this.authorizingOfficialName = currentAward.Authorizing_Official_Name__c;
        this.authorizingOfficialTitle = currentAward.Authorizing_Official_Title__c;
        this.currentDatetime = System.now();
        this.currentDate = Date.today().format();
        this.submittedDate = currentAward.Submitted_Date__c != null ? currentAward.Submitted_Date__c.format() : null;
        this.aoApprovalDate = currentAward.Supervisor_Approval_Date__c != null ? currentAward.Supervisor_Approval_Date__c.format() : null;
        this.requiresSupervisorApproval = currentAward.Requires_Supervisor_Approval__c;
        this.requiresIOAAApproval = currentAward.Requires_IOAA_Approval__c;
        this.outsideOrg = currentAward.Outside_Org__c;
        this.outsideOrd = currentAward.Outside_ORD__c;
        this.awardeeDirSuperName = currentAward.Awardee_Direct_Supervisor__r.Name;
        this.awardeeDirSuperTitle = currentAward.Awardee_Direct_Supervisor__r.Title;
        this.ioaaApproverName = currentAward.IOAA_Approver__r.Name;
        this.ioaaApproverTitle = currentAward.IOAA_Approver__r.Title;
        
        // Set class variables based on picklist values
        this.tangibleBenefit = currentAward.Type_of_Benefit__c == 'Tangible' ? true : false;
        this.intangibleBenefit = currentAward.Type_of_Benefit__c == 'Intangible' ?  true : false;
        this.moderate = currentAward.Value_and_Application__c != null && currentAward.Value_and_Application__c.contains('MODERATE VALUE') ? true : false;
        this.substantial = currentAward.Value_and_Application__c != null && currentAward.Value_and_Application__c.contains('SUBSTANTIAL VALUE') ? true : false;
        this.high = currentAward.Value_and_Application__c != null && currentAward.Value_and_Application__c.contains('HIGH VALUE') ? true : false;
        this.exceptional = currentAward.Value_and_Application__c != null && currentAward.Value_and_Application__c.contains('EXCEPTIONAL VALUE') ? true : false;
        this.limited = currentAward.Value_and_Application__c != null && currentAward.Value_and_Application__c.contains('LIMITED APPLICATION') ? true : false;
        this.extended = currentAward.Value_and_Application__c != null && currentAward.Value_and_Application__c.contains('EXTENDED APPLICATION') ? true : false;
        this.broad = currentAward.Value_and_Application__c != null && currentAward.Value_and_Application__c.contains('BROAD APPLICATION') ? true : false;
        this.general = currentAward.Value_and_Application__c != null && currentAward.Value_and_Application__c.contains('GENERAL APPLICATION') ? true : false;

        // Set class variables based on whether or not the fields either have values or those values are greater than 0
        this.individualCashAward = currentAward.Cash_Award_Amount__c != null && currentAward.Cash_Award_Amount__c > 0  && !(currentAward.OTS_Amount__c > 0) ? true : false;
        this.groupCashAward = currentAward.Group_Award_Name__c != null ? true : false;
        this.timeOffAward = currentAward.Time_Off_Amount__c != null && currentAward.Time_Off_Amount__c > 0 ? true : false;
        this.onTheSpotAward = currentAward.OTS_Amount__c != null && currentAward.OTS_Amount__c > 0 ? true : false;
        this.awardAmount = this.onTheSpotAward ? currentAward.OTS_Amount__c : currentAward.Cash_Award_Amount__c;
    }

    public PageReference createOnePageForm() {
        Award__c award = getCurrentAward(this.awardId);

        Attachment attachment = new Attachment();
        PageReference pdf = Page.AwardSinglePageForm;
        pdf.getParameters().put('Id', this.awardId);
        Blob pdfBlob = Test.isRunningTest() ? Blob.valueOf('PDF Content') : pdf.getContent();
        attachment.Body = pdfBlob;
        attachment.Name = award.Emp_Name__r.Name + '_' + String.valueOf(Date.today()) + '_1page.pdf';
        attachment.ParentId = award.Id;
        insert attachment;

        return new PageReference('/' + award.Id);
    }

    public PageReference createDoublePageForm() {
        Award__c award = getCurrentAward(this.awardId);

        Attachment attachment = new Attachment();
        PageReference pdf = Page.AwardDoublePageForm;
        pdf.getParameters().put('Id', this.awardId);
        Blob pdfBlob = Test.isRunningTest() ? Blob.valueOf('PDF Content') : pdf.getContent();
        attachment.Body = pdfBlob;
        attachment.Name = award.Emp_Name__r.Name + '_' + String.valueOf(Date.today()) + '_2page.pdf';
        attachment.ParentId = award.Id;
        insert attachment;

        return new PageReference('/' + award.Id);
    }

    public PageReference createCincinnatiForm() {
        Award__c award = getCurrentAward(this.awardId);

        Attachment attachment = new Attachment();
        PageReference pdf = Page.CincinnatiJustificationForm;
        pdf.getParameters().put('Id', this.awardId);
        attachment.Body = Test.isRunningTest() ? Blob.valueOf('PDF Content') : pdf.getContentAsPDF();
        attachment.Name = award.Emp_Name__r.Name + '_' + String.valueOf(Date.today()) + '_CincinattiJustification.pdf';
        attachment.ParentId = award.Id;
        insert attachment;

        return new PageReference('/' + award.Id);
    }

    private Award__c getCurrentAward(Id awardId) {
        Award__c award = [
                SELECT Id, Name, Emp_Name__r.Name, Emp_ID__c, Emp_Name__r.Position_Title__c, Emp_Name__r.Grade__c, Emp_Name__r.Account.Name,
                        Extent_of_Contribution__c, Cash_Award_Amount__c, Group_Award_Name__c, Work_Code__c,
                        Supervisor_Justification__c, Type_of_Benefit__c, OTS_Amount__c, Time_Off_Amount__c,
                        Requesting_Official_Supervisor__c, Requesting_Official_Supervisor_Title__c, Authorizing_Official_Name__c,
                        Authorizing_Official_Title__c, Submitted_Date__c, Supervisor_Approval_Date__c, Emp_Name__r.Phone, Cincinnati_Office_Justification__c,
                        Requires_Supervisor_Approval__c, Requires_IOAA_Approval__c, Outside_Org__c, Awardee_Direct_Supervisor__r.Name,
                        Awardee_Direct_Supervisor__r.Title, Outside_ORD__c, IOAA_Approver__r.Name, IOAA_Approver__r.Title, Value_and_Application__c
                FROM Award__c
                WHERE Id = :awardId
                LIMIT 1
        ];

        return award;
    }

    private void parseCincinnatiJustification(Award__c award) {
        String cinciJustification = award.Cincinnati_Office_Justification__c;
        List<String> justificationReasons = new List<String>();

        if (cinciJustification != null) {
            justificationReasons = cinciJustification.split(';');
        }

        if (justificationReasons.size() > 0) {
            for (String reason : justificationReasons) {
                if (reason.contains('Substantially surpasses performance goals')) {
                    this.employeeAchievement = 'X';
                }

                if (reason.contains('Improved performance over the prior period')) {
                    this.materialImprovement = 'X';
                }

                if (reason.contains('Reduced costs, expert performance, increased efficiencies')) {
                    this.unitCostReduction = 'X';
                }

                if (reason.contains('Makes significant contributions to the EPA')) {
                    this.significantContribution = 'X';
                }

                if (reason.contains('Exemplifies core values of the EPA')) {
                    this.exhibitsBehavior = 'X';
                }

                if (reason.contains('Achieves Specific Scientific Advancements')) {
                    this.scientificAdvancement = 'X';
                }

                if (reason.contains('Prepares outstanding publications')) {
                    this.noteworthyPublication = 'X';
                }

                if (reason.contains('Improves service to the public')) {
                    this.improvesService = 'X';
                }
            }
        }
    }

    private List<ProcessInstanceStep> getApprovalHistory(Id awardId) {
        ProcessInstance[] processInstance = [
                SELECT Id
                FROM ProcessInstance
                WHERE TargetObjectId = :awardId
                AND Status = 'Approved'
                LIMIT 1
        ];

        if (processInstance.isEmpty()) {
            return null;
        }

        List<ProcessInstanceStep> approvalHistory = [
                SELECT Id, OriginalActor.Name, Actor.Name, CreatedDate, StepStatus
                FROM ProcessInstanceStep
                WHERE ProcessInstanceId = :processInstance[0].Id
        ];

        return approvalHistory;
    }
}