objects/Award__c.object
<CustomObject>
    <fields>
        <fullName>Branch__c</fullName>
        <description>Calculated field based on the 2nd component of the Requesting Official's Department.</description>
        <label>Branch</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Budget__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Budget that the award will be allocated toward.</description>
        <label>Budget</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Document__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Document - Award Budget</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Document__c</referenceTo>
        <relationshipLabel>Awards</relationshipLabel>
        <relationshipName>Budgeted_Awards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cash_Award_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Amount of award given to employee (monetary awards only).</description>
        <inlineHelpText>Cash Awards over $2,000 require AO approval. Collective awards over $5,000 for an awardee require two levels of approval.</inlineHelpText>
        <label>Cash Award Amount</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <description>The third component of the Requesting Officials department.</description>
        <label>Division</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Emp_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Awardee's Name</description>
        <label>Emp Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Awards (Emp Name)</relationshipLabel>
        <relationshipName>Employee</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Extent_of_Contribution__c</fullName>
        <description>Extent of Contribution as defined on EPA's recommendation for incentive award form.</description>
        <label>Extent of Contribution</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Limited</fullName>
                </value>
                <value>
                    <fullName>Extended</fullName>
                </value>
                <value>
                    <fullName>Broad</fullName>
                </value>
                <value>
                    <fullName>General</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Group_Award_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Group Award Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Group_Award_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Group Award object to determine which awards are part of a group award. The individual awards, though, are processed as normal.</description>
        <inlineHelpText>Create Group Award Names or leverage existing names in order to tag and organize group awards.</inlineHelpText>
        <label>Group Award Name</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Group_Award__c.CreatedBy.Id</field>
                <operation>equals</operation>
                <valueField>$User.Id</valueField>
            </filterItems>
            <infoMessage>Please choose a group award that you have created.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Group_Award__c</referenceTo>
        <relationshipLabel>Awards</relationshipLabel>
        <relationshipName>Awards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LCO__c</fullName>
        <label>LCO</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OTS_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>The Cash Award Amount will automatically be calculated based on the OTS Amount entered.</inlineHelpText>
        <label>OTS Amount</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Outside_LCO__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if an award is for an individual outside that is outside of the Requesting Official's organization.</description>
        <inlineHelpText>Please check if the award is going towards an individual outside of your organization.</inlineHelpText>
        <label>Outside LCO</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Outside_ORD__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if the award is going to an individual outside of the RPIO.</description>
        <inlineHelpText>Please check if the Awardee is outside of ORD. If you do not check this field for non-ORD employees, the award will be at risk of not being processed.</inlineHelpText>
        <label>Outside ORD</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Pay_Period__c</fullName>
        <description>The pay period in which the employee was paid.</description>
        <inlineHelpText>NOT ENTERED BY REQUESTING OFFICIAL! Please use for Cash and QSIs.</inlineHelpText>
        <label>Calendar Pay Period (Cash)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>201722</fullName>
                </value>
                <value>
                    <fullName>201723</fullName>
                </value>
                <value>
                    <fullName>201724</fullName>
                </value>
                <value>
                    <fullName>201725</fullName>
                </value>
                <value>
                    <fullName>201726</fullName>
                </value>
                <value>
                    <fullName>201801</fullName>
                </value>
                <value>
                    <fullName>201802</fullName>
                </value>
                <value>
                    <fullName>201803</fullName>
                </value>
                <value>
                    <fullName>201804</fullName>
                </value>
                <value>
                    <fullName>201805</fullName>
                </value>
                <value>
                    <fullName>201806</fullName>
                </value>
                <value>
                    <fullName>201807</fullName>
                </value>
                <value>
                    <fullName>201808</fullName>
                </value>
                <value>
                    <fullName>201809</fullName>
                </value>
                <value>
                    <fullName>201810</fullName>
                </value>
                <value>
                    <fullName>201811</fullName>
                </value>
                <value>
                    <fullName>201812</fullName>
                </value>
                <value>
                    <fullName>201813</fullName>
                </value>
                <value>
                    <fullName>201814</fullName>
                </value>
                <value>
                    <fullName>201815</fullName>
                </value>
                <value>
                    <fullName>201816</fullName>
                </value>
                <value>
                    <fullName>201817</fullName>
                </value>
                <value>
                    <fullName>201818</fullName>
                </value>
                <value>
                    <fullName>201819</fullName>
                </value>
                <value>
                    <fullName>201820</fullName>
                </value>
                <value>
                    <fullName>201821</fullName>
                </value>
                <value>
                    <fullName>201822</fullName>
                </value>
                <value>
                    <fullName>201823</fullName>
                </value>
                <value>
                    <fullName>201824</fullName>
                </value>
                <value>
                    <fullName>201825</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Planned</fullName>
                    <default>true</default>
                    <label>Planned</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Pending Direct Supervisor Approval</fullName>
                </value>
                <value>
                    <fullName>HR Review</fullName>
                </value>
                <value>
                    <fullName>Sent for Union Review</fullName>
                </value>
                <value>
                    <fullName>Ready for FPPS</fullName>
                </value>
                <value>
                    <fullName>Entered into FPPS</fullName>
                </value>
                <value>
                    <fullName>Ready for Bulk Upload</fullName>
                </value>
                <value>
                    <fullName>Bulk Uploaded</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                    <isActive>false</isActive>
                    <label>Approved</label>
                </value>
                <value>
                    <fullName>Awaiting Funding</fullName>
                    <isActive>false</isActive>
                    <label>Awaiting Funding</label>
                </value>
                <value>
                    <fullName>Funded</fullName>
                    <isActive>false</isActive>
                    <label>Funded</label>
                </value>
                <value>
                    <fullName>Partially Paid</fullName>
                    <isActive>false</isActive>
                    <label>Partially Paid</label>
                </value>
                <value>
                    <fullName>Ready for SSC</fullName>
                    <isActive>false</isActive>
                    <label>Ready for SSC</label>
                </value>
                <value>
                    <fullName>Ready for Work Codes</fullName>
                    <isActive>false</isActive>
                    <label>Ready for Work Codes</label>
                </value>
                <value>
                    <fullName>Received by OARS/Approved</fullName>
                    <isActive>false</isActive>
                    <label>Received by OARS/Approved</label>
                </value>
                <value>
                    <fullName>Reference</fullName>
                    <isActive>false</isActive>
                    <label>Reference</label>
                </value>
                <value>
                    <fullName>To SSC</fullName>
                    <isActive>false</isActive>
                    <label>To SSC</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Submitted_Date__c</fullName>
        <label>Submitted Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Supervisor_Justification__c</fullName>
        <inlineHelpText>If using the group award functionality, this field will automatically assume the justification of the group award.</inlineHelpText>
        <label>Supervisor Justification</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Time_Off_Amount__c</fullName>
        <description>Amount of time-off hours given to employee.</description>
        <inlineHelpText>Time Off awards greater than 10 hours require AO approval.</inlineHelpText>
        <label>Time Off Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type_of_Benefit__c</fullName>
        <label>Type of Benefit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Tangible</fullName>
                </value>
                <value>
                    <fullName>Intangible</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Value_of_Benefit__c</fullName>
        <description>Value of Benefit as defined on EPA's recommendation for incentive award form.</description>
        <label>Value of Benefit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Moderate</fullName>
                </value>
                <value>
                    <fullName>Substantial</fullName>
                </value>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Exceptional</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Award given to employee (or eventually to other recipients).  First used in AART.</description>
    <label>Award</label>
    <nameField>
        <displayFormat>AWARD-{0000000}</displayFormat>
        <label>Award Internal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Awards</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/MyAwardPlannerController.cls
/**
 * Controller for getting, updating Award records for award planning visualforce page.
 */

public with sharing class MyAwardPlannerController {
    public List<AwardWrapper> awardsList {get; set;}
    public Decimal budgetCashAmount {get; set;}
    public Decimal totalBudgetAmount {get; set;}
    public Decimal totalAllocatedAmount {get; set;}
    public Decimal totalBudgetRemaining {get; set;}
    public Boolean isSelected {get; set;}
    private final Id userId = UserInfo.getUserId();

    public class AwardWrapper {
        public Award__c award {get; set;}
        public Boolean selected {get; set;}

        public AwardWrapper(Award__c a) {
            award = a;
            selected = false;
        }
    }

    public MyAwardPlannerController() {
        if (awardsList == null) {
            awardsList = getPlannedAwards(userId);
        }

        Map<String, Decimal> budgetAmounts = getBudgetAmounts();
        budgetCashAmount = calculateCashAmount();
        totalBudgetAmount = budgetAmounts.get('totalBudget');
        totalAllocatedAmount = budgetAmounts.get('allocatedAmount');
        totalBudgetRemaining = 0.00;
        // Set all checkboxes to false when initially loading page
        isSelected = false;
    }

    /**
     * Builds and returns a list of AwardWrapper objects to populate the awards planner page.
     *
     * @param userId User accessing the page
     *
     * @return List of AwardWrapper objects for which that user has access
     */
    public List<AwardWrapper> getPlannedAwards(Id userId) {
        List<AwardWrapper> awardsList = new List<AwardWrapper>();

        List<Award__c> awards = [
                SELECT Id, Name, Emp_Name__r.Name, LCO__c, Division__c, Branch__c, Outside_LCO__c, Outside_ORD__c,
                        Cash_Award_Amount__c, Time_Off_Amount__c, Group_Award_Amount__c, Group_Award_Name__c,
                        Type_of_Benefit__c, Value_of_Benefit__c, Extent_of_Contribution__c, Supervisor_Justification__c,
                        Status__c, Pay_Period__c, OTS_Amount__c, Budget__c
                FROM Award__c
                WHERE Status__c = :AwardConstants.AWARD_STATUS_PLANNED
                ORDER BY Emp_Name__r.LastName ASC
        ];

        for (Award__c award : awards) {
            AwardWrapper aw = new AwardWrapper(award);
            awardsList.add(aw);
        }

        return awardsList;
    }

    /**
     * Saves all awards on the page and refreshes the page.
     *
     * @return Nothing - refreshes the page
     */
    public PageReference save() {
        List<Award__c> awards = new List<Award__c>();

        for (AwardWrapper aw : awardsList) {
            awards.add(aw.award);
        }

        upsert awards;

        ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.CONFIRM, 'Awards saved.'));
        PageReference currentPage = new PageReference(ApexPages.currentPage().getUrl());
        currentPage.setRedirect(true);
        return currentPage;
    }

    /**
     * Calculates upon page instantiation the amounts of the awards on the page.
     *
     * @return Total amount of all awards on the page
     */
    private Decimal calculateCashAmount() {
        Decimal amount = 0.00;

        for (AwardWrapper aw : awardsList) {
            amount = amount + aw.award.Cash_Award_Amount__c;
        }

        return amount;
    }

    /**
     * Gets the budget amounts that are linked to the awards on the AwardsPlanner page. If more than one budget is returned
     * then the budget amounts are added together and the sum is presented to the User.
     *
     * @param userId User accessing the planner page
     *
     * @return Map of total and allocated budget amounts
     */
    private Map<String, Decimal> getBudgetAmounts() {
        Map<String, Decimal> budgetAmountsMap = new Map<String, Decimal>();
        Map<Id, Document__c> budgets = new Map<Id, Document__c>();
        Set<Id> budgetIds = new Set<Id>();

        // Loop through the awards list and put the budget Ids in a set.
        if (!awardsList.isEmpty()) {
            for (AwardWrapper aw : awardsList) {
                if (aw.award.Budget__c != null) {
                    budgetIds.add(aw.award.Budget__c);
                }
            }
        }

        if (!budgetIds.isEmpty()) {
            budgets = AwardProcessSupporter.getBudgetsById(budgetIds);
        }

        if (budgets.size() == 1) {
            List<Document__c> budgetList = new List<Document__c>(budgets.values());
            budgetAmountsMap.put('totalBudget', budgets.get(budgetList[0].Id).Award_Total_Budget__c);
            budgetAmountsMap.put('allocatedAmount', budgets.get(budgetList[0].Id).Award_Allocated_Amount__c);
        } else {
            Decimal totalBudgetAmounts = 0;
            Decimal totalAllocatedAmounts = 0;

            for (Id budgetId : budgetIds) {
                totalBudgetAmounts = totalBudgetAmounts + budgets.get(budgetId).Award_Total_Budget__c;
                totalAllocatedAmounts = totalAllocatedAmounts + budgets.get(budgetId).Award_Allocated_Amount__c;
            }

            budgetAmountsMap.put('totalBudget', totalBudgetAmounts);
            budgetAmountsMap.put('allocatedAmount', totalAllocatedAmounts);
        }

        return budgetAmountsMap;
    }

    /**
     * Before submitting awards for approval, checks to make sure that the amounts of the awards do not exceed the
     * budget and then submits the awards for approval.
     *
     * @return Refreshes the page.
     */
    public PageReference submitAwardsForApproval() {
        List<Award__c> awards = new List<Award__c>();
        List<Award__c> outsideOrdAwards = new List<Award__c>();
        Boolean withinBudget = true;

        for (AwardWrapper aw : awardsList) {
            if (aw.selected) {
                awards.add(aw.award);
            }
        }

        if (!awards.isEmpty()) {
            // Check to make sure the sum of award values don't exceed budget
            Decimal awardsTotal = 0;
            for (Award__c award : awards) {
                awardsTotal = awardsTotal + award.Cash_Award_Amount__c;
            }

            Decimal budgetRemaining = totalBudgetAmount - totalAllocatedAmount;

            if (budgetRemaining < awardsTotal) {
                withinBudget = false;
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'The award amounts exceed the amount remaining ' +
                        'on the budget. Please update the amounts before submitting again.'));
                return null;
            }

            // Check to make sure that the submitted awards pass justification and budget validations.
            try {
                AwardProcessSupporter.submissionChecks(awards, UserInfo.getUserId());
            } catch (Exception e) {
                ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.FATAL, e.getMessage()));
                return null;
            }

            // If not budgetExceeded, then submit each award for approval
            if (withinBudget) {
                for (Award__c award : awards) {
                    if (!award.Outside_ORD__c) {
                        Approval.ProcessSubmitRequest approvalReq = new Approval.ProcessSubmitRequest();
                        approvalReq.setSubmitterId(userId);
                        approvalReq.setProcessDefinitionNameOrId('ORD_Awards_Approval_Process');
                        approvalReq.setObjectId(award.Id);
                        approvalReq.setComments('Please review this award for approval.');

                        try {
                            Approval.ProcessResult result = Approval.process(approvalReq);
                        } catch (Exception e) {
                            System.debug('Error message: ' + e.getMessage());
                            ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.FATAL, 'An error occurred with the ' +
                                    'following message: ' + e.getMessage()));
                        }
                    } else {
                        // If award is outside ORD, set status and update awards
                        award.Status__c = AwardConstants.AWARD_STATUS_AWAITING_FUNDING;
                        award.Submitted_Date__c = System.today();
                        outsideOrdAwards.add(award);
                    }
                }

                if (!outsideOrdAwards.isEmpty()) {
                    update awards;
                }
            }
        }

        ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.CONFIRM, 'Awards submitted successfully.'));
        PageReference currentPage = new PageReference(ApexPages.currentPage().getUrl());
        currentPage.setRedirect(true);
        return currentPage;
    }
}