objects/Award__c.object
<CustomObject>
    <fields>
        <fullName>Authorizing_Official__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Requesting official's supervisor. Responsible for the award's first level of approval.</description>
        <label>Authorizing Official</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Awards_Authorizing_Official</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Awardee_Direct_Supervisor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Awardee's Direct Supervisor. Used when a requesting official submits an award for someone outside of his/her organization.</description>
        <label>Awardee Direct Supervisor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Awards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Budget__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Budget that the award will be allocated toward.</description>
        <label>Budget</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Document__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Document - Award Budget</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Document__c</referenceTo>
        <relationshipLabel>Awards</relationshipLabel>
        <relationshipName>Budgeted_Awards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cincinnati_Office_Justification__c</fullName>
        <description>Required for Cincinnati Union Employees. Justification specific to the Cinc. Union form.</description>
        <inlineHelpText>Required for Awardees in the Cinc. Union. Press and hold the Ctrl key to select multiple options.</inlineHelpText>
        <label>Cincinnati Office Justification</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Substantially surpasses performance goals</fullName>
                </value>
                <value>
                    <fullName>Improved performance over the prior period</fullName>
                </value>
                <value>
                    <fullName>Reduced costs, expert performance, increased efficiencies</fullName>
                </value>
                <value>
                    <fullName>Makes significant contributions to the EPA</fullName>
                </value>
                <value>
                    <fullName>Exemplifies core values of the EPA</fullName>
                </value>
                <value>
                    <fullName>Achieves Specific Scientific Advancements</fullName>
                </value>
                <value>
                    <fullName>Prepares outstanding publications</fullName>
                </value>
                <value>
                    <fullName>Improves service to the public</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Emp_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Awardee's Name</description>
        <label>Emp Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Awards (Emp Name)</relationshipLabel>
        <relationshipName>Employee</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>QSI__c</fullName>
        <defaultValue>false</defaultValue>
        <label>QSI</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Requesting_Official__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Requesting Official Contact Lookup</description>
        <inlineHelpText>Requesting Official. The individual submitting the award. Please note, the budget is assigned based on the RO's organization.</inlineHelpText>
        <label>Requesting Official</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Awards (Contact)</relationshipLabel>
        <relationshipName>Awards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Supervisor_Justification__c</fullName>
        <inlineHelpText>If using the group award functionality, this field will automatically assume the justification of the group award.</inlineHelpText>
        <label>Supervisor Justification</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Value_and_Application__c</fullName>
        <description>Combined Value of Benefit and Extent of Application field with corresponding amount ranges.</description>
        <inlineHelpText>Select the applicable Value of Benefit and Extent of Application combination. The Cash Award amount will be restricted based on the corresponding amount range.</inlineHelpText>
        <label>Value and Application</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>MODERATE VALUE &amp; LIMITED APPLICATION ($25-125)</fullName>
                </value>
                <value>
                    <fullName>MODERATE VALUE &amp; EXTENDED APPLICATION ($125-325)</fullName>
                </value>
                <value>
                    <fullName>MODERATE VALUE &amp; BROAD APPLICATION ($325-650)</fullName>
                </value>
                <value>
                    <fullName>MODERATE VALUE &amp; GENERAL APPLICATION ($650-1,300)</fullName>
                </value>
                <value>
                    <fullName>SUBSTANTIAL VALUE &amp; LIMITED APPLICATION ($125-325)</fullName>
                </value>
                <value>
                    <fullName>SUBSTANTIAL VALUE &amp; EXTENDED APPLICATION ($325-650)</fullName>
                </value>
                <value>
                    <fullName>SUBSTANTIAL VALUE &amp; BROAD APPLICATION ($650-1,300)</fullName>
                </value>
                <value>
                    <fullName>SUBSTANTIAL VALUE &amp; GENERAL APPLICATION ($1,300-3,100)</fullName>
                </value>
                <value>
                    <fullName>HIGH VALUE &amp; LIMITED APPLICATION ($325-650)</fullName>
                </value>
                <value>
                    <fullName>HIGH VALUE &amp; EXTENDED APPLICATION ($650-1,300)</fullName>
                </value>
                <value>
                    <fullName>HIGH VALUE &amp; BROAD APPLICATION ($1,300-3,150)</fullName>
                </value>
                <value>
                    <fullName>HIGH VALUE &amp; GENERAL APPLICATION ($3,150-5,000)</fullName>
                </value>
                <value>
                    <fullName>EXCEPTIONAL VALUE &amp; LIMITED APPLICATION ($650-1,300)</fullName>
                </value>
                <value>
                    <fullName>EXCEPTIONAL VALUE &amp; EXTENDED APPLICATION ($1,300-3,150)</fullName>
                </value>
                <value>
                    <fullName>EXCEPTIONAL VALUE &amp; BROAD APPLICATION ($3,150-6,000)</fullName>
                </value>
                <value>
                    <fullName>EXCEPTIONAL VALUE &amp; BROAD APPLICATION ($3,150-5,000)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Work_Code_Lookup__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>NOT ENTERED BY REQUESTING OFFICIAL!</inlineHelpText>
        <label>Work Code Lookup</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Awards (Cost Center)</relationshipLabel>
        <relationshipName>Cost_Center</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>Award given to employee (or eventually to other recipients).  First used in AART.</description>
    <label>Award</label>
    <nameField>
        <displayFormat>AWARD-{0000000}</displayFormat>
        <label>Award Internal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Awards</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/AwardCloneController.cls
/**
 * AwardCloneController clones award records based on record type.
 */
public with sharing class AwardCloneController {
    private ApexPages.StandardController controller { get; set; }
    private Award__c award { get; set; }

    public AwardCloneController(ApexPages.StandardController controller) {
        this.controller = controller;
        award = (Award__c) controller.getRecord();
    }

    public void cashAwardClone() {
        String recordTypeName = 'Cash Award';

        cloneAward(recordTypeName);
    }

    public void timeoffAwardClone() {
        String recordTypeName = 'Time Off Award';

        cloneAward(recordTypeName);
    }

    public PageReference cloneAward(String recordTypeName) {
        Savepoint sp = Database.setSavepoint();
        Award__c newAward;
        Id recordTypeId;

        // Need to get the Awards record type
        String recordTypeToCopy;
        if (!String.isBlank(recordTypeName)) {
            recordTypeToCopy = recordTypeName;
            recordTypeId = Schema.SObjectType.Award__c.getRecordTypeInfosByName().get(recordTypeName).getRecordTypeId();
        } else {
            recordTypeToCopy = [SELECT RecordType.Name FROM Award__c WHERE Id = :award.Id LIMIT 1].RecordType.Name;
            recordTypeId = Schema.SObjectType.Award__c.getRecordTypeInfosByName().get(recordTypeToCopy).getRecordTypeId();
        }

        // Query for fields related to that record type
        String fields = getQueryFields(recordTypeToCopy);
        Id awardId = award.Id;
        String queryString = 'SELECT ' + fields + ' FROM Award__c WHERE Id = :awardId';

        // Use award.clone to clone the award record
        try {
            award = Database.query(queryString);

            newAward = award.clone(false, false, false, false);
            newAward.RecordTypeId = recordTypeId;

            insert newAward;
        } catch (DmlException e) {
            Database.rollback(sp);
            ApexPages.addMessages(e);
            return null;
        }

        System.debug('>>>> New award id: ' + newAward.Id);
        System.debug('>>>> Attempting to redirect ...');
        // Return a new page reference to the record
        return new PageReference('/' + newAward.Id);

    }

    /**
     * Because we're querying for fields based on record type, return the query string with specific fields for the
     * supplied record type name.
     *
     * @param recordTypeName Record type name for the award getting cloned
     *
     * @return Query string for the specific record type
     */
    private static String getQueryFields(String recordTypeName) {

        Map<String, String> queryFieldsByRecordType = new Map<String, String>{
                'Cash Award' => 'Requesting_Official__c, Emp_Name__c, Authorizing_Official__c, Awardee_Direct_Supervisor__c, Budget__c, Work_Code_Lookup__c, Value_and_Application__c, Supervisor_Justification__c, Cincinnati_Office_Justification__c',
                'QSI Award' => 'Requesting_Official__c, Emp_Name__c, Authorizing_Official__c, Awardee_Direct_Supervisor__c, Budget__c, Work_Code_Lookup__c, Value_and_Application__c, Supervisor_Justification__c, Cincinnati_Office_Justification__c, QSI__c',
                'Time Off Award' => 'Requesting_Official__c, Emp_Name__c, Authorizing_Official__c, Awardee_Direct_Supervisor__c, Budget__c, Work_Code_Lookup__c, Value_and_Application__c, Supervisor_Justification__c, Cincinnati_Office_Justification__c'
        };

        return queryFieldsByRecordType.get(recordTypeName);
    }

}