objects/Award__c.object
<CustomObject>
    <fields>
        <fullName>Budget__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Budget that the award will be allocated toward.</description>
        <label>Budget</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Document__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Document - Award Budget</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Document__c</referenceTo>
        <relationshipLabel>Awards</relationshipLabel>
        <relationshipName>Budgeted_Awards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cash_Award_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Amount of award given to employee (monetary awards only).</description>
        <inlineHelpText>Cash Awards over $2,000 require AO approval. Collective awards over $5,000 for an awardee require two levels of approval.</inlineHelpText>
        <label>Cash Award Amount</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Extent_of_Contribution__c</fullName>
        <description>Extent of Contribution as defined on EPA's recommendation for incentive award form.</description>
        <label>Extent of Contribution</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Limited</fullName>
                </value>
                <value>
                    <fullName>Extended</fullName>
                </value>
                <value>
                    <fullName>Broad</fullName>
                </value>
                <value>
                    <fullName>General</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IOAA_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The designated person with IOAA who would need to approve the award request, if necessary.</description>
        <inlineHelpText>Approver for awards that are over $5,000 or take the awardee over a total of $5,000 for cash awards within the fiscal year.</inlineHelpText>
        <label>IOAA Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>IOAA_Awards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Outside_ORD__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if the award is going to an individual outside of the RPIO.</description>
        <inlineHelpText>Please check if the Awardee is outside of ORD. If you do not check this field for non-ORD employees, the award will be at risk of not being processed.</inlineHelpText>
        <label>Outside ORD</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Supervisor_Justification__c</fullName>
        <inlineHelpText>If using the group award functionality, this field will automatically assume the justification of the group award.</inlineHelpText>
        <label>Supervisor Justification</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Type_of_Benefit__c</fullName>
        <label>Type of Benefit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Tangible</fullName>
                </value>
                <value>
                    <fullName>Intangible</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Value_of_Benefit__c</fullName>
        <description>Value of Benefit as defined on EPA's recommendation for incentive award form.</description>
        <label>Value of Benefit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Moderate</fullName>
                </value>
                <value>
                    <fullName>Substantial</fullName>
                </value>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Exceptional</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Award given to employee (or eventually to other recipients).  First used in AART.</description>
    <label>Award</label>
    <nameField>
        <displayFormat>AWARD-{0000000}</displayFormat>
        <label>Award Internal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Awards</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Supervisor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Approving Supervisor.  The end user may edit his approving supervisor from the "Edit My Approvers" page.</description>
        <label>Approving Supervisor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contact_Supervisor</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Supervisor__c</fullName>
        <description>Deprecated.  Use the Contact's Approving Supervisor instead.</description>
        <inlineHelpText>Deprecated.  Use the Contact's Approving Supervisor instead.</inlineHelpText>
        <label>(Deprecated) Approving Supervisor</label>
        <relationshipName>Supervisor</relationshipName>
        <restrictedAdminField>false</restrictedAdminField>
        <type>Hierarchy</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/MyAwardPlannerController_Test.cls
/**
 * Test methods for MyAwardPlannerController.
 */

@IsTest
public with sharing class MyAwardPlannerController_Test {
    static Id AWARD_RECORDTYPE_ID = Schema.SObjectType.Award__c.getRecordTypeInfosByName().get('Standard Award').getRecordTypeId();

    @TestSetup
    public static void setupTestData() {
        Account hrOrg = AwardTestUtilities.createOrganization('ORD-OARS');
        insert hrOrg;

        User testAwardeeSupervisor = AwardTestUtilities.createTestUser();
        testAwardeeSupervisor.LastName = 'User Supervisor';
        testAwardeeSupervisor.Username = 'test.awardeesupervisor@epa.gov.test';
        insert testAwardeeSupervisor;

        User testIoaaSupervisor = AwardTestUtilities.createTestUser();
        testIoaaSupervisor.LastName = 'IOAA Supervisor';
        testIoaaSupervisor.Username = 'test.ioaasupervisor@epa.gov.test';
        insert testIoaaSupervisor;

        List<Contact> employees = new List<Contact>();
        for(Integer i = 0; i < 3; i++) {
            Contact employee = AwardTestUtilities.createEmployee(hrOrg);
            employee.LastName = 'LastName' + i;
            employee.Supervisor__c = testAwardeeSupervisor.Id;

            employees.add(employee);
        }
        insert employees;

        Document__c budget = AwardTestUtilities.createBudget(hrOrg, 20000);
        insert budget;

        List<Award__c> awards = new List<Award__c>();
        for(Contact employee : employees) {
            Award__c award = AwardTestUtilities.createAward(employee);
            award.RecordTypeId = AWARD_RECORDTYPE_ID;
            award.OwnerId = UserInfo.getUserId();
            award.IOAA_Approver__c = testIoaaSupervisor.Id;
            award.Extent_of_Contribution__c = AwardTestUtilities.EXTENT_OF_CONTRIBUTION;
            award.Value_of_Benefit__c = AwardTestUtilities.VALUE_OF_BENEFIT;
            award.Type_of_Benefit__c = AwardTestUtilities.TYPE_OF_BENEFIT;
            award.Supervisor_Justification__c = AwardTestUtilities.SUPERVISOR_JUSTIFICATION;
            award.Budget__c = budget.Id;
            award.Cash_Award_Amount__c = 1000;

            awards.add(award);
        }
        insert awards;
    }

    @IsTest
    public static void testLoadAndSave() {
        Test.startTest();
        PageReference pageRef = Page.AwardsPlanner;
        Test.setCurrentPageReference(pageRef);

        MyAwardPlannerController controller = new MyAwardPlannerController();
        controller.getPlannedAwards(UserInfo.getUserId());
        controller.save();
        Test.stopTest();
    }

    @IsTest
    public static void testLoadWithMultipleBudgets() {
        Account newHrOrg = AwardTestUtilities.createOrganization('ORD-OARS');
        insert newHrOrg;

        Document__c newBudget = AwardTestUtilities.createBudget(newHrOrg, 20000);
        insert newBudget;

        Award__c award = [SELECT Id FROM Award__c LIMIT 1];
        award.Budget__c = newBudget.Id;
        update award;

        Test.startTest();
        PageReference pageRef = Page.AwardsPlanner;
        Test.setCurrentPageReference(pageRef);

        MyAwardPlannerController controller = new MyAwardPlannerController();
        controller.getPlannedAwards(UserInfo.getUserId());
        Test.stopTest();
    }

    @IsTest
    public static void testSubmitAward() {
        Test.startTest();
        PageReference pageRef = Page.AwardsPlanner;
        Test.setCurrentPageReference(pageRef);

        MyAwardPlannerController controller = new MyAwardPlannerController();
        controller.getPlannedAwards(UserInfo.getUserId());
        controller.awardsList[0].selected = true;
        controller.awardsList[1].award.Outside_ORD__c = true;
        controller.awardsList[1].selected = true;

        controller.submitAwardsForApproval();
        Test.stopTest();
    }

    @IsTest
    public static void testErrorHandling() {
        Test.startTest();
        PageReference pageRef = Page.AwardsPlanner;
        Test.setCurrentPageReference(pageRef);

        MyAwardPlannerController controller = new MyAwardPlannerController();
        controller.getPlannedAwards(UserInfo.getUserId());
        for(MyAwardPlannerController.AwardWrapper aw : controller.awardsList) {
            aw.award.Cash_Award_Amount__c = 8000;
            aw.selected = true;
        }

        controller.submitAwardsForApproval();
        Test.stopTest();
    }

    @IsTest
    public static void testSubmittingAwardWithoutJustification() {
        Test.startTest();
        PageReference pageRef = Page.AwardsPlanner;
        Test.setCurrentPageReference(pageRef);

        MyAwardPlannerController controller = new MyAwardPlannerController();
        controller.getPlannedAwards(UserInfo.getUserId());
        controller.awardsList[0].selected = true;
        controller.awardsList[0].award.Supervisor_Justification__c = null;
        controller.submitAwardsForApproval();
        Test.stopTest();

        System.assertNotEquals(null, ApexPages.getMessages(), 'Should have received a Justification error.');
    }

    @IsTest
    public static void testSubmittingAwardWithoutBudget() {
        Test.startTest();
        PageReference pageRef = Page.AwardsPlanner;
        Test.setCurrentPageReference(pageRef);

        MyAwardPlannerController controller = new MyAwardPlannerController();
        controller.getPlannedAwards(UserInfo.getUserId());
        controller.awardsList[0].selected = true;
        controller.awardsList[0].award.Budget__c = null;
        controller.submitAwardsForApproval();
        Test.stopTest();

        System.assertNotEquals(null, ApexPages.getMessages(), 'Should have received a missing Budget error.');
    }

}