objects/Candidate_Application__c.object
<CustomObject>
    <fields>
        <fullName>First_Line_Supervisor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>First Line Supervisor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Candidate_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Intended_Track__c</fullName>
        <label>Intended Track</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Development</fullName>
                </value>
                <value>
                    <fullName>Research</fullName>
                </value>
                <value>
                    <fullName>Expert</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Second_Line_Supervisor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Second Line Supervisor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Candidate_Applications1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>LOI Approved</fullName>
                </value>
                <value>
                    <fullName>Awaiting 1st Line Supervisor Approval</fullName>
                </value>
                <value>
                    <fullName>Awaiting 2nd Line Supervisor Approval</fullName>
                </value>
                <value>
                    <fullName>Awaiting TQB Coordinator Approval</fullName>
                </value>
                <value>
                    <fullName>Awaiting TQB Chair Approval</fullName>
                </value>
                <value>
                    <fullName>TQB Coordinator Review</fullName>
                </value>
                <value>
                    <fullName>TQB Scheduled</fullName>
                </value>
                <value>
                    <fullName>TQB Held</fullName>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                </value>
                <value>
                    <fullName>Incomplete</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Approved By 1st Line Supervisor</fullName>
                    <isActive>false</isActive>
                    <label>Approved By 1st Line Supervisor</label>
                </value>
                <value>
                    <fullName>Approved By 2nd Line Supervisor</fullName>
                    <isActive>false</isActive>
                    <label>Approved By 2nd Line Supervisor</label>
                </value>
                <value>
                    <fullName>Approved_by_TQB_Chair</fullName>
                    <isActive>false</isActive>
                    <label>Approved by TQB Chair</label>
                </value>
                <value>
                    <fullName>Awaiting L/C/O Approval</fullName>
                    <isActive>false</isActive>
                    <label>Awaiting L/C/O Approval</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <isActive>false</isActive>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>LOI Submitted</fullName>
                    <isActive>false</isActive>
                    <label>LOI Submitted</label>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                    <isActive>false</isActive>
                    <label>Rejected</label>
                </value>
                <value>
                    <fullName>Returned</fullName>
                    <isActive>false</isActive>
                    <label>Returned</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                    <isActive>false</isActive>
                    <label>Submitted</label>
                </value>
                <value>
                    <fullName>TQB Completed</fullName>
                    <isActive>false</isActive>
                    <label>TQB Completed</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Candidate Application</label>
    <nameField>
        <displayFormat>TQBR-{00000000}</displayFormat>
        <label>Candidate Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidate Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Candidate_Package</fullName>
        <active>true</active>
        <label>Candidate Application</label>
    </recordTypes>
    <recordTypes>
        <fullName>Letter_of_Intent_LOI</fullName>
        <active>true</active>
        <label>Letter of Intent (LOI)</label>
    </recordTypes>
</CustomObject>

objects/Question_Response__c.object
<CustomObject>
    <fields>
        <fullName>Candidate_Application__c</fullName>
        <label>Candidate Application</label>
        <referenceTo>Candidate_Application__c</referenceTo>
        <relationshipName>Question_Responses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <description>Question text.</description>
        <inlineHelpText>Allowed Character limit : 35,000</inlineHelpText>
        <label>Question</label>
        <length>35000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Questions__c</fullName>
        <label>Questions</label>
        <referenceTo>Questions__c</referenceTo>
        <relationshipLabel>Question Responses</relationshipLabel>
        <relationshipName>Question_Responses</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <description>Responses to questions (whose text is probably, , though not necessarily, held in the Questions object).</description>
    <label>Question Response</label>
    <nameField>
        <displayFormat>QR-{000000}</displayFormat>
        <label>Question Response ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Questions__c.object
<CustomObject>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Track__c</fullName>
        <label>Track</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Development</fullName>
                </value>
                <value>
                    <fullName>Research</fullName>
                </value>
                <value>
                    <fullName>Expert</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Question text, initially used for Technical Qualifications Board (TQB) reviews.</description>
    <label>Questions</label>
    <nameField>
        <displayFormat>Q-{000000}</displayFormat>
        <label>Questions ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TQBRequestHandler_Test.cls
@isTest(SeeAllData=true)
public class TQBRequestHandler_Test {

    public static string TEST_TRACK = 'Development';
    public static Id loiRt = [select id from recordtype where developerName='Letter_of_Intent_LOI'].Id;
    public static Id candidateRt = [select id from recordtype where developerName='Candidate_Package'].Id;

    //Candidate_Application__c
    @isTest
    public static void testInsertQuestionsToRequest(){
        // Insert a new request.
        // // Mounika Suram 8/10/2018 Updated the profile to System Administrator.
        Profile p = [select id, name from profile where name = 'System Administrator'];                
        User u = new User(FirstName='test', LastName='User', profileID=p.id, Username='test@userdomain.abc', 
                    email='test@userdomain.abc', Alias='testU', CommunityNickname='testU', TimeZoneSidKey= 'America/Los_Angeles',
                    LocaleSidKey='en_US', EmailEncodingKey='UTF-8', LanguageLocaleKey='en_US');
        insert u;
        
        Candidate_Application__c request1 = new Candidate_Application__c();
        request1.Intended_Track__c = TEST_TRACK;
        request1.First_Line_Supervisor__c = u.Id;
        request1.Second_Line_Supervisor__c = u.Id;
        // Mounika Suram 8/10/2018 Corrected the RecordTypeID
        request1.RecordTypeId = [select id,developerName from RecordType where SobjectType='Candidate_Application__c'  and developername='Letter_of_Intent_LOI'].id;
        system.runas(u) {
            test.StartTest();
            insert request1;
            System.debug('Status ' + request1.Id + ' & Status ' + request1.Intended_Track__c);


            TQBRequestHandler.addRelatedQuestions(new List<Candidate_Application__c>{
                    request1
            });
            TQBRequestHandler.createRequestResponses(null, null);
            // Validate if question responses have been updated with relevant questions.
            List<Question_Response__c> newRecords = [Select Id,Question__c from Question_Response__c where Candidate_Application__r.Id = :request1.Id and Candidate_Application__r.Intended_Track__c = :TEST_TRACK];
            System.debug('newRecords' + newRecords);
            // Mounika Suram 8/10/2018 Added the Status__c to the soql
            List<Questions__c> relatedQuestions = [Select id,Question__c from Questions__c where Status__c = 'Active'and Track__c = :TEST_TRACK]; System.debug('relatedQuestions' + relatedQuestions);
            System.assertEquals(newRecords.size(), relatedQuestions.size());

            // Add Attachment
            ContentVersion contentVersion = new ContentVersion();
            contentVersion.Title = 'test-' + request1.Id + '.pdf';
            contentVersion.PathOnClient = contentVersion.Title;
            Blob bodyBlob = EncodingUtil.base64Decode('TestFileData');
            contentVersion.VersionData = bodyBlob;
            contentVersion.IsMajorVersion = false;
            contentVersion.origin = 'H';
            insert contentVersion;
            ContentVersion testContent = [SELECT id, ContentDocumentId FROM ContentVersion where Id = :contentVersion.Id];

            ContentDocumentLink contentlink = new ContentDocumentLink();
            contentlink.LinkedEntityId = request1.id;
            contentlink.ShareType = 'V';
            contentlink.ContentDocumentId = testcontent.ContentDocumentId;
            insert contentlink;

            // Submit for approval - with attachment
            Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
            req1.setComments('Submitting request for approval.');
            req1.setObjectId(request1.id);
            // Submit on behalf of a specific submitter
            req1.setSubmitterId(u.Id);
            // Submit the approval request for the account
            Approval.ProcessResult result = Approval.process(req1);
            update request1;
            delete contentlink;
            test.StopTest();
        }
    }

    @istest
    public static void testSupervisorTriggers(){
        // TEST 2
        Profile p = [select id, name from profile where name = 'System Administrator'];
        User u = new User(FirstName='test', LastName='User', profileID=p.id, Username='test@userdomain.abc',
                email='test@userdomain.abc', Alias='testU', CommunityNickname='testU', TimeZoneSidKey= 'America/Los_Angeles',
                LocaleSidKey='en_US', EmailEncodingKey='UTF-8', LanguageLocaleKey='en_US');
        insert u;

        System.debug('Begin Test - Supervisors');
        Candidate_Application__c request2 = new Candidate_Application__c();
        request2.RecordTypeId = candidateRt;
        request2.Intended_Track__c = TEST_TRACK;
        request2.First_Line_Supervisor__c = u.Id;
        //request2.Second_Line_Supervisor__c = u.Id;
        system.runas(u) {
            test.StartTest();
            try{
            insert request2;

            // Submit for approval - with attachment
            Approval.ProcessSubmitRequest req2 = new Approval.ProcessSubmitRequest();
            req2.setComments('Submitting request2 for approval.');
            req2.setObjectId(request2.id);
            // Submit on behalf of a specific submitter
            req2.setSubmitterId(u.Id);
            // Submit the approval request for the account
            Approval.ProcessResult result2 = Approval.process(req2);
            update request2;
            } catch (Exception ee){}
            test.StopTest();
        }
    }


    @istest
    public static void testOtherTriggers(){
        // TEST 2
        Profile p = [select id, name from profile where name = 'System Administrator'];
        User u = new User(FirstName='test', LastName='User', profileID=p.id, Username='test@userdomain.abc',
                email='test@userdomain.abc', Alias='testU', CommunityNickname='testU', TimeZoneSidKey= 'America/Los_Angeles',
                LocaleSidKey='en_US', EmailEncodingKey='UTF-8', LanguageLocaleKey='en_US');
        insert u;

        System.debug('Begin Test - Other');
        Candidate_Application__c request2 = new Candidate_Application__c();
        request2.RecordTypeId = candidateRt;
        request2.Intended_Track__c = TEST_TRACK;
        request2.First_Line_Supervisor__c = u.Id;
        request2.Second_Line_Supervisor__c = u.Id;
        system.runas(u) {
            test.StartTest();
            try {
                insert request2;

                // Submit for approval - with attachment
                Approval.ProcessSubmitRequest req2 = new Approval.ProcessSubmitRequest();
                req2.setComments('Submitting request2 for approval.');
                req2.setObjectId(request2.id);
                // Submit on behalf of a specific submitter
                req2.setSubmitterId(u.Id);
                // Submit the approval request for the account
                Approval.ProcessResult result2 = Approval.process(req2);

                update request2;
            } catch (Exception ee){}
            test.StopTest();
        }
    }

}