objects/Candidate_Application__c.object
<CustomObject>
    <fields>
        <fullName>Intended_Track__c</fullName>
        <label>Intended Track</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Development</fullName>
                </value>
                <value>
                    <fullName>Research</fullName>
                </value>
                <value>
                    <fullName>Expert</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>LOI Approved</fullName>
                </value>
                <value>
                    <fullName>Awaiting 1st Line Supervisor Approval</fullName>
                </value>
                <value>
                    <fullName>Awaiting 2nd Line Supervisor Approval</fullName>
                </value>
                <value>
                    <fullName>Awaiting TQB Coordinator Approval</fullName>
                </value>
                <value>
                    <fullName>Awaiting TQB Chair Approval</fullName>
                </value>
                <value>
                    <fullName>TQB Coordinator Review</fullName>
                </value>
                <value>
                    <fullName>TQB Scheduled</fullName>
                </value>
                <value>
                    <fullName>TQB Held</fullName>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                </value>
                <value>
                    <fullName>Incomplete</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Approved By 1st Line Supervisor</fullName>
                    <isActive>false</isActive>
                    <label>Approved By 1st Line Supervisor</label>
                </value>
                <value>
                    <fullName>Approved By 2nd Line Supervisor</fullName>
                    <isActive>false</isActive>
                    <label>Approved By 2nd Line Supervisor</label>
                </value>
                <value>
                    <fullName>Approved_by_TQB_Chair</fullName>
                    <isActive>false</isActive>
                    <label>Approved by TQB Chair</label>
                </value>
                <value>
                    <fullName>Awaiting L/C/O Approval</fullName>
                    <isActive>false</isActive>
                    <label>Awaiting L/C/O Approval</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <isActive>false</isActive>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>LOI Submitted</fullName>
                    <isActive>false</isActive>
                    <label>LOI Submitted</label>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                    <isActive>false</isActive>
                    <label>Rejected</label>
                </value>
                <value>
                    <fullName>Returned</fullName>
                    <isActive>false</isActive>
                    <label>Returned</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                    <isActive>false</isActive>
                    <label>Submitted</label>
                </value>
                <value>
                    <fullName>TQB Completed</fullName>
                    <isActive>false</isActive>
                    <label>TQB Completed</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Candidate Application</label>
    <nameField>
        <displayFormat>TQBR-{00000000}</displayFormat>
        <label>Candidate Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidate Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Question_Response__c.object
<CustomObject>
    <fields>
        <fullName>Candidate_Application__c</fullName>
        <label>Candidate Application</label>
        <referenceTo>Candidate_Application__c</referenceTo>
        <relationshipName>Question_Responses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <description>Question text.</description>
        <inlineHelpText>Allowed Character limit : 35,000</inlineHelpText>
        <label>Question</label>
        <length>35000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Questions__c</fullName>
        <label>Questions</label>
        <referenceTo>Questions__c</referenceTo>
        <relationshipLabel>Question Responses</relationshipLabel>
        <relationshipName>Question_Responses</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <description>Responses to questions (whose text is probably, , though not necessarily, held in the Questions object).</description>
    <label>Question Response</label>
    <nameField>
        <displayFormat>QR-{000000}</displayFormat>
        <label>Question Response ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Questions__c.object
<CustomObject>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Track__c</fullName>
        <label>Track</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Development</fullName>
                </value>
                <value>
                    <fullName>Research</fullName>
                </value>
                <value>
                    <fullName>Expert</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Question text, initially used for Technical Qualifications Board (TQB) reviews.</description>
    <label>Questions</label>
    <nameField>
        <displayFormat>Q-{000000}</displayFormat>
        <label>Questions ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TQBRequestHandler.cls
public class TQBRequestHandler {

    private static Id tqbQuestionResponsesRT = Schema.SObjectType.Question_Response__c.getRecordTypeInfosByName().get('TQB Question Responses').getRecordTypeId();
    
    @InvocableMethod
    public static void addRelatedQuestions(List<Candidate_Application__c>  requests){
        if(requests.size() > 0){
            Candidate_Application__c  request = requests.get(0);
            String track = request.Intended_Track__c;
            System.debug('addRelatedQuestions for ' + request.Id + ' = ' + track);
            // Get all related questions
            List<Questions__c> relatedQuestions = TQBRequestHandler.getRelatedQuestions(track);
            System.debug('relatedQuestions = ' + relatedQuestions.size());
            // Create junction records for the request
            Boolean insertStatus = TQBRequestHandler.createRequestResponses(request,relatedQuestions);
            System.debug('insertStatus = ' + insertStatus);
        }
    }
    
    public static List<Questions__c> getRelatedQuestions(String track){
        List<Questions__c> relatedQuestions = null;
        try{
            //Mounika Suram-  4/11/2019 - updated the query to sort by ascending
            relatedQuestions = [Select id,Question__c from Questions__c where Status__c = 'Active' AND Track__c =:track order by Name ASC];
            if(Test.isRunningTest()) {
                CalloutException e = new CalloutException();
                e.setMessage('This is a constructed exception for testing and code coverage');
                throw e;
            }
        }catch(Exception e){
            System.debug('getRelatedQuestions query fail.'+e.getMessage());
        }
        return relatedQuestions;
    }
    public static Boolean createRequestResponses(Candidate_Application__c request, List<Questions__c> relatedQuestions){
        Boolean insertStatus = true;

        try{
            List<Question_Response__c> newRecords = null;
            // do we have to find any existing objects and modify?
            Boolean updateExistingQuestions = true;
            Boolean insertNewRecords = false;
            if(updateExistingQuestions){
                 //Mounika Suram-  4/11/2019 - updated the query to sort by ascending
                newRecords = [Select Id,Question__c from Question_Response__c where Candidate_Application__r.Id =:request.Id order by Name ASC];                
            }
            if(newRecords != null && newRecords.size()>0){ newRecords = null;
            }else{
                insertNewRecords = true;
            }
                
            if(insertNewRecords){
                newRecords = new  List<Question_Response__c>();
                for(Questions__c  relatedQuestion : relatedQuestions){
                    Question_Response__c reqResponse = new Question_Response__c();
                    reqResponse.Candidate_Application__c = request.Id;
                    reqResponse.Questions__c = relatedQuestion.Id;
                    reqResponse.Question__c = relatedQuestion.Question__c;
                    reqResponse.RecordTypeId = tqbQuestionResponsesRT;
                    newRecords.add(reqResponse);
                }
            }
            if(newRecords.size()>0){
                upsert newRecords;
            }
        }catch(Exception e){
            insertStatus = true;
            System.debug('Exception in createRequestResponses. '+e.getMessage());
        }
        return insertStatus;
    }
}