objects/Candidate_Application__c.object
<CustomObject>
    <fields>
        <fullName>First_Line_Supervisor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>First Line Supervisor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Candidate_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Intended_Track__c</fullName>
        <label>Intended Track</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Development</fullName>
                </value>
                <value>
                    <fullName>Research</fullName>
                </value>
                <value>
                    <fullName>Expert</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Second_Line_Supervisor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Second Line Supervisor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Candidate_Applications1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>LOI Approved</fullName>
                </value>
                <value>
                    <fullName>Awaiting 1st Line Supervisor Approval</fullName>
                </value>
                <value>
                    <fullName>Awaiting 2nd Line Supervisor Approval</fullName>
                </value>
                <value>
                    <fullName>Awaiting TQB Coordinator Approval</fullName>
                </value>
                <value>
                    <fullName>Awaiting TQB Chair Approval</fullName>
                </value>
                <value>
                    <fullName>TQB Coordinator Review</fullName>
                </value>
                <value>
                    <fullName>TQB Scheduled</fullName>
                </value>
                <value>
                    <fullName>TQB Held</fullName>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                </value>
                <value>
                    <fullName>Incomplete</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Approved By 1st Line Supervisor</fullName>
                    <isActive>false</isActive>
                    <label>Approved By 1st Line Supervisor</label>
                </value>
                <value>
                    <fullName>Approved By 2nd Line Supervisor</fullName>
                    <isActive>false</isActive>
                    <label>Approved By 2nd Line Supervisor</label>
                </value>
                <value>
                    <fullName>Approved_by_TQB_Chair</fullName>
                    <isActive>false</isActive>
                    <label>Approved by TQB Chair</label>
                </value>
                <value>
                    <fullName>Awaiting L/C/O Approval</fullName>
                    <isActive>false</isActive>
                    <label>Awaiting L/C/O Approval</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                    <isActive>false</isActive>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>LOI Submitted</fullName>
                    <isActive>false</isActive>
                    <label>LOI Submitted</label>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                    <isActive>false</isActive>
                    <label>Rejected</label>
                </value>
                <value>
                    <fullName>Returned</fullName>
                    <isActive>false</isActive>
                    <label>Returned</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                    <isActive>false</isActive>
                    <label>Submitted</label>
                </value>
                <value>
                    <fullName>TQB Completed</fullName>
                    <isActive>false</isActive>
                    <label>TQB Completed</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Candidate Application</label>
    <nameField>
        <displayFormat>TQBR-{00000000}</displayFormat>
        <label>Candidate Application ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidate Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Letter_of_Intent_LOI</fullName>
        <active>true</active>
        <label>Letter of Intent (LOI)</label>
    </recordTypes>
</CustomObject>

objects/Metadata__c.object
<CustomObject>
    <fields>
        <fullName>Filename__c</fullName>
        <description>Filename, Transmit Records, 04.16.19</description>
        <label>Filename</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Original_SF_ID__c</fullName>
        <description>Original copied SF ID, BAP Metadata, 2018.07.18</description>
        <label>Original SF ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <description>Parent of the metadata item, BAP Metadata, 2018.07.16</description>
        <label>Parent</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Generic Status field, currently used but the sandbox refresh log</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Metadata object for loading data to report on BAP itself</description>
    <label>Metadata</label>
    <nameField>
        <label>Metadata Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metadata</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Question_Response__c.object
<CustomObject>
    <fields>
        <fullName>Candidate_Application__c</fullName>
        <label>Candidate Application</label>
        <referenceTo>Candidate_Application__c</referenceTo>
        <relationshipName>Question_Responses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <description>Question text.</description>
        <inlineHelpText>Allowed Character limit : 35,000</inlineHelpText>
        <label>Question</label>
        <length>35000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Questions__c</fullName>
        <label>Questions</label>
        <referenceTo>Questions__c</referenceTo>
        <relationshipLabel>Question Responses</relationshipLabel>
        <relationshipName>Question_Responses</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <description>Responses to questions (whose text is probably, , though not necessarily, held in the Questions object).</description>
    <label>Question Response</label>
    <nameField>
        <displayFormat>QR-{000000}</displayFormat>
        <label>Question Response ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Questions__c.object
<CustomObject>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Track__c</fullName>
        <label>Track</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Development</fullName>
                </value>
                <value>
                    <fullName>Research</fullName>
                </value>
                <value>
                    <fullName>Expert</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Question text, initially used for Technical Qualifications Board (TQB) reviews.</description>
    <label>Questions</label>
    <nameField>
        <displayFormat>Q-{000000}</displayFormat>
        <label>Questions ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/FileSelector_Test.cls
@IsTest
private class FileSelector_Test {
    public static Id fileSelectorRt = Schema.SObjectType.Metadata__c.getRecordTypeInfosByName().get('File Selector').getRecordTypeId();
    public static string TEST_TRACK = 'Development';


    @IsTest
    static void testBehavior() {

        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        User u = new User(Alias = 'test2345', Email='standarduser@testorg.com',
                EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                LocaleSidKey='en_US', ProfileId = p.Id,
                TimeZoneSidKey='America/Los_Angeles',
                UserName='test72547@test.org');
        insert u;

        List<String> sObj = new List<String>();
        sObj.add('Candidate_Application__c');


        Candidate_Application__c request = new Candidate_Application__c();
        request.Intended_Track__c = TEST_TRACK;
        request.First_Line_Supervisor__c = u.Id;
        request.Second_Line_Supervisor__c = u.Id;
        // Mounika Suram 8/10/2018 Corrected the RecordTypeID
        request.RecordTypeId = [select id,developerName from RecordType where SobjectType='Candidate_Application__c'  and developername='Letter_of_Intent_LOI'].id;
        insert request;
        System.debug('Status ' + request.Id + ' & Status '+ request.Intended_Track__c);

        TQBRequestHandler.addRelatedQuestions(new List<Candidate_Application__c>{request});
        //TQBRequestHandler.createRequestResponses(null,null);
        // Validate if questoin responses have been updated with relavent questions.
        List<Question_Response__c> newRecords = [Select Id,Question__c from Question_Response__c where Candidate_Application__r.Id =:request.Id and Candidate_Application__r.Intended_Track__c=:TEST_TRACK ];
        System.debug('newRecords'+newRecords);
        // Mounika Suram 8/10/2018 Added the Status__c to the soql
        List<Questions__c> relatedQuestions = [Select id,Question__c from Questions__c where Status__c = 'Active'and Track__c =:TEST_TRACK];        System.debug('relatedQuestions'+relatedQuestions);
        System.assertEquals(newRecords.size(),relatedQuestions.size());


        List<Id> mdList = new List<Id>();
        mdList.add(request.id);

        Metadata__c c = new Metadata__c();
            c.RecordTypeId = fileSelectorRt;
            c.Parent__c = 'Test';
            c.Filename__c = 'Test.pdf';
            c.Name = 'Test';
            c.Original_SF_ID__c = '1234';
            insert c;

        ContentVersion contentVersion = new ContentVersion();
        contentVersion.Title = 'test-'+request.Id + '.pdf';
        contentVersion.PathOnClient = contentVersion.Title;
        Blob bodyBlob = EncodingUtil.base64Decode('TestFileData');
        contentVersion.VersionData = bodyBlob;
        contentVersion.IsMajorVersion = false;
        contentVersion.origin = 'H';
        //content.LinkedEntityId=sub.id;
        insert contentVersion;
        ContentDocumentLink contentlink=new ContentDocumentLink();
        contentlink.LinkedEntityId=request.id;
        contentlink.contentdocumentid=[select contentdocumentid from contentversion where id =: contentVersion.id].contentdocumentid;
        contentlink.ShareType = 'V';
        //test.starttest();
        //system.runAs(u) {

            insert contentlink;

            FileSelector_Controller.getAttachedFiles(mdList);
            FileSelector_Controller.getAttachedFiles2(mdList,sObj);
            String j = '["'+ contentlink.contentdocumentid +'"]';
            FileSelector_Controller.saveFileList(j, 'Test__c','Test');

        //}
        //test.StopTest();

        FileSelector_Controller.getPreselectedFiles(mdList);
        FileSelector_Controller.resetListAction(u.Id);



    }


}