objects/Contact.object
<CustomObject>
    <fields>
        <fullName>LAN_ID__c</fullName>
        <externalId>true</externalId>
        <label>LAN ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Supervisor_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Second Approving Supervisor.  The end user may edit his approving supervisors from the "Edit My Approvers" page.</description>
        <label>Approving Supervisor 2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contact_Supervisor_2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Supervisor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Approving Supervisor.  The end user may edit his approving supervisor from the "Edit My Approvers" page.</description>
        <label>Approving Supervisor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contact_Supervisor</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact_Approvers__c.object
<CustomObject>
    <fields>
        <fullName>Use_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Use Contact</label>
        <type>Checkbox</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Checkbox --  if checked, code uses Contact fields for Approval process, if not checked, code uses User fields for Approval process.</description>
    <label>Contact Approvers</label>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>LAN_ID__c</fullName>
        <externalId>true</externalId>
        <label>LAN ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Session_Token__c</fullName>
        <label>Session Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Supervisor_2__c</fullName>
        <description>Deprecated.  Use the Contact's Approving Supervisor 2 instead.</description>
        <inlineHelpText>Deprecated.  Use the Contact's Approving Supervisor 2 instead.</inlineHelpText>
        <label>(Deprecated) Approving Supervisor 2</label>
        <relationshipName>Supervisor_2</relationshipName>
        <restrictedAdminField>false</restrictedAdminField>
        <type>Hierarchy</type>
    </fields>
    <fields>
        <fullName>Supervisor__c</fullName>
        <description>Deprecated.  Use the Contact's Approving Supervisor instead.</description>
        <inlineHelpText>Deprecated.  Use the Contact's Approving Supervisor instead.</inlineHelpText>
        <label>(Deprecated) Approving Supervisor</label>
        <relationshipName>Supervisor</relationshipName>
        <restrictedAdminField>false</restrictedAdminField>
        <type>Hierarchy</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/FormPrintable_Test.cls
@isTest
public class FormPrintable_Test {

    @isTest
    static void testController(){
   
      //add test form
       insert new Contact_Approvers__c(name='Use Contact Fields', Use_Contact__c = false); // checkbox from "Contact Approvers" Custom Setting
         User u = [select id from User where isActive = true limit 1];
       User u2 = [select id from User where isActive = true and PRofile.Name = 'System Administrator' and id != :u.id limit 1];
        u.Session_Token__c = '123ABC';
        u.Supervisor__c = u2.id;
        u.Supervisor_2__c = u2.id;
        u.Lan_ID__c = 'thetest';
        update u;

        //siteUser
        User uSU = [select id from User where isActive = true AND id != :u.id AND id != :u2.id limit 1];
        
        //apiUser
        User uAU = [select id from User where isActive = true AND id != :u.id AND id != :u2.id AND id != :uSU.id limit 1];

        contact c = new contact(FirstName='Bob', LastName='Smith', Lan_ID__c = 'thetest');
        insert c;
     
        Forms__c testForm = new Forms__c();
        testForm.Unauthenticated_Owner__c = u.Id;
        testForm.approval_step__c = 'Form Prepared for you by test';
        testForm.RecordTypeID = [select id from RecordType where sObjectType = 'Forms__c' ORDER BY createddate limit 1].id;
        insert testForm;
 
 
 Test.setCurrentPageReference(new PageReference('Page.FormPrintablePDF'));
        ApexPages.StandardController stdCont= new ApexPages.StandardController(testForm);

        FormPrintable controller = new FormPrintable(stdCont);
    }

}