objects/Contact.object
<CustomObject>
    <fields>
        <fullName>EPA_Agreement_License__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>EPA License.Created to capture the EPA License.</description>
        <label>Record Id</label>
        <referenceTo>EPA_Agreement__c</referenceTo>
        <relationshipLabel>Inventor/s</relationshipLabel>
        <relationshipName>Inventors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Inventor_Amount__c</fullName>
        <defaultValue>0.0</defaultValue>
        <description>FTTA License. Created to capture the inventor amount for FTTA License.</description>
        <label>Inventor Amount</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Lab_Office_Amount__c</fullName>
        <defaultValue>0.0</defaultValue>
        <description>FTTA Application. Created to capture the lab amount input from the user.</description>
        <inlineHelpText>Please enter the amount for the Lab/Office.</inlineHelpText>
        <label>Lab/Office Amount</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>FTTA_License_Inventor</fullName>
        <active>true</active>
        <description>FTTA License Inventor.</description>
        <label>FTTA License Inventor</label>
    </recordTypes>
</CustomObject>

objects/EPA_Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Total_EPA_Inventor_Amount__c</fullName>
        <description>FTTA License Application. Created to capture the total amount from all related EPA Inventors</description>
        <label>Total EPA Inventor Amount</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Lab_Office_Amount__c</fullName>
        <description>FTTA License Application. Created to capture the total amount from all related lab/office.</description>
        <label>Total Lab / Office Amount</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Royalties__c</fullName>
        <description>FTTA License. Created to capture the total royalties amount.</description>
        <inlineHelpText>Total Royalties Amount</inlineHelpText>
        <label>Total Royalties Amount</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <description>Information on an EPA Agreement, initially used for FTTA, but also available for other uses.  (Note that the similarly named Agreement object has a Master-Detail relationship with Project, which limits the breadth of its potential use, whereas this object has no such Master-Detail relationship, so it can be used in more situations.)</description>
    <label>EPA Agreement</label>
    <nameField>
        <displayFormat>EPA-{0000000}</displayFormat>
        <label>Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EPA Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>FTTA_License</fullName>
        <active>true</active>
        <description>FTTA License</description>
        <label>FTTA License</label>
    </recordTypes>
</CustomObject>

classes/FTTA_CalculateTotalInventorAndLabTest.cls
/**********************************************************************
Name: FTTA_CalculateTotalInventorAndLabTest()
======================================================
======================================================
Purpose: Unit testing of FTTA_CalculateTotalInventorAndLab trigger.
-------
======================================================
======================================================
History
-------
VERSION AUTHOR        DATE       DETAIL              FEATURES/CSR/TTP
1.0 -   Mounika Suram 09/26/2018 INITIAL DEVELOPMENT CSR: FTTA License
***********************************************************************/
@isTest(SeeAllData=true)
public class FTTA_CalculateTotalInventorAndLabTest {

     @isTest
    private static void whenContactsAdded(){
        id fttaInventorRTId = [select id, developerName from RecordType where developerName='FTTA_License_Inventor'].id;
        id fttaLicenseId = [select id, developerName from RecordType where developerName='FTTA_License'].id;
        // Create mock data
        // Insert epa license
        EPA_Agreement__c license = [select id,Total_Royalties__c from EPA_Agreement__c where recordTypeId=:fttaLicenseId Limit 1];
        //Create accounting lines and associate with license
        List<Contact> conList= new List<Contact>();
        Contact con = new Contact();
        con.LastName='test';
        con.Inventor_Amount__c= 100.0;
        con.Lab_Office_Amount__c = 100.0;
        con.EPA_Agreement_License__c=license.id;
        con.RecordTypeId=fttaInventorRTId;
        conList.add(con);
        Contact con1 = new Contact();
        con1.LastName='test1';
        con1.Inventor_Amount__c= 100.0;
        con1.Lab_Office_Amount__c = 100.0;
        con1.EPA_Agreement_License__c=license.id;
        con1.RecordTypeId=fttaInventorRTId;
        conList.add(con1);
        Contact con2 = new Contact();
        con2.LastName='test2';
        con2.Inventor_Amount__c= 100.0;
        con2.Lab_Office_Amount__c = 100.0;
        con2.EPA_Agreement_License__c=license.id;
        con2.RecordTypeId=fttaInventorRTId;
        conList.add(con2);
        Test.startTest();
        insert conList;
        Decimal totalInventorAmount=[select id,Total_EPA_Inventor_Amount__c from EPA_Agreement__c where id=:license.id].Total_EPA_Inventor_Amount__c ;
        Decimal totalLabAmount=[select id,Total_Lab_Office_Amount__c from EPA_Agreement__c where id=:license.id].Total_Lab_Office_Amount__c ;
        con.Inventor_Amount__c= 200.0;
        con.Lab_Office_Amount__c = 200.0;
        update con;
        system.assertEquals(totalInventorAmount + 100.0, 
                            [select id,Total_EPA_Inventor_Amount__c from EPA_Agreement__c where id=:license.id].Total_EPA_Inventor_Amount__c);
        system.assertEquals(totalLabAmount + 100.0, 
                            [select id,Total_Lab_Office_Amount__c from EPA_Agreement__c where id=:license.id].Total_Lab_Office_Amount__c);
        delete con;
        Test.stopTest();
        
    }
}