objects/Contact.object
<CustomObject>
    <fields>
        <fullName>At_Time_Research_Was__c</fullName>
        <description>STAA</description>
        <label>At Time Research Was</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>EPA Employee (Not SES)</fullName>
                </value>
                <value>
                    <fullName>EPA SES, ST, SL or Title 42 Employee</fullName>
                </value>
                <value>
                    <fullName>PHS Assigned to EPA</fullName>
                </value>
                <value>
                    <fullName>Non EPA Author</fullName>
                    <isActive>false</isActive>
                    <label>Non EPA Author</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cover_Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>STAA</description>
        <label>Cover Form</label>
        <referenceTo>Cover_Form__c</referenceTo>
        <relationshipLabel>Authors</relationshipLabel>
        <relationshipName>Authors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Do_You_have_Record_of_Agree__c</fullName>
        <defaultValue>false</defaultValue>
        <description>STAA</description>
        <label>Record of Agreement?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Laboratory_Office_Name__c</fullName>
        <label>Laboratory/Office Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Seperation_Date__c</fullName>
        <description>STAA</description>
        <label>Retirement or Separation Date from EPA</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>of_Total_Effort__c</fullName>
        <description>STAA</description>
        <label>% of Total Effort</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Cover_Form__c.object
<CustomObject>
    <fields>
        <fullName>Citation__c</fullName>
        <description>STAA</description>
        <inlineHelpText>Use “Initial Caps” format.  For example, “Effect of Benzene on Adult Population”.  Do not use the title of the publication, do not exceed 120 characters including spaces.</inlineHelpText>
        <label>Citation</label>
        <length>256</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Eligibility_Criteria_1__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The nominated publication(s) has not been submitted to a previous STAA competition.</description>
        <label>Eligibility Criteria 1</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Eligibility_Criteria_2__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The nominated publication(s) was published on or before January 1, 2019, and on or after January 1, 2013.</description>
        <label>Eligibility Criteria 2</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Eligibility_Criteria_3__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The principal author was an EPA employee or a PHS employee assigned to EPA when the research was performed.</description>
        <label>Eligibility Criteria 3</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Eligibility_Criteria_4__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The EPA author has submitted a "Record of Agreement" to attest that credit has been correctly assigned.</description>
        <label>Eligibility Criteria 4</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Justification_1__c</fullName>
        <description>STAA</description>
        <inlineHelpText>Explain how the nominated  paper's represent research that is innovative and important in advancing the scientific knowledge or technology relevant to EPA's mission. It is, important to provide a clear and compelling explanation of the relevance.</inlineHelpText>
        <label>Justification 1</label>
        <length>16000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Justification_2A__c</fullName>
        <description>STAA</description>
        <inlineHelpText>Justification 2a: If multiple publications are submitted, provide a comprehensive explanation of the relationship and lengths between subject matter among the different nominated publications (Limit to 16,000 characters) Enter n/a if blank</inlineHelpText>
        <label>Justification 2A</label>
        <length>16000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Justification_2B__c</fullName>
        <description>STAA</description>
        <inlineHelpText>Justification 2b  List the previous 5 year's of STAA nominations and associated publications for each EPA author. Categorize the list by author and include publication title, year, and award.(Limit to 16,000 characters including spaces) Enter n/a if blank</inlineHelpText>
        <label>Justification 2B</label>
        <length>16000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Justification_2C__c</fullName>
        <description>STAA</description>
        <inlineHelpText>Justification 2c  Provide a description of how this nomination's publication(s) differ from previous (last 5 years) and current nominations by the author(s). (Limit to 16,000 characters including spaces.) Enter n/a if blank.</inlineHelpText>
        <label>Justification 2C</label>
        <length>16000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Justification_2D__c</fullName>
        <description>STAA</description>
        <inlineHelpText>Justification 2d Indicate whether previously submitted supplemental information is listed as supplemental information for the current nomination. (Limit to 16,000 characters including spaces.) Enter n/a if blank.</inlineHelpText>
        <label>Justification 2D</label>
        <length>16000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Justification_2E__c</fullName>
        <description>STAA</description>
        <inlineHelpText>Justification 2e If any of the authors have submitted a concurrent nomination to another research category, provide sufficient justification to distinguish the differnce between nominations. (Limit to 16,000 characters including spaces) Enter n/a if blank</inlineHelpText>
        <label>Justification 2E</label>
        <length>16000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Justification_3A__c</fullName>
        <description>STAA</description>
        <inlineHelpText>Justification 3a Provide evidence of recognition of the contribution from outside. (Limit to 16,000 characters including spaces.)</inlineHelpText>
        <label>Justification 3A</label>
        <length>16000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Justification_3B__c</fullName>
        <description>STAA</description>
        <inlineHelpText>Justification 3b Provide an explanation of the external peer review process used to evaluate the scientific merit of the nominated publication(s). (Limit to 16,000 characters including spaces.)</inlineHelpText>
        <label>Justification 3B</label>
        <length>16000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Laboratory_Office_Name__c</fullName>
        <defaultValue>$User.CompanyName</defaultValue>
        <description>STAA Application</description>
        <label>Laboratory/Office Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nominating_Official__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>STAA</description>
        <label>Nominating Official</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>User.Contact.User__c</field>
                <operation>equals</operation>
                <value>$User.Supervisor__c</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Cover_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Research_Category__c</fullName>
        <description>STAA</description>
        <label>Primary Research Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Control Systems and Technology (CS)</fullName>
                </value>
                <value>
                    <fullName>Ecological Research (ER)</fullName>
                </value>
                <value>
                    <fullName>Health Effects Research and Human Health Risk Assessment (HE)</fullName>
                </value>
                <value>
                    <fullName>Monitoring and Measurement Methods (MM)</fullName>
                </value>
                <value>
                    <fullName>Transport and Fate (TF)</fullName>
                </value>
                <value>
                    <fullName>Review Articles (RA)</fullName>
                </value>
                <value>
                    <fullName>Risk Management and Ecosystem Restoration (RM)</fullName>
                </value>
                <value>
                    <fullName>Integrated Risk Assessment (IR)</fullName>
                </value>
                <value>
                    <fullName>Environmental Policy and Decision-Making Studies (EP)</fullName>
                </value>
                <value>
                    <fullName>Homeland Security (HS)</fullName>
                </value>
                <value>
                    <fullName>Industry and the Environment (IE)</fullName>
                </value>
                <value>
                    <fullName>Energy and the Environment (EE)</fullName>
                </value>
                <value>
                    <fullName>Sustainability and Innovation (SI)</fullName>
                </value>
                <value>
                    <fullName>Other Environmental Research (OR)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>STAA_Coordinator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>STAA</description>
        <label>STAA Coordinator</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Cover_Forms1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>STAA</description>
        <inlineHelpText>The package stays in DRAFT mode until STAA Coordinator Marks FINAL.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DRAFT</fullName>
                    <default>true</default>
                    <label>DRAFT</label>
                </value>
                <value>
                    <fullName>LOCKED</fullName>
                    <label>LOCKED - Pending Nominating Official Approval</label>
                </value>
                <value>
                    <fullName>LOCKED2</fullName>
                    <label>LOCKED - Pending STAA Coordinator Approval</label>
                </value>
                <value>
                    <fullName>FINAL</fullName>
                </value>
                <value>
                    <fullName>AWARDED</fullName>
                </value>
                <value>
                    <fullName>NOT AWARDED</fullName>
                </value>
                <value>
                    <fullName>EXPIRED</fullName>
                </value>
                <value>
                    <fullName>Package Ready</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Initially created as an overflow object for the increasingly utilized Forms object, this object is oriented more toward forms intended to relegate most substantial content to attachments or other objects, as would a routing slip on top of a document.  Used initially in STAA, but available for other purposes, too.</description>
    <label>Cover Form</label>
    <nameField>
        <displayFormat>EPA-CF-{0000000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cover Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/STAAApplicationCommentsRequiredTest.cls
/*
*    Author : mondal.javed@epa.gov
*    CreatedDate : 7-May-2018
*    Class Name : STAAAplicationCommentsRequired
*    Test of trigger that requires Comments to be filled in at the time of Approval/Rejection. Then those Comments are inputted into a designated field on the Object
*
**/

@isTest
public class STAAApplicationCommentsRequiredTest

{
   public static Id staaRt = Schema.SObjectType.Cover_Form__c.getRecordTypeInfosByName().get('STAA Application').getRecordTypeId();
   public static Id staaAuthorRt = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('STAA Application').getRecordTypeId();
   public static Id staaPubRt = Schema.SObjectType.Line_Item__C.getRecordTypeInfosByName().get('STAA Application').getRecordTypeId();
    /*
        For this first test, create an object for approval, then
        simulate rejeting the approval with an added comment for explanation.
        
        The rejection should be processed normally without being interrupted.
    */
    private static testmethod void testRejectionWithComment()
    {
        User u =[select id from user where UserName='STAA21@test.org'];
        Cover_Form__c covF = [select id from cover_form__C where Laboratory_Office_Name__c ='Test' limit 1];
        system.runas(u){
        // Submit Request
        Approval.ProcessSubmitRequest testReq = new Approval.ProcessSubmitRequest();
        testReq.setObjectId(covF.Id);
        Approval.ProcessResult reqResult = Approval.process(testReq);
        
        // Generate sample work item using utility method.
        Id testWorkItemId = reqResult.getNewWorkitemIds()[0];
        
        // Reject the submitted request, providing a comment.
        Approval.ProcessWorkitemRequest testRej = new Approval.ProcessWorkitemRequest();
        testRej.setComments('Rejecting request with a comment.');
        testRej.setAction('Reject');
        testRej.setWorkitemId(testWorkItemId);
    
        Test.startTest();        
            try
            {
                Approval.ProcessResult testRejResult =  Approval.process(testRej);
                system.debug('testRejResult'+testRejResult);
                System.assert(testRejResult.isSuccess());
            }
            catch(DMLException e)
            {
                system.assertEquals('Operation Cancelled: Please provide a comment', 
                                    e.getDmlMessage(0), 
                  'error message should be Operation Cancelled: Please provide a rejection reason!'); 
            }
        Test.stopTest();
        
      }
        
    }
    
    /*
        For this test, create an object for approval, then reject the request, mark the approval status as pending, then
        without a comment explaining why. The rejection should be halted, and
        and an apex page message should be provided to the user.
    */
    private static testmethod void testRejectionWithoutComment()
    {
        
        User u =[select id from user where UserName='STAA21@test.org'];
        Cover_Form__c covF = [select id from cover_form__C where Laboratory_Office_Name__c ='Test' limit 1];
        system.runas(u){
        // Submit Request
        Approval.ProcessSubmitRequest testReq = new Approval.ProcessSubmitRequest();
        testReq.setObjectId(covF.Id);
        Approval.ProcessResult reqResult = Approval.process(testReq);
        // Generate sample work item using utility method.
        Id testWorkItemId = reqResult.getNewWorkitemIds()[0];
        
        // Reject the submitted request, without providing a comment.
        Approval.ProcessWorkitemRequest testRej = new Approval.ProcessWorkitemRequest();
        testRej.setComments('');
        testRej.setAction('Reject');      
        testRej.setWorkitemId(testWorkItemId);
    
        Test.startTest();        
            // Attempt to process the rejection
            try
            {
                Approval.ProcessResult testRejResult =  Approval.process(testRej);
                system.assert(false, 'A rejection with no comment should cause an exception');
            }
            catch(DMLException e)
            {
                system.assertEquals('Operation Cancelled: Please provide a comment', 
                                    e.getDmlMessage(0), 
                  'error message should be Operation Cancelled: Please provide a rejection reason!'); 
            }
        Test.stopTest();
    	}
    }
    
    /*
        When an approval is approved instead of rejected, a comment is not required, 
        mark the approval status as pending, then ensure that this functionality still holds together.
    */
    private static testmethod void testApprovalWithoutComment()
    {
                User u =[select id from user where UserName='STAA21@test.org'];
        Cover_Form__c covF = [select id from cover_form__C where Laboratory_Office_Name__c ='Test' limit 1];
        system.runas(u){
        // Submit Request
        Approval.ProcessSubmitRequest testReq = new Approval.ProcessSubmitRequest();
        testReq.setObjectId(covF.Id);
        Approval.ProcessResult reqResult = Approval.process(testReq);
        // Generate sample work item using utility method.
        Id testWorkItemId = reqResult.getNewWorkitemIds()[0];
        
        // approve the submitted request, without providing a comment.
        Approval.ProcessWorkitemRequest testApp = new Approval.ProcessWorkitemRequest();
        testApp.setComments('');
        testApp.setAction('Approve');
        testApp.setWorkitemId(testWorkItemId);
    
        Test.startTest();        
            try
            {
                Approval.ProcessResult testRejResult =  Approval.process(testApp);
                system.assert(false, 'A approval with no comment should cause an exception');
            }
            catch(DMLException e)
            {
                system.assertEquals('Operation Cancelled: Please provide a comment', 
                                    e.getDmlMessage(0), 
                  'error message should be Operation Cancelled: Please provide a approval reason!'); 
            }
        Test.stopTest();
     }
    }
    
    
    /*
        Utility method for creating single object, and submitting for approval.
        
        The method should return the Id of the work item generated as a result of the submission.
    */
    @TestSetup
    private static void setup()
    {
        // Create a sample form statement object and then submit it for approval.
            
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
		
        // Create User Record
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com',
        EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
        LocaleSidKey='en_US', ProfileId = p.Id,
        TimeZoneSidKey='America/Los_Angeles',
        UserName='STAA21@test.org');
        insert u;

        PermissionSet ps = [SELECT ID From PermissionSet WHERE Name = 'STAA_Coordinator_Access'];
        insert new PermissionSetAssignment(AssigneeId = u.id, PermissionSetId = ps.Id );
        
        // Create Cover Form Record
        Cover_Form__c CForm = new Cover_Form__c();
        CForm.RecordTypeId=staaRt;
        CForm.Status__c='DRAFT';
        CForm.Laboratory_Office_Name__c='Test';
        CForm.Primary_Research_Category__c = 'Ecological Research';
        CForm.Nominating_Official__c = u.Id;
        CForm.STAA_Coordinator__c  = u.Id;
        CForm.Justification_1__c = 'N/A';
        CForm.Justification_2A__c = 'N/A';
        CForm.Justification_2B__c = 'N/A';
        CForm.Justification_2C__c = 'N/A';
        CForm.Justification_2D__c = 'N/A';
        CForm.Justification_2E__c = 'N/A';
        CForm.Justification_3A__c = 'N/A';
        CForm.Justification_3B__c = 'N/A';
        CForm.Eligibility_Criteria_1__c = TRUE;
        CForm.Eligibility_Criteria_2__c = TRUE;
        CForm.Eligibility_Criteria_3__c = TRUE;
        CForm.Eligibility_Criteria_4__c = TRUE;
        CForm.Citation__c = 'Test';
        

        // Create Contact Record
       // Contact con = [Select Id, of_Total_Effort__c, Do_You_have_Record_of_Agree__c,At_Time_Research_Was__c,Seperation_Date__c
                               // from Contact where Cover_Form__c =: CForm.Id];
        Contact con = new Contact();
        con.RecordTypeId=staaAuthorRt;
        con.LastName='test';
        con.Cover_Form__c=CForm.id;
        con.of_Total_Effort__c = 100;
        con.Do_You_have_Record_of_Agree__c = TRUE;
        con.At_Time_Research_Was__c = 'PHS Assigned to EPA';
        con.Seperation_Date__c = System.today();
        
        // Create Publication Record
        Line_Item__c pub = new Line_Item__c();
        pub.RecordTypeId=staaPubRt;
        pub.Publication_Title__c  = '1';
        pub.Publication_Date__c   = Date.newInstance(2018, 12, 9);
        pub.Journal_Publication_Method__c = '1';
        pub.Volume__c = '1';
        pub.Number__c = '1';
        pub.Pages__c = '1';
        pub.Impact_Factor__c = '1';
        pub.Cover_Form__C = CForm.Id;
        

        // Create Publication Attachment Record
        ContentVersion contentVersion_1 = new ContentVersion(
          Title = 'Test',
          PathOnClient = 'Test.jpg',
          VersionData = Blob.valueOf('Test Content'),
          IsMajorVersion = true
        );
        
        system.runAs(u){
            insert CForm;
            insert con;
            insert pub;
            insert contentVersion_1;
            ContentVersion contentVersion_2 = [SELECT Id, Title, ContentDocumentId FROM ContentVersion WHERE Id = :contentVersion_1.Id LIMIT 1]; 
            ContentDocumentLink contentlink = new ContentDocumentLink();
            contentlink.LinkedEntityId = pub.id;
            contentlink.contentdocumentid = contentVersion_2.contentdocumentid;
            contentlink.ShareType = 'V';
            insert contentlink; 
        }
    }
}