objects/Contact.object
<CustomObject>
    <fields>
        <fullName>At_Time_Research_Was__c</fullName>
        <description>STAA</description>
        <label>At Time Research Was</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>EPA Employee (Not SES)</fullName>
                </value>
                <value>
                    <fullName>EPA SES, ST, SL or Title 42 Employee</fullName>
                </value>
                <value>
                    <fullName>PHS Assigned to EPA</fullName>
                </value>
                <value>
                    <fullName>Non EPA Author</fullName>
                    <isActive>false</isActive>
                    <label>Non EPA Author</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cover_Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>STAA</description>
        <label>Cover Form</label>
        <referenceTo>Cover_Form__c</referenceTo>
        <relationshipLabel>Authors</relationshipLabel>
        <relationshipName>Authors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Do_You_have_Record_of_Agree__c</fullName>
        <defaultValue>false</defaultValue>
        <description>STAA</description>
        <label>Record of Agreement?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Seperation_Date__c</fullName>
        <description>STAA</description>
        <label>Retirement or Separation Date from EPA</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>non_EPA_Personnel__c</fullName>
        <defaultValue>false</defaultValue>
        <label>non-EPA Personnel</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>of_Total_Effort__c</fullName>
        <description>STAA</description>
        <label>% of Total Effort</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Cover_Form__c.object
<CustomObject>
    <fields>
        <fullName>Citation__c</fullName>
        <description>STAA</description>
        <inlineHelpText>Use “Initial Caps” format.  For example, “Effect of Benzene on Adult Population”.  Do not use the title of the publication, do not exceed 120 characters including spaces.</inlineHelpText>
        <label>Citation</label>
        <length>256</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Eligibility_Criteria_1__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The nominated publication(s) has not been submitted to a previous STAA competition.</description>
        <label>Eligibility Criteria 1</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Eligibility_Criteria_2__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The nominated publication(s) was published on or before January 1, 2019, and on or after January 1, 2013.</description>
        <label>Eligibility Criteria 2</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Eligibility_Criteria_3__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The principal author was an EPA employee or a PHS employee assigned to EPA when the research was performed.</description>
        <label>Eligibility Criteria 3</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Eligibility_Criteria_4__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The EPA author has submitted a "Record of Agreement" to attest that credit has been correctly assigned.</description>
        <label>Eligibility Criteria 4</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Justification_1__c</fullName>
        <description>STAA</description>
        <inlineHelpText>Explain how the nominated  paper's represent research that is innovative and important in advancing the scientific knowledge or technology relevant to EPA's mission. It is, important to provide a clear and compelling explanation of the relevance.</inlineHelpText>
        <label>Justification 1</label>
        <length>16000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Justification_2A__c</fullName>
        <description>STAA</description>
        <inlineHelpText>Justification 2a: If multiple publications are submitted, provide a comprehensive explanation of the relationship and lengths between subject matter among the different nominated publications (Limit to 16,000 characters) Enter n/a if blank</inlineHelpText>
        <label>Justification 2A</label>
        <length>16000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Justification_2B__c</fullName>
        <description>STAA</description>
        <inlineHelpText>Justification 2b  List the previous 5 year's of STAA nominations and associated publications for each EPA author. Categorize the list by author and include publication title, year, and award.(Limit to 16,000 characters including spaces) Enter n/a if blank</inlineHelpText>
        <label>Justification 2B</label>
        <length>16000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Justification_2C__c</fullName>
        <description>STAA</description>
        <inlineHelpText>Justification 2c  Provide a description of how this nomination's publication(s) differ from previous (last 5 years) and current nominations by the author(s). (Limit to 16,000 characters including spaces.) Enter n/a if blank.</inlineHelpText>
        <label>Justification 2C</label>
        <length>16000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Justification_2D__c</fullName>
        <description>STAA</description>
        <inlineHelpText>Justification 2d Indicate whether previously submitted supplemental information is listed as supplemental information for the current nomination. (Limit to 16,000 characters including spaces.) Enter n/a if blank.</inlineHelpText>
        <label>Justification 2D</label>
        <length>16000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Justification_2E__c</fullName>
        <description>STAA</description>
        <inlineHelpText>Justification 2e If any of the authors have submitted a concurrent nomination to another research category, provide sufficient justification to distinguish the differnce between nominations. (Limit to 16,000 characters including spaces) Enter n/a if blank</inlineHelpText>
        <label>Justification 2E</label>
        <length>16000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Justification_3A__c</fullName>
        <description>STAA</description>
        <inlineHelpText>Justification 3a Provide evidence of recognition of the contribution from outside. (Limit to 16,000 characters including spaces.)</inlineHelpText>
        <label>Justification 3A</label>
        <length>16000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Justification_3B__c</fullName>
        <description>STAA</description>
        <inlineHelpText>Justification 3b Provide an explanation of the external peer review process used to evaluate the scientific merit of the nominated publication(s). (Limit to 16,000 characters including spaces.)</inlineHelpText>
        <label>Justification 3B</label>
        <length>16000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>STAA</description>
        <inlineHelpText>The package stays in DRAFT mode until STAA Coordinator Marks FINAL.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DRAFT</fullName>
                    <default>true</default>
                    <label>DRAFT</label>
                </value>
                <value>
                    <fullName>LOCKED</fullName>
                    <label>LOCKED - Pending Nominating Official Approval</label>
                </value>
                <value>
                    <fullName>LOCKED2</fullName>
                    <label>LOCKED - Pending STAA Coordinator Approval</label>
                </value>
                <value>
                    <fullName>FINAL</fullName>
                </value>
                <value>
                    <fullName>AWARDED</fullName>
                </value>
                <value>
                    <fullName>NOT AWARDED</fullName>
                </value>
                <value>
                    <fullName>EXPIRED</fullName>
                </value>
                <value>
                    <fullName>Package Ready</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Initially created as an overflow object for the increasingly utilized Forms object, this object is oriented more toward forms intended to relegate most substantial content to attachments or other objects, as would a routing slip on top of a document.  Used initially in STAA, but available for other purposes, too.</description>
    <label>Cover Form</label>
    <nameField>
        <displayFormat>EPA-CF-{0000000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cover Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/STAAAplicationFinalValidation.cls
/*
*    Author : mondal.javed@epa.gov
*    CreatedDate : 7-May-2018
*    Class Name : STAAAplicationFinalValidation
*    This class creates a VisualForce page that is populated with errors based on the criteria below (validateRecord class)
*
**/

public class STAAAplicationFinalValidation {

    public Cover_Form__c cForm;
    public String errorMessage{get;set;}
    public String recordId;
    
    // Get RecordType Id
    public Id RecordTypeIdToFilterBy = Schema.SObjectType.Cover_Form__c.getRecordTypeInfosByName().get('STAA Application').getRecordTypeId();
    
    public STAAAplicationFinalValidation(ApexPages.StandardController stdController) {
        recordId = stdController.getRecord().Id;       
        cForm = [Select Id, RecordTypeId, Eligibility_Criteria_1__c, Eligibility_Criteria_2__c, Eligibility_Criteria_3__c, Eligibility_Criteria_4__c,
            Justification_1__c, Justification_2A__c, Justification_2B__c, Justification_2C__c, Justification_2D__c, Justification_2E__c,
            Justification_3A__c, Justification_3B__c, Citation__c, Status__c
            from Cover_Form__c where Id =: recordId];
        
        // Inserts Error Message into the VisualForce page
        errorMessage = '<div class="errorTitle">Please review and complete the following fields</div>';
    }
    
    
    // Populates VisualForce Page
    public PageReference checkRecord(){
    if(cForm.recordtypeId == RecordTypeIdToFilterBy){
        if(!validateRecord()){ 
            Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
            //req1.setComments('Submitting request for approval.');
            req1.setObjectId(cForm.id);
            Approval.ProcessResult result = Approval.process(req1);
            
            if(result.isSuccess()){
                PageReference pg = new PageReference('/'+cForm.Id);
                pg.setRedirect(true);
                return pg;  
            }
            else{
                ApexPages.AddMessage(new ApexPages.Message(ApexPages.Severity.FATAL,'Approval Not Submitted Succesfully'));
                return null;
            }
        }
        else{
            ApexPages.AddMessage(new ApexPages.Message(ApexPages.Severity.FATAL,errorMessage));
            return null;
        }
        }
        return null;
    }
    


    // Checks for Errors
    public Boolean validateRecord() {
        
        Boolean result = False;
        
        if(cForm.Status__c != 'DRAFT'){
            errorMessage += '<div class="errorItem">- <span class="errorItemTitle">Application has already been submitted or expired (check "Comments" tab)</div>';
            result = TRUE;
        }
        
        ///// Eligibility Criteria boxes (error if not checked)
        if(!cForm.Eligibility_Criteria_1__c){
            errorMessage += '<div class="errorItem">- <span class="errorItemTitle">"Eligibility Criteria 1"</span> must be checked before application submission.</div>';
            result = TRUE;
        }
        
        if(!cForm.Eligibility_Criteria_2__c){
            errorMessage += '<div class="errorItem">- <span class="errorItemTitle">"Eligibility Criteria 2"</span> must be checked before application submission.</div>';
            result = TRUE;
        }
        
        if(!cForm.Eligibility_Criteria_3__c){
            errorMessage += '<div class="errorItem">- <span class="errorItemTitle">"Eligibility Criteria 3"</span> must be checked before application submission.</div>';
            result = TRUE;
        }
        
        if(!cForm.Eligibility_Criteria_4__c){
            errorMessage += '<div class="errorItem">- <span class="errorItemTitle">"Eligibility Criteria 4"</span> must be checked before application submission.</div>';
            result = TRUE;
        }

        ///// Justification text areas (error if empty)
        if(cForm.Justification_1__c == NULL){
            errorMessage += '<div class="errorItem">- <span class="errorItemTitle">"Justification 1"</span> needs to be filled.</div>';
            result = TRUE;
        }
        
        if(cForm.Justification_2A__c == NULL){
            errorMessage += '<div class="errorItem">- <span class="errorItemTitle">"Justification 2A"</span> needs to be filled.</div>';
            result = TRUE;
        }
        
        if(cForm.Justification_2B__c == NULL){
            errorMessage += '<div class="errorItem">- <span class="errorItemTitle">"Justification 2B"</span> needs to be filled.</div>';
            result = TRUE;
        }
        
        if(cForm.Justification_2C__c == NULL){
            errorMessage += '<div class="errorItem">- <span class="errorItemTitle">"Justification 2C"</span> needs to be filled.</div>';
            result = TRUE;
        }
 
         if(cForm.Justification_2D__c == NULL){
            errorMessage += '<div class="errorItem">- <span class="errorItemTitle">"Justification 2D"</span> needs to be filled.</div>';
            result = TRUE;
        }  
        
        if(cForm.Justification_2E__c == NULL){
            errorMessage += '<div class="errorItem">- <span class="errorItemTitle">"Justification 2E"</span> needs to be filled.</div>';
            result = TRUE;
        }
        
        if(cForm.Justification_3A__c == NULL){
            errorMessage += '<div class="errorItem">- <span class="errorItemTitle">"Justification 3A"</span> needs to be filled.</div>';
            result = TRUE;
        } 
        
        if(cForm.Justification_3B__c == NULL){
            errorMessage += '<div class="errorItem">- <span class="errorItemTitle">"Justification 3B"</span> needs to be filled.</div>';
            result = TRUE;
        } 

        if(cForm.Citation__c == NULL){
            errorMessage += '<div class="errorItem">- <span class="errorItemTitle">"Citation"</span> needs to be filled.</div>';
            result = TRUE;
        }
        
        /////////// Authors Related List
        //Id devRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('STAA Application').getRecordTypeId();
        
        Map<Id,Contact> listAuthors = new Map<Id,Contact>(
            [Select id, Name, of_Total_Effort__c, non_EPA_Personnel__c, Do_You_have_Record_of_Agree__c, At_Time_Research_Was__c, Seperation_Date__c from Contact where Cover_Form__c =: recordId]);       
        
        // Error if no Authors are created
        if(listAuthors.size() == 0){
            errorMessage += '<div class="errorItem">- Please Add <span class="errorItemTitle">Authors</span>.</div>';
            result = TRUE;
        }
        
        // Error if Authors' efforts do not add up to 100%
        Double total_eforts = 0;
        for (Contact con: listAuthors.values()){
            if(con.of_Total_Effort__c == NULL){
                total_eforts += 0;
            }
            if(con.of_Total_Effort__c != NULL){
                total_eforts += con.of_Total_Effort__c;
            }         
        }
        if (total_eforts != 100){
            errorMessage += '<div class="errorItem">- Check the <span class="errorItemTitle">"Authors"</span> Section. <span class="errorItemTitle">"% of Total Effort"</span> across Authors must sum 100%.</div>';
            result = TRUE;
        }
        
        
        for (Contact con: listAuthors.values()){
            String author_name = con.Name;
            Double percentage_eforts = con.of_Total_Effort__c;
                        
            // Error if '% of Total Effort' is zero of NULL
            if(percentage_eforts == 0 || percentage_eforts == NULL){
                errorMessage += '<div class="errorItem">- Check Author <span class="errorItemTitle">' + author_name + ' - "% of Total Effort"</span> must greater than 0%.</div>';
                result = TRUE;          
            }
            
            if(con.non_EPA_Personnel__c == FALSE){
                    // Error if 'At Time Research Was' not selected
                    if(con.At_Time_Research_Was__c == NULL){
                        errorMessage += '<div class="errorItem">- Check Author <span class="errorItemTitle">' + author_name + ' - "At Time Research Was"</span> value must be selected.</div>';
                        result = TRUE;              
                    }
            
                    // Error if 'Record of Agreement' not checked
                    if(con.Do_You_have_Record_of_Agree__c == FALSE){
                        errorMessage += '<div class="errorItem">- Check Author <span class="errorItemTitle">' + author_name + ' - "Record of Agreement"</span> must be checked.</div>';
                        result = TRUE;          
                    }           

            }
        }
    
        
        
        //////////Publications
        Map<Id,Line_Item__c> listPublication = new Map<Id,Line_Item__c>(
            [Select id, Name from Line_Item__c where Cover_Form__c =: recordId]);
        
        // Error if there are no Publications
        if(listPublication.size() == 0){
            errorMessage += '<div class="errorItem">- Please attach a file to your <span class="errorItemTitle">Publications</span>.</div>';
            result = TRUE;
        }
        
        Set<Id> newSet = listPublication.keySet();
        List<Id> newList = new List<Id>();
        newList.addAll(listPublication.keySet());
        if(newList.size() > 0){
            List<ContentDocumentLink> listContentDocumentLink = [Select id, LinkedEntityId from ContentDocumentLink where LinkedEntityId IN :newList];
        
            for(ContentDocumentLink cdl : listContentDocumentLink){
                if(listPublication.containsKey(cdl.LinkedEntityId))
                    newSet.remove(cdl.LinkedEntityId);
            }
            
            // Error if Publication does not have a file attached
            if(newSet.size() > 0){
                errorMessage += '<div class="errorItem">- Please attach at least <span class="errorItemTitle">1 file</span> to all the related <span class="errorItemTitle">Publications</span>.</div>';
                result = TRUE;
            }
        }
        
       
        return result;
        
    }
    
}