objects/Contact.object
<CustomObject>
    <fields>
        <fullName>At_Time_Research_Was__c</fullName>
        <description>STAA</description>
        <label>At Time Research Was</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>EPA Employee (Not SES)</fullName>
                </value>
                <value>
                    <fullName>EPA SES, ST, SL or Title 42 Employee</fullName>
                </value>
                <value>
                    <fullName>PHS Assigned to EPA</fullName>
                </value>
                <value>
                    <fullName>Non EPA Author</fullName>
                    <isActive>false</isActive>
                    <label>Non EPA Author</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cover_Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>STAA</description>
        <label>Cover Form</label>
        <referenceTo>Cover_Form__c</referenceTo>
        <relationshipLabel>Authors</relationshipLabel>
        <relationshipName>Authors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Do_You_have_Record_of_Agree__c</fullName>
        <defaultValue>false</defaultValue>
        <description>STAA</description>
        <label>Record of Agreement?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Seperation_Date__c</fullName>
        <description>STAA</description>
        <label>Retirement or Separation Date from EPA</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>non_EPA_Personnel__c</fullName>
        <defaultValue>false</defaultValue>
        <label>non-EPA Personnel</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>of_Total_Effort__c</fullName>
        <description>STAA</description>
        <label>% of Total Effort</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Cover_Form__c.object
<CustomObject>
    <fields>
        <fullName>Citation__c</fullName>
        <description>STAA</description>
        <inlineHelpText>Use “Initial Caps” format.  For example, “Effect of Benzene on Adult Population”.  Do not use the title of the publication, do not exceed 120 characters including spaces.</inlineHelpText>
        <label>Citation</label>
        <length>256</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Eligibility_Criteria_1__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The nominated publication(s) has not been submitted to a previous STAA competition.</description>
        <label>Eligibility Criteria 1</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Eligibility_Criteria_2__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The nominated publication(s) was published on or before January 1, 2019, and on or after January 1, 2013.</description>
        <label>Eligibility Criteria 2</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Eligibility_Criteria_3__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The principal author was an EPA employee or a PHS employee assigned to EPA when the research was performed.</description>
        <label>Eligibility Criteria 3</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Eligibility_Criteria_4__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The EPA author has submitted a "Record of Agreement" to attest that credit has been correctly assigned.</description>
        <label>Eligibility Criteria 4</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Justification_1__c</fullName>
        <description>STAA</description>
        <inlineHelpText>Explain how the nominated  paper's represent research that is innovative and important in advancing the scientific knowledge or technology relevant to EPA's mission. It is, important to provide a clear and compelling explanation of the relevance.</inlineHelpText>
        <label>Justification 1</label>
        <length>16000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Justification_2A__c</fullName>
        <description>STAA</description>
        <inlineHelpText>Justification 2a: If multiple publications are submitted, provide a comprehensive explanation of the relationship and lengths between subject matter among the different nominated publications (Limit to 16,000 characters) Enter n/a if blank</inlineHelpText>
        <label>Justification 2A</label>
        <length>16000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Justification_2B__c</fullName>
        <description>STAA</description>
        <inlineHelpText>Justification 2b  List the previous 5 year's of STAA nominations and associated publications for each EPA author. Categorize the list by author and include publication title, year, and award.(Limit to 16,000 characters including spaces) Enter n/a if blank</inlineHelpText>
        <label>Justification 2B</label>
        <length>16000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Justification_2C__c</fullName>
        <description>STAA</description>
        <inlineHelpText>Justification 2c  Provide a description of how this nomination's publication(s) differ from previous (last 5 years) and current nominations by the author(s). (Limit to 16,000 characters including spaces.) Enter n/a if blank.</inlineHelpText>
        <label>Justification 2C</label>
        <length>16000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Justification_2D__c</fullName>
        <description>STAA</description>
        <inlineHelpText>Justification 2d Indicate whether previously submitted supplemental information is listed as supplemental information for the current nomination. (Limit to 16,000 characters including spaces.) Enter n/a if blank.</inlineHelpText>
        <label>Justification 2D</label>
        <length>16000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Justification_2E__c</fullName>
        <description>STAA</description>
        <inlineHelpText>Justification 2e If any of the authors have submitted a concurrent nomination to another research category, provide sufficient justification to distinguish the differnce between nominations. (Limit to 16,000 characters including spaces) Enter n/a if blank</inlineHelpText>
        <label>Justification 2E</label>
        <length>16000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Justification_3A__c</fullName>
        <description>STAA</description>
        <inlineHelpText>Justification 3a Provide evidence of recognition of the contribution from outside. (Limit to 16,000 characters including spaces.)</inlineHelpText>
        <label>Justification 3A</label>
        <length>16000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Justification_3B__c</fullName>
        <description>STAA</description>
        <inlineHelpText>Justification 3b Provide an explanation of the external peer review process used to evaluate the scientific merit of the nominated publication(s). (Limit to 16,000 characters including spaces.)</inlineHelpText>
        <label>Justification 3B</label>
        <length>16000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Nominating_Official__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>STAA</description>
        <label>Nominating Official</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>User.Contact.User__c</field>
                <operation>equals</operation>
                <value>$User.Supervisor__c</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Cover_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Research_Category__c</fullName>
        <description>STAA</description>
        <label>Primary Research Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Control Systems and Technology (CS)</fullName>
                </value>
                <value>
                    <fullName>Ecological Research (ER)</fullName>
                </value>
                <value>
                    <fullName>Health Effects Research and Human Health Risk Assessment (HE)</fullName>
                </value>
                <value>
                    <fullName>Monitoring and Measurement Methods (MM)</fullName>
                </value>
                <value>
                    <fullName>Transport and Fate (TF)</fullName>
                </value>
                <value>
                    <fullName>Review Articles (RA)</fullName>
                </value>
                <value>
                    <fullName>Risk Management and Ecosystem Restoration (RM)</fullName>
                </value>
                <value>
                    <fullName>Integrated Risk Assessment (IR)</fullName>
                </value>
                <value>
                    <fullName>Environmental Policy and Decision-Making Studies (EP)</fullName>
                </value>
                <value>
                    <fullName>Homeland Security (HS)</fullName>
                </value>
                <value>
                    <fullName>Industry and the Environment (IE)</fullName>
                </value>
                <value>
                    <fullName>Energy and the Environment (EE)</fullName>
                </value>
                <value>
                    <fullName>Sustainability and Innovation (SI)</fullName>
                </value>
                <value>
                    <fullName>Other Environmental Research (OR)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>STAA_Coordinator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>STAA</description>
        <label>STAA Coordinator</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Cover_Forms1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>STAA</description>
        <inlineHelpText>The package stays in DRAFT mode until STAA Coordinator Marks FINAL.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DRAFT</fullName>
                    <default>true</default>
                    <label>DRAFT</label>
                </value>
                <value>
                    <fullName>LOCKED</fullName>
                    <label>LOCKED - Pending Nominating Official Approval</label>
                </value>
                <value>
                    <fullName>LOCKED2</fullName>
                    <label>LOCKED - Pending STAA Coordinator Approval</label>
                </value>
                <value>
                    <fullName>FINAL</fullName>
                </value>
                <value>
                    <fullName>AWARDED</fullName>
                </value>
                <value>
                    <fullName>NOT AWARDED</fullName>
                </value>
                <value>
                    <fullName>EXPIRED</fullName>
                </value>
                <value>
                    <fullName>Package Ready</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Initially created as an overflow object for the increasingly utilized Forms object, this object is oriented more toward forms intended to relegate most substantial content to attachments or other objects, as would a routing slip on top of a document.  Used initially in STAA, but available for other purposes, too.</description>
    <label>Cover Form</label>
    <nameField>
        <displayFormat>EPA-CF-{0000000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cover Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/STAAAplicationFinalValidationTest.cls
/*
*    Author : mondal.javed@epa.gov
*    CreatedDate : 7-May-2018
*    Class Name : STAAAplicationFinalValidationTest
*    This class tests VisualForce page that is populated with errors

**/

@isTest
private class STAAAplicationFinalValidationTest{
 public static Id staaRt = Schema.SObjectType.Cover_Form__c.getRecordTypeInfosByName().get('STAA Application').getRecordTypeId();
 public static Id staaAuthorRt = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('STAA Application').getRecordTypeId();
 public static Id staaPubRt = Schema.SObjectType.Line_Item__C.getRecordTypeInfosByName().get('STAA Application').getRecordTypeId();
  
 public static testMethod void beforeInsertTest(){
  
  Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];

    // Create User Record
    User u = new User(Alias = 'standt', Email='standarduser@testorg.com',
    EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
    LocaleSidKey='en_US', ProfileId = p.Id,
    TimeZoneSidKey='America/Los_Angeles',
    UserName='STAA2@test.org', Phone='1231231234');
    insert u;
	PermissionSet ps = [SELECT ID From PermissionSet WHERE Name = 'STAA_Coordinator_Access'];
    insert new PermissionSetAssignment(AssigneeId = u.id, PermissionSetId = ps.Id );
    // Create Contact Record
    Contact con = new Contact(LastName='Test',Email='standarduser@testorg.com', Phone='1231231234');
    
    
    Line_Item__c pub = new Line_Item__c();
    pub.RecordTypeId=staaPubRt;
    pub.Publication_Title__c  = '1';
    pub.Publication_Date__c   = Date.newInstance(2018, 12, 9);
    pub.Journal_Publication_Method__c = '1';
    pub.Volume__c = '1';
    pub.Number__c = '1';
    pub.Pages__c = '1';
    pub.Impact_Factor__c = '1';


    // Create Cover Form Record
    Cover_Form__c CForm = new Cover_Form__c();
    cForm.recordTypeId=staaRt; 
    CForm.Primary_Research_Category__c = 'Ecological Research';
    CForm.Nominating_Official__c = u.Id;
    CForm.STAA_Coordinator__c  = u.Id;
    CForm.Status__c = 'FINAL';
    
   
    // Begin Test Page
    Test.startTest(); 
     system.runAs(u) {
        insert CForm;
        insert con;
        insert pub;
        ApexPages.currentPage().getParameters().put('id',CForm.id);
        ApexPages.StandardController sc= new ApexPages.StandardController(CForm);
        STAAAplicationFinalValidation obj = new STAAAplicationFinalValidation(new ApexPages.StandardController(CForm));
        obj.checkRecord();
     }
    Test.stopTest();

 }
 

 public static testMethod void ValidationTest(){
  
    Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
    
    // Create User Record
    User u = new User(Alias = 'standt', Email='standarduser@testorg.com',
    EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
    LocaleSidKey='en_US', ProfileId = p.Id,
    TimeZoneSidKey='America/Los_Angeles',
    UserName='STTA3@test.org');
    insert u;
     
	PermissionSet ps = [SELECT ID From PermissionSet WHERE Name = 'STAA_Coordinator_Access'];
    insert new PermissionSetAssignment(AssigneeId = u.id, PermissionSetId = ps.Id );
    // Create Cover Form Record
    system.runAs(u) {
    Cover_Form__c CForm = new Cover_Form__c();
    cform.RecordTypeId=staaRt;
    CForm.Primary_Research_Category__c = 'Ecological Research';
    CForm.Nominating_Official__c = u.Id;
    CForm.STAA_Coordinator__c  = u.Id;
    CForm.Justification_1__c = 'N/A';
    CForm.Justification_2A__c = 'N/A';
    CForm.Justification_2B__c = 'N/A';
    CForm.Justification_2C__c = 'N/A';
    CForm.Justification_2D__c = 'N/A';
    CForm.Justification_2E__c = 'N/A';
    CForm.Justification_3A__c = 'N/A';
    CForm.Justification_3B__c = 'N/A';
    CForm.Eligibility_Criteria_1__c = TRUE;
    CForm.Eligibility_Criteria_2__c = TRUE;
    CForm.Eligibility_Criteria_3__c = TRUE;
    CForm.Eligibility_Criteria_4__c = TRUE;
    CForm.Citation__c = 'N/A';
    insert CForm;

    // Create Contact Record
    Contact con = [Select id, Name, of_Total_Effort__c, non_EPA_Personnel__c, Do_You_have_Record_of_Agree__c, At_Time_Research_Was__c, Seperation_Date__c from Contact where Cover_Form__c =: CForm.Id];
    con.LastName='test';
    con.Cover_Form__c=CForm.id;
    con.of_Total_Effort__c = 100;
    con.Do_You_have_Record_of_Agree__c = TRUE;
    con.At_Time_Research_Was__c = 'PHS Assigned to EPA';
    con.Seperation_Date__c = System.today();
   	update con;

    // Create Publication Record
    Line_Item__c pub = new Line_Item__c();
    //pub.RecordTypeId=staaPubRt; 
    pub.Publication_Title__c  = '1';
    pub.Publication_Date__c   = Date.newInstance(2018, 12, 9);
    pub.Journal_Publication_Method__c = '1';
    pub.Volume__c = '1';
    pub.Number__c = '1';
    pub.Pages__c = '1';
    pub.Impact_Factor__c = '1';
    pub.Cover_Form__C = CForm.Id;
    insert pub;

    // Create Publication Attachment Record
    ContentVersion contentVersion_1 = new ContentVersion(
      Title = 'Test',
      PathOnClient = 'Test.jpg',
      VersionData = Blob.valueOf('Test Content'),
      IsMajorVersion = true
    );
    
      
        insert contentVersion_1;
        ContentVersion contentVersion_2 = [SELECT Id, Title, ContentDocumentId FROM ContentVersion WHERE Id = :contentVersion_1.Id LIMIT 1]; 
        ContentDocumentLink contentlink = new ContentDocumentLink();
        contentlink.LinkedEntityId = pub.id;
        contentlink.contentdocumentid = contentVersion_2.contentdocumentid;
  		contentlink.ShareType = 'V';
        insert contentlink; 
        Test.startTest(); 
        //ApexPages.currentPage().getParameters().put('id',CForm.id);
        //ApexPages.StandardController sc= new ApexPages.StandardController(CForm);
        STAAAplicationFinalValidation obj = new STAAAplicationFinalValidation(new ApexPages.StandardController(CForm));
        obj.checkRecord();
   
    // Re-run Test without Contact and Publication Attachment Records
       delete con;
       delete contentlink;
       obj.checkRecord();
    
    Test.stopTest(); 
        }
 }
}