objects/Cover_Form__c.object
<CustomObject>
    <fields>
        <fullName>Citation__c</fullName>
        <description>STAA</description>
        <inlineHelpText>Use “Initial Caps” format.  For example, “Effect of Benzene on Adult Population”.  Do not use the title of the publication, do not exceed 120 characters including spaces.</inlineHelpText>
        <label>Citation</label>
        <length>256</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Nominating_Official__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>STAA</description>
        <label>Nominating Official</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>User.Contact.User__c</field>
                <operation>equals</operation>
                <value>$User.Supervisor__c</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Cover_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Research_Category__c</fullName>
        <description>STAA</description>
        <label>Primary Research Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Control Systems and Technology (CS)</fullName>
                </value>
                <value>
                    <fullName>Ecological Research (ER)</fullName>
                </value>
                <value>
                    <fullName>Health Effects Research and Human Health Risk Assessment (HE)</fullName>
                </value>
                <value>
                    <fullName>Monitoring and Measurement Methods (MM)</fullName>
                </value>
                <value>
                    <fullName>Transport and Fate (TF)</fullName>
                </value>
                <value>
                    <fullName>Review Articles (RA)</fullName>
                </value>
                <value>
                    <fullName>Risk Management and Ecosystem Restoration (RM)</fullName>
                </value>
                <value>
                    <fullName>Integrated Risk Assessment (IR)</fullName>
                </value>
                <value>
                    <fullName>Environmental Policy and Decision-Making Studies (EP)</fullName>
                </value>
                <value>
                    <fullName>Homeland Security (HS)</fullName>
                </value>
                <value>
                    <fullName>Industry and the Environment (IE)</fullName>
                </value>
                <value>
                    <fullName>Energy and the Environment (EE)</fullName>
                </value>
                <value>
                    <fullName>Sustainability and Innovation (SI)</fullName>
                </value>
                <value>
                    <fullName>Other Environmental Research (OR)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>STAA_Coordinator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>STAA</description>
        <label>STAA Coordinator</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Cover_Forms1</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>Initially created as an overflow object for the increasingly utilized Forms object, this object is oriented more toward forms intended to relegate most substantial content to attachments or other objects, as would a routing slip on top of a document.  Used initially in STAA, but available for other purposes, too.</description>
    <label>Cover Form</label>
    <nameField>
        <displayFormat>EPA-CF-{0000000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cover Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/STAA_ReportsForCoverFormTest.cls
/**********************************************************************
Name: STAA_ReportsForCoverFormTest

======================================================
======================================================
Purpose:
-------
Created this class to test the STAA_ReportsForCoverForm class.
======================================================
======================================================
History
-------
VERSION AUTHOR DATE DETAIL FEATURES/CSR/TTP
1.0 - Mounika Suram 7/12/2018 INITIAL DEVELOPMENT 
1.0- Mounika Suram	11/9/2018 Fixing the Errors in the production deployment.
***********************************************************************/
@isTest
public class STAA_ReportsForCoverFormTest {
    public static Id staaRt = Schema.SObjectType.Cover_Form__c.getRecordTypeInfosByName().get('STAA Application').getRecordTypeId();
    static testMethod void afterInsert(){
     
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com',
   	    EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
    	LocaleSidKey='en_US', 
        ProfileId = p.Id,
    	TimeZoneSidKey='America/Los_Angeles',
    	UserName='STTA10@test.org');
    	insert u;
        PermissionSet ps = [SELECT ID From PermissionSet WHERE Name = 'STAA_Coordinator_Access'];
        insert new PermissionSetAssignment(AssigneeId = u.id, PermissionSetId = ps.Id );
        
        cover_form__c cf = new cover_form__C();
        cf.Primary_Research_Category__c='Ecological Research';
        cf.Nominating_Official__c=u.id;
        cf.STAA_Coordinator__c=u.id;
        cf.Citation__c='Some Citation';
        cf.RecordTypeId=staaRt;
      	test.StartTest();
        system.runAs(u){
        insert cf;
        ApexPages.currentPage().getParameters().put('id',cf.id);
        ApexPages.StandardController sc= new ApexPages.StandardController(cf);
        STAA_ReportsForCoverForm ext= new STAA_ReportsForCoverForm(sc);
        ext.saveAttachment();
       
        }
         test.StopTest();
    }
    static testMethod void afterUpdate(){
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com',
   	    EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
    	LocaleSidKey='en_US', ProfileId = p.Id,
    	TimeZoneSidKey='America/Los_Angeles',
    	UserName='STTA11@test.org');
    	insert u;
        PermissionSet ps = [SELECT ID From PermissionSet WHERE Name = 'STAA_Coordinator_Access'];
        insert new PermissionSetAssignment(AssigneeId = u.id, PermissionSetId = ps.Id );
        cover_form__c cf = new cover_form__C();
        cf.Primary_Research_Category__c='Ecological Research';
        cf.Nominating_Official__c=u.Id;
        cf.STAA_Coordinator__c=u.Id;
        cf.Citation__c='Some Citation';
        cf.RecordTypeId=staaRt;
              
        ContentVersion contentVersion = new ContentVersion(); 
        contentVersion.Title = 'test-'+cf.Id + '.pdf'; 
        contentVersion.PathOnClient = contentVersion.Title; 
        Blob bodyBlob = EncodingUtil.base64Decode('TestFileData');
        contentVersion.VersionData = bodyBlob; 
        contentVersion.IsMajorVersion = false;
        contentVersion.origin = 'H';
        test.StartTest();
        system.runAs(u){
        insert cf;
        insert contentVersion;       
        ApexPages.CurrentPage().getParameters().put('id',cf.id);
        Apexpages.StandardController sc = new Apexpages.StandardController(cf);
        STAA_ReportsForCoverForm ext = new STAA_ReportsForCoverForm(sc);
        ext.saveAttachment();
        ext.redirectToPDFPage();
        
        }
        test.StopTest();
    }
    static testMethod void negativeTesting(){
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com',
   	    EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
    	LocaleSidKey='en_US', ProfileId = p.Id,
    	TimeZoneSidKey='America/Los_Angeles',
    	UserName='STTA11@test.org');
    	insert u;
        PermissionSet ps = [SELECT ID From PermissionSet WHERE Name = 'STAA_Coordinator_Access'];
        insert new PermissionSetAssignment(AssigneeId = u.id, PermissionSetId = ps.Id );
        cover_form__c cf = new cover_form__C();
        cf.Primary_Research_Category__c='Ecological Research';
        cf.Nominating_Official__c=u.Id;
        cf.STAA_Coordinator__c=u.Id;
        cf.Citation__c='Some Citation';
        cf.RecordTypeId=staaRt;           
        ContentVersion contentVersion = new ContentVersion(); 
        contentVersion.Title = 'test.pdf'; 
        contentVersion.PathOnClient = contentVersion.Title; 
        Blob bodyBlob = EncodingUtil.base64Decode('TestFileData');
        contentVersion.VersionData = bodyBlob; 
        contentVersion.IsMajorVersion = false;
        contentVersion.origin = 'H';
        
        test.StartTest();
        system.runAs(u){
        insert contentVersion;
        ApexPages.CurrentPage().getParameters().put('id',null);
        Apexpages.StandardController sc = new Apexpages.StandardController(cf);
        STAA_ReportsForCoverForm ext = new STAA_ReportsForCoverForm(sc);
        ext.saveAttachment();
        ext.redirectToPDFPage();
        }
         test.StopTest();
    }
    
}