objects/eOrder_Item__c.object
<CustomObject>
    <fields>
        <fullName>Delivery_Date__c</fullName>
        <description>GAS Application</description>
        <inlineHelpText>Delivery Date by Vendor</inlineHelpText>
        <label>Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Order_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Request</label>
        <referenceTo>Order_Request__c</referenceTo>
        <relationshipLabel>Order Request Items</relationshipLabel>
        <relationshipName>eOrder_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_List_Price__c</fullName>
        <formula>Product__r.List_Price__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Choose a Product by searching for Product details</description>
        <inlineHelpText>Choose a Product by searching for Product details</inlineHelpText>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>EPA_Product__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>EPA_Product__c.Vendor__r.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>EPA_Product__c</referenceTo>
        <relationshipLabel>eOrder Items</relationshipLabel>
        <relationshipName>eOrder_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <description>Number of cylinders requested</description>
        <inlineHelpText>Number of cylinders requested</inlineHelpText>
        <label>Quantity</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The current state of this item</description>
        <inlineHelpText>The current state of this item</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New Order</fullName>
                    <default>true</default>
                    <label>New Order</label>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Request Approved</fullName>
                </value>
                <value>
                    <fullName>Added to Order</fullName>
                </value>
                <value>
                    <fullName>Order Placed</fullName>
                </value>
                <value>
                    <fullName>Order Received</fullName>
                </value>
                <value>
                    <fullName>Order Delivered</fullName>
                </value>
                <value>
                    <fullName>Added to 1900-63</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Price__c</fullName>
        <formula>Product__r.List_Price__c * Quantity__c</formula>
        <label>Total Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Vendor_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Vendor Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>eOrder Items</relationshipLabel>
        <relationshipName>eOrder_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>X1900_63_Generated_Date__c</fullName>
        <label>1900-63 Generated Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>X1900_63__c</fullName>
        <defaultValue>false</defaultValue>
        <label>1900-63</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>eOrder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>eOrder</label>
        <referenceTo>eOrders__c</referenceTo>
        <relationshipLabel>eOrder Items</relationshipLabel>
        <relationshipName>eOrder_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>Specific or detailed items within an order tracked in the eOrders document, initially for the GAS application.  (Similar to Line Items, into which this item might be merged someday.)</description>
    <label>eOrder Item</label>
    <nameField>
        <displayFormat>EPA-EOI-{000000000}</displayFormat>
        <label>eOrder Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>eOrder Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/eOrders__c.object
<CustomObject>
    <fields>
        <fullName>Call_Number__c</fullName>
        <description>Identifier used internally with GAS Team</description>
        <inlineHelpText>Identifier used internally with GAS Team</inlineHelpText>
        <label>Call Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Request</label>
        <referenceTo>Order_Request__c</referenceTo>
        <relationshipLabel>eOrders</relationshipLabel>
        <relationshipName>eOrders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The current state of the eOrder</description>
        <inlineHelpText>The current state of the eOrder</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <color>#0B6FCE</color>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Activated</fullName>
                    <color>#78C953</color>
                    <label>Activated</label>
                </value>
                <value>
                    <fullName>Return Order Placed</fullName>
                    <color>#CC33CC</color>
                    <label>Return Order Placed</label>
                </value>
                <value>
                    <fullName>Order Placed</fullName>
                    <color>#E27001</color>
                    <label>Order Placed</label>
                </value>
                <value>
                    <fullName>Partial Order Received</fullName>
                    <color>#F3D904</color>
                    <label>Partial Order Received</label>
                </value>
                <value>
                    <fullName>Full Order Received</fullName>
                    <color>#A845DC</color>
                    <label>Full Order Received</label>
                </value>
                <value>
                    <fullName>Order Closed</fullName>
                    <color>#A53711</color>
                    <label>Order Closed</label>
                </value>
                <value>
                    <fullName>Return Order Closed</fullName>
                    <color>#333333</color>
                    <label>Return Order Closed</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vendor_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Choose the Vendor for which you want to create an eOrder</description>
        <inlineHelpText>Choose the Vendor for which you want to create an eOrder</inlineHelpText>
        <label>Vendor Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>GAS Vendors</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>eOrders</relationshipLabel>
        <relationshipName>eOrders</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>Custom Object to Capture Orders placed for GAS Order Management Application.</description>
    <label>eOrder</label>
    <nameField>
        <displayFormat>EPA-EO-{000000000}</displayFormat>
        <label>eOrder ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>eOrders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/EPA_Product__c.object
<CustomObject>
    <description>Products being acquired, products being generated by a process or system, or other kinds of objects being tracked, managed, reported on, etc.  Used initially for gas cylinder products being procured in the GAS application.</description>
    <label>Product</label>
    <nameField>
        <displayFormat>EPA-P-{0000000000}</displayFormat>
        <label>Product ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Order_Request__c.object
<CustomObject>
    <fields>
        <fullName>Delivery_Date__c</fullName>
        <description>Gas</description>
        <inlineHelpText>Potential Delivery Date</inlineHelpText>
        <label>Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Requester_Org__c</fullName>
        <description>GAS Order Management</description>
        <formula>Owner:User.Department</formula>
        <inlineHelpText>Requester Name typically the user who logged in and placing an order</inlineHelpText>
        <label>Requester Org</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vendor_Name__c</fullName>
        <description>PCOR Application.Created to capture the name of the vendor.</description>
        <label>Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <description>Requests for orders to be placed.  Initially used in the GAS application, then in PCORS, and available for other uses.  Used not only in native licensed access ("Type 3 interface" in BAP parlance) but also in "Type 1" interface (unlicensed guest access).</description>
    <label>Order Request</label>
    <nameField>
        <displayFormat>EPA-OR-{000000000}</displayFormat>
        <label>Order Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ORDGAS_190063savePDF.cls
/*
*    Author : mondal.javed@epa.gov
*    CreatedDate : 1-May-2018
*    Class Name : ORDGAS_190063savePDF 
*    Class called VisualForce page to attached data to files of the Account record when 'Generate 1900-63' button pushed
**/
public class ORDGAS_190063savePDF {
    public boolean isRedirect {get;set;}
    public Id pageeOrdId {get; set;}
    public List<eOrder_Item__c> eroderToDisplay {get; set;}
    public List<String> orgNames {get; set;}
    public String organizationName {get; set;}
  
    // The extension constructor initializes the private member
    // variable pageeOrd by using the getRecord method from the standard
    // controller.
    Date myDate = system.today();
    Private Account pageeOrd;
    public Boolean initialised{get; set;}

    //Constructor
    public ORDGAS_190063savePDF(ApexPages.StandardController stdController) {
        orgNames = new List<String>();
        this.pageeOrd = (Account)stdController.getRecord();
        pageeOrdId = ApexPages.currentPage().getParameters().get('id');
        initialised=false;
        system.debug('organizationName = ' + organizationName);
        system.debug('id = ' + pageeOrd.id + '     id2' +pageeOrdId);
        if(organizationName != null && orgNames.contains(organizationName)){
            eroderToDisplay = [
                    SELECT id, eOrder__r.Call_Number__c,Product__r.Name,Quantity__c,Product_List_Price__c,Total_Price__c,Order_Request__r.Requester_Org__c,Order_Request__r.Delivery_Date__c,X1900_63_Generated_Date__c
                    from eOrder_Item__c
                    where Vendor_Name__c = :pageeOrdId AND X1900_63__c = TRUE AND Status__c = 'Order Delivered' AND Order_Request__r.Requester_Org__c = :organizationName
            ];
        }
        else {
            eroderToDisplay = [SELECT id , eOrder__r.Call_Number__c,Product__r.Name,Quantity__c,Product_List_Price__c,Total_Price__c,Order_Request__r.Requester_Org__c,Order_Request__r.Delivery_Date__c,X1900_63_Generated_Date__c from eOrder_Item__c where Vendor_Name__c =:pageeOrdId AND X1900_63__c = TRUE AND Status__c = 'Order Delivered' ];
        }

        system.debug('@@@'+eroderToDisplay);
        for(eOrder_Item__c item :eroderToDisplay){
            if(!orgNames.contains(item.Order_Request__r.Requester_Org__c)){orgNames.add(item.Order_Request__r.Requester_Org__c);}
        }
        if(eroderToDisplay.isEmpty()){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'There are no eOrder Items with the status "Order Delivered" to be added to this form'));
        }
        isRedirect = false;
    }

    public void redirectToPDFPage(){
        isRedirect = true;
    }

    public pageReference getEordersForOrg(){
        System.debug('in getEordersForOrg');
        if(orgNames.contains(organizationName)) {
            eroderToDisplay = [
                    SELECT id, eOrder__r.Call_Number__c,Product__r.Name,Quantity__c,Product_List_Price__c,Total_Price__c,Order_Request__r.Requester_Org__c,Order_Request__r.Delivery_Date__c,X1900_63_Generated_Date__c
                    from eOrder_Item__c
                    where Vendor_Name__c = :pageeOrdId AND X1900_63__c = TRUE AND Status__c = 'Order Delivered' AND Order_Request__r.Requester_Org__c = :organizationName
            ];
            System.debug('Eorders' + eroderToDisplay);
        }
        else{
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'There are no eOrder Items with the status "Order Delivered" for the Organization'));
        }

        return null;
    }

    public pageReference Cancel(){
        PageReference vendorPage = new PageReference('/' + pageeOrdId);
        return vendorPage;
    }
    
//method to insert attachement call it on page on click of button 
    public pageReference saveAttachement() {
        string filename;
        PageReference vendorPage = new PageReference('/' + pageeOrdId);
        if (!initialised && pageeOrd.ID !=NULL) {
            System.debug('Eorders - save Attachment' + eroderToDisplay);
                PageReference pdf = Page.ORDGAS_190063;
                // create the new attachment
                Attachment attach = new Attachment();
                // the contents of the attachment from the pdf

                //body = pdf.getContentAsPDF();
                Blob body;
                try{
                    body = pdf.getContentAsPDF();
                }catch(Exception e){
                    body = EncodingUtil.base64Decode('TestFileData');
                }
                if(organizationName != null){
                    filename = '1900-63 - ' + pageeOrd.Name + ' - '+ organizationName + ' - '+ system.Now() +'.pdf';
                }
                else{
                    filename = '1900-63 - ' + pageeOrd.Name + ' - ' + system.Now() +'.pdf';
                }
                system.debug('body should be fine>>>' +filename);
                List<ContentVersion> contentVersionExisting = new List<ContentVersion>();
                contentVersionExisting = [select id,VersionNumber,VersionData, ContentDocumentId from ContentVersion WHERE title =: filename];
                if(contentVersionExisting.IsEmpty()){
                    contentVersion contentVersion = new ContentVersion();
                    contentVersion.Title = filename;
                    contentVersion.PathOnClient = '/'+contentVersion.Title ;
                    contentVersion.VersionData = body;
                    contentVersion.IsMajorVersion = false;
                    Insert contentVersion;
                    contentVersion = [select id, ContentDocumentId from ContentVersion WHERE Id =: contentVersion.Id];
                    ContentDocumentLink cl = new ContentDocumentLink();
                    cl.ContentDocumentId = contentVersion.ContentDocumentId;
                    cl.LinkedEntityId = pageeOrd.Id;
                    cl.ShareType = 'V';
                    cl.Visibility = 'AllUsers';
                    insert cl;
                }else{
                    contentVersionExisting[0].VersionData=body;
                    update contentVersionExisting[0];

                }
                for( eOrder_Item__c orderItems : eroderToDisplay){
                    orderItems.Status__c = 'Added to 1900-63';
                }
                update eroderToDisplay;
             }

        else {
          system.debug('Ran twice');
      }
        return vendorPage;
      
    } 
}