objects/eOrders__c.object
<CustomObject>
    <fields>
        <fullName>Order_Number__c</fullName>
        <displayFormat>EPA-PO-{000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The current state of the eOrder</description>
        <inlineHelpText>The current state of the eOrder</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <color>#0B6FCE</color>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Activated</fullName>
                    <color>#78C953</color>
                    <label>Activated</label>
                </value>
                <value>
                    <fullName>Return Order Placed</fullName>
                    <color>#CC33CC</color>
                    <label>Return Order Placed</label>
                </value>
                <value>
                    <fullName>Order Placed</fullName>
                    <color>#E27001</color>
                    <label>Order Placed</label>
                </value>
                <value>
                    <fullName>Partial Order Received</fullName>
                    <color>#F3D904</color>
                    <label>Partial Order Received</label>
                </value>
                <value>
                    <fullName>Full Order Received</fullName>
                    <color>#A845DC</color>
                    <label>Full Order Received</label>
                </value>
                <value>
                    <fullName>Order Closed</fullName>
                    <color>#A53711</color>
                    <label>Order Closed</label>
                </value>
                <value>
                    <fullName>Return Order Closed</fullName>
                    <color>#333333</color>
                    <label>Return Order Closed</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Custom Object to Capture Orders placed for GAS Order Management Application.</description>
    <label>eOrder</label>
    <nameField>
        <displayFormat>EPA-EO-{000000000}</displayFormat>
        <label>eOrder ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>eOrders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ORDGAS_savePDF.cls
/*
*    Author : mondal.javed@epa.gov
*    CreatedDate : 1-May-2018
*    Class Name : ORDGAS_savePDF 
*    Class called VisualForce page to attached data to files of the eOrder record when 'Generate Document' button pushed
**/
public class ORDGAS_savePDF {
    public boolean isRedirect {get;set;}
    public String orderNumber {get;set;}
  
    // The extension constructor initializes the private member
    // variable pageeOrd by using the getRecord method from the standard
    // controller.
    Date myDate = system.today();
    Private eOrders__c pageeOrd;
    public Boolean initialised{get; set;}

    //Constructor
    public ORDGAS_savePDF(ApexPages.StandardController stdController) {
        this.pageeOrd = (eOrders__c)stdController.getRecord();
        id pageeOrdId = ApexPages.currentPage().getParameters().get('id');
        initialised=false;
        orderNumber = [select Order_Number__c from eOrders__c where id=:pageeOrdId].Order_Number__c;
        system.debug('id = ' + pageeOrd.id + '     id2' +pageeOrdId);
        isRedirect = false;
    }

    public void redirectToPDFPage(){
        isRedirect = true;
    }
    
//method to insert attachement call it on page on click of button 
    public void saveAttachement() {
        if (!initialised && pageeOrd.ID !=NULL) {

        PageReference pdf = Page.EOrderPage;
        // create the new attachment
        Attachment attach = new Attachment();
        // the contents of the attachment from the pdf

        //body = pdf.getContentAsPDF();
        Blob body;
        try{
            body = pdf.getContentAsPDF();
        }catch(Exception e){
            body = EncodingUtil.base64Decode('TestFileData');
        }
        string filename = 'eOrder_'+ orderNumber +'.pdf';
        system.debug('body should be fine>>>' +filename);
        List<ContentVersion> contentVersionExisting = new List<ContentVersion>(); 
        contentVersionExisting = [select id,VersionNumber,VersionData, ContentDocumentId from ContentVersion WHERE title =: filename];
        if(contentVersionExisting.IsEmpty()){
            contentVersion contentVersion = new ContentVersion(); 
            contentVersion.Title = filename; 
            contentVersion.PathOnClient = '/'+contentVersion.Title ; 
            contentVersion.VersionData = body; 
            contentVersion.IsMajorVersion = false;
            Insert contentVersion;
            contentVersion = [select id, ContentDocumentId from ContentVersion WHERE Id =: contentVersion.Id];
            ContentDocumentLink cl = new ContentDocumentLink();
            cl.ContentDocumentId = contentVersion.ContentDocumentId;
            cl.LinkedEntityId = pageeOrd.Id; 
            cl.ShareType = 'V';
            cl.Visibility = 'AllUsers';
            insert cl;
        }else{
            contentVersionExisting[0].VersionData=body;
            update contentVersionExisting[0];
            
        }
        eOrders__c order = [SELECT Status__c FROM eOrders__c WHERE Id =:pageeOrd.Id ];
        if(order.Status__c == 'Draft'){
            order.Status__c = 'Activated';
            update order;
        }

        } else {
          system.debug('tried to run twice');
      }
      
    } 
}