objects/eOrder_Item__c.object
<CustomObject>
    <fields>
        <fullName>Order_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Request</label>
        <referenceTo>Order_Request__c</referenceTo>
        <relationshipLabel>Order Request Items</relationshipLabel>
        <relationshipName>eOrder_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The current state of this item</description>
        <inlineHelpText>The current state of this item</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New Order</fullName>
                    <default>true</default>
                    <label>New Order</label>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Request Approved</fullName>
                </value>
                <value>
                    <fullName>Added to Order</fullName>
                </value>
                <value>
                    <fullName>Order Placed</fullName>
                </value>
                <value>
                    <fullName>Order Received</fullName>
                </value>
                <value>
                    <fullName>Order Delivered</fullName>
                </value>
                <value>
                    <fullName>Added to 1900-63</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Specific or detailed items within an order tracked in the eOrders document, initially for the GAS application.  (Similar to Line Items, into which this item might be merged someday.)</description>
    <label>eOrder Item</label>
    <nameField>
        <displayFormat>EPA-EOI-{000000000}</displayFormat>
        <label>eOrder Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>eOrder Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/eOrders__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <description>Comments to help describe the needs, uses, and etc. of the eOrder</description>
        <inlineHelpText>Comments to help describe the needs, uses, and etc. of the eOrder</inlineHelpText>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Order_Amount__c</fullName>
        <description>Total Cost of the sum of associated eOrder Items</description>
        <inlineHelpText>Total Cost of the sum of associated eOrder Items</inlineHelpText>
        <label>Order Amount</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Order_Number__c</fullName>
        <displayFormat>EPA-PO-{000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Order_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Request</label>
        <referenceTo>Order_Request__c</referenceTo>
        <relationshipLabel>eOrders</relationshipLabel>
        <relationshipName>eOrders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The current state of the eOrder</description>
        <inlineHelpText>The current state of the eOrder</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <color>#0B6FCE</color>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Activated</fullName>
                    <color>#78C953</color>
                    <label>Activated</label>
                </value>
                <value>
                    <fullName>Return Order Placed</fullName>
                    <color>#CC33CC</color>
                    <label>Return Order Placed</label>
                </value>
                <value>
                    <fullName>Order Placed</fullName>
                    <color>#E27001</color>
                    <label>Order Placed</label>
                </value>
                <value>
                    <fullName>Partial Order Received</fullName>
                    <color>#F3D904</color>
                    <label>Partial Order Received</label>
                </value>
                <value>
                    <fullName>Full Order Received</fullName>
                    <color>#A845DC</color>
                    <label>Full Order Received</label>
                </value>
                <value>
                    <fullName>Order Closed</fullName>
                    <color>#A53711</color>
                    <label>Order Closed</label>
                </value>
                <value>
                    <fullName>Return Order Closed</fullName>
                    <color>#333333</color>
                    <label>Return Order Closed</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Custom Object to Capture Orders placed for GAS Order Management Application.</description>
    <label>eOrder</label>
    <nameField>
        <displayFormat>EPA-EO-{000000000}</displayFormat>
        <label>eOrder ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>eOrders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/EPA_Product__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <description>Products being acquired, products being generated by a process or system, or other kinds of objects being tracked, managed, reported on, etc.  Used initially for gas cylinder products being procured in the GAS application.</description>
    <label>Product</label>
    <nameField>
        <displayFormat>EPA-P-{0000000000}</displayFormat>
        <label>Product ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Order_Request__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <description>Comments to help describe the needs, uses, and etc. of the Order Request</description>
        <inlineHelpText>Comments to help describe the needs, uses, and etc. of the Order Request</inlineHelpText>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <description>Requests for orders to be placed.  Initially used in the GAS application, then in PCORS, and available for other uses.  Used not only in native licensed access ("Type 3 interface" in BAP parlance) but also in "Type 1" interface (unlicensed guest access).</description>
    <label>Order Request</label>
    <nameField>
        <displayFormat>EPA-OR-{000000000}</displayFormat>
        <label>Order Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ORDGAS_savePDFTest.cls
/*
*    Author : mondal.javed@epa.gov
*    CreatedDate : 1-May-2018
*    Class Name : ORDGAS_savePDFTest
*    Test Class for ORDGAS_savePDF
**/
@isTest
Public Class ORDGAS_savePDFTest{
    private static Id recordTypeId = Schema.SObjectType.Line_Item__c.getRecordTypeInfosByName().get('GAS Cylinders').getRecordTypeId();
    private static Id recordTypeIdVendor = Schema.SObjectType.Account.getRecordTypeInfosByName().get('GAS Vendors').getRecordTypeId();
    private static Id recordTypeIdeOrderAdmin = Schema.SObjectType.eOrders__c.getRecordTypeInfosByName().get('GAS eOrder Admin').getRecordTypeId();
    private static Id recordTypeIdeOrderReturn = Schema.SObjectType.eOrders__c.getRecordTypeInfosByName().get('GAS eOrder Return').getRecordTypeId();
    private static Id recordTypeIdOrderRequest = Schema.SObjectType.Order_Request__C.getRecordTypeInfosByName().get('GAS Order Request').getRecordTypeId();
    private static Id recordTypeIdeOrderItem = Schema.SObjectType.eOrder_Item__c.getRecordTypeInfosByName().get('GAS eOrder Item').getRecordTypeId();
    private static Id recordTypeIdReturn =Schema.SObjectType.Line_Item__c.getRecordTypeInfosByName().get('GAS Cylinders Return').getRecordTypeId();
    private static Id recordTypeIdProduct =Schema.SObjectType.EPA_Product__c.getRecordTypeInfosByName().get('GAS Order Product').getRecordTypeId();
    static testMethod void afterInsert(){
        User u =[select id from user where UserName='GAS5@test.org'];
        system.runas(u){
            test.StartTest();
            eOrders__c eorder = new eOrders__c();
            eorder.RecordTypeId=recordTypeIdeOrderAdmin;
            eorder.Description__c = 'test';
            eorder.Order_Amount__c= 50.0;
            eorder.Status__c  = 'Draft';
            insert eorder;      
            ApexPages.CurrentPage().getParameters().put('id',eorder.id);
            Apexpages.StandardController sc = new Apexpages.StandardController(eorder);
            ORDGAS_savePDF ext = new ORDGAS_savePDF(sc);
            ext.saveAttachement();
             
            /*ContentVersion contentVersion = new ContentVersion(); 
            contentVersion.Title = 'Test ContentVersion File - '; 
            contentVersion.PathOnClient = contentVersion.Title; 
            Blob bodyBlob = EncodingUtil.base64Decode('TestFileData');
            contentVersion.VersionData = bodyBlob; 
            contentVersion.IsMajorVersion = false;
            contentVersion.origin = 'H';
            //contentVersion.ContentDocumentId = contentVersionId; 
            
              */
        }
    }
    static testMethod void afterUpdate(){
         User u =[select id from user where UserName='GAS5@test.org'];
        system.runas(u){
        eOrders__c eorder = new eOrders__c();
        eorder.RecordTypeId=recordTypeIdeOrderAdmin;
        eorder.Description__c = 'test';
        eorder.Order_Amount__c= 50.0;
        eorder.Status__c  = 'Draft';
        insert eorder;      
        ContentVersion contentVersion = new ContentVersion(); 
        contentVersion.Title = 'Quote_'+eorder.Id + '.pdf'; 
        contentVersion.PathOnClient = contentVersion.Title; 
        Blob bodyBlob = EncodingUtil.base64Decode('TestFileData');
        contentVersion.VersionData = bodyBlob; 
        contentVersion.IsMajorVersion = false;
        contentVersion.origin = 'H';
        insert contentVersion;
        test.StartTest();
        ApexPages.CurrentPage().getParameters().put('id',eorder.id);
        Apexpages.StandardController sc = new Apexpages.StandardController(eorder);
        ORDGAS_savePDF ext = new ORDGAS_savePDF(sc);
        ext.saveAttachement();
        ext.redirectToPDFPage();
        }
    }
    static testMethod void negativeTesting(){
        User u =[select id from user where UserName='GAS5@test.org'];
        system.runas(u){
        eOrders__c eorder = new eOrders__c();
        eorder.RecordTypeId=recordTypeIdeOrderAdmin;
        eorder.Description__c = 'test';
        eorder.Order_Amount__c= 50.0;
        eorder.Status__c  = 'Draft';
        insert eorder;
       eOrders__c eorder1 = [select id, name,RecordTypeId,Description__c,Order_Amount__c,Status__c, order_number__c from eOrders__c where id =:eorder.Id];
        ContentVersion contentVersion = new ContentVersion(); 
        contentVersion.Title = 'Quot.pdf'; 
        contentVersion.PathOnClient = contentVersion.Title; 
        Blob bodyBlob = EncodingUtil.base64Decode('TestFileData');
        contentVersion.VersionData = bodyBlob; 
        contentVersion.IsMajorVersion = false;
        contentVersion.origin = 'H';
        insert contentVersion;
        test.StartTest();
        ApexPages.CurrentPage().getParameters().put('id',eorder1.id);
        Apexpages.StandardController sc = new Apexpages.StandardController(eorder1);
        ORDGAS_savePDF ext = new ORDGAS_savePDF(sc);
        ext.saveAttachement();
        ext.redirectToPDFPage();
        }
    }
      @TestSetup
    private static void setup()
    {
        // Create a sample form statement object and then submit it for approval.
            
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
		
        // Create User Record
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com',
        EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
        LocaleSidKey='en_US', ProfileId = p.Id,
        TimeZoneSidKey='America/Los_Angeles',
        UserName='GAS5@test.org');
        insert u;

        PermissionSet ps = [SELECT ID From PermissionSet WHERE Name = 'GAS_Application_Admin'];
        insert new PermissionSetAssignment(AssigneeId = u.id, PermissionSetId = ps.Id ); 
    }
}