objects/eOrder_Item__c.object
<CustomObject>
    <fields>
        <fullName>Item_Price__c</fullName>
        <formula>Product__r.List_Price__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Item Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Order_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Request</label>
        <referenceTo>Order_Request__c</referenceTo>
        <relationshipLabel>Order Request Items</relationshipLabel>
        <relationshipName>eOrder_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Active__c</fullName>
        <formula>IF( Product__r.Active__c , TRUE, FALSE)</formula>
        <label>Product Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Code__c</fullName>
        <formula>Product__r.Product_Code__c</formula>
        <label>Product Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Description__c</fullName>
        <formula>Product__r.Description__c</formula>
        <label>Product Description</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <formula>TEXT(Product__r.Product_Type__c)</formula>
        <label>Product Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Vendor__c</fullName>
        <formula>Product__r.Vendor__r.Name</formula>
        <label>Product Vendor</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Choose a Product by searching for Product details</description>
        <inlineHelpText>Choose a Product by searching for Product details</inlineHelpText>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>EPA_Product__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>EPA_Product__c.Vendor__r.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>EPA_Product__c</referenceTo>
        <relationshipLabel>eOrder Items</relationshipLabel>
        <relationshipName>eOrder_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <description>Number of cylinders requested</description>
        <inlineHelpText>Number of cylinders requested</inlineHelpText>
        <label>Quantity</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The current state of this item</description>
        <inlineHelpText>The current state of this item</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New Order</fullName>
                    <default>true</default>
                    <label>New Order</label>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Request Approved</fullName>
                </value>
                <value>
                    <fullName>Added to Order</fullName>
                </value>
                <value>
                    <fullName>Order Placed</fullName>
                </value>
                <value>
                    <fullName>Order Received</fullName>
                </value>
                <value>
                    <fullName>Order Delivered</fullName>
                </value>
                <value>
                    <fullName>Added to 1900-63</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Price__c</fullName>
        <formula>Product__r.List_Price__c * Quantity__c</formula>
        <label>Total Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>eOrder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>eOrder</label>
        <referenceTo>eOrders__c</referenceTo>
        <relationshipLabel>eOrder Items</relationshipLabel>
        <relationshipName>eOrder_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>Specific or detailed items within an order tracked in the eOrders document, initially for the GAS application.  (Similar to Line Items, into which this item might be merged someday.)</description>
    <label>eOrder Item</label>
    <nameField>
        <displayFormat>EPA-EOI-{000000000}</displayFormat>
        <label>eOrder Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>eOrder Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/eOrders__c.object
<CustomObject>
    <fields>
        <fullName>Order_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Request</label>
        <referenceTo>Order_Request__c</referenceTo>
        <relationshipLabel>eOrders</relationshipLabel>
        <relationshipName>eOrders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The current state of the eOrder</description>
        <inlineHelpText>The current state of the eOrder</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <color>#0B6FCE</color>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Activated</fullName>
                    <color>#78C953</color>
                    <label>Activated</label>
                </value>
                <value>
                    <fullName>Return Order Placed</fullName>
                    <color>#CC33CC</color>
                    <label>Return Order Placed</label>
                </value>
                <value>
                    <fullName>Order Placed</fullName>
                    <color>#E27001</color>
                    <label>Order Placed</label>
                </value>
                <value>
                    <fullName>Partial Order Received</fullName>
                    <color>#F3D904</color>
                    <label>Partial Order Received</label>
                </value>
                <value>
                    <fullName>Full Order Received</fullName>
                    <color>#A845DC</color>
                    <label>Full Order Received</label>
                </value>
                <value>
                    <fullName>Order Closed</fullName>
                    <color>#A53711</color>
                    <label>Order Closed</label>
                </value>
                <value>
                    <fullName>Return Order Closed</fullName>
                    <color>#333333</color>
                    <label>Return Order Closed</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Custom Object to Capture Orders placed for GAS Order Management Application.</description>
    <label>eOrder</label>
    <nameField>
        <displayFormat>EPA-EO-{000000000}</displayFormat>
        <label>eOrder ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>eOrders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Order_Request__c.object
<CustomObject>
    <description>Requests for orders to be placed.  Initially used in the GAS application, then in PCORS, and available for other uses.  Used not only in native licensed access ("Type 3 interface" in BAP parlance) but also in "Type 1" interface (unlicensed guest access).</description>
    <label>Order Request</label>
    <nameField>
        <displayFormat>EPA-OR-{000000000}</displayFormat>
        <label>Order Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ORDGAS_eOrderClass.cls
/*
*    Author : mondal.javed@epa.gov
*    CreatedDate : 1-May-2018
*    Class Name : ORGGAS_eOrderClass
*    On record update, this trigger checks status and creates related Cylinders (Line Items)
**/

public without sharing class ORDGAS_eOrderClass{
    public static void ActivatedStatus(eOrders__c eOrder, map<id,eOrders__c> eOrderOldMap){
        if((eOrder.Status__c == 'Full Order Received' || eOrder.Status__c == 'Partial Order Received') &&  eOrder.Status__c != eOrderOldMap.get(eOrder.Id).Status__c  ){
            Id recordTypeId = Schema.SObjectType.Line_Item__c.getRecordTypeInfosByName().get('GAS Cylinders').getRecordTypeId();
            List<eOrder_Item__c> eOrderItemUpdate = new List<eOrder_Item__c>();
            List<Line_Item__c> itemToInsert = new List<Line_Item__c>();
            List<eOrder_Item__c> eOrderItemList  = [SELECT eOrder__c,Order_Request__r.Ownerid,Id,Item_Price__c,Name,Order_Request__c,OwnerId,Product_Active__c,
                                                    Product_Code__c,Product_Description__c,Product_Type__c,Product_Vendor__c,Product__c,
                                                    Quantity__c,Status__c,Total_Price__c FROM eOrder_Item__c where Status__c = 'Order Placed' AND eOrder__c =:eOrder.id ];
            for(eOrder_Item__c eorderItem : eOrderItemList){
                eorderItem.Status__c = 'Order Received';
                eOrderItemUpdate.add(eorderItem);
                for(integer i = 0;i<eorderItem.Quantity__c ; i++){
                    
                    Line_Item__c lineItem = getLineItems();
                    lineItem.Product__c = eorderItem.Product__c;
                    lineItem.Status__c= 'Open';
                    lineItem.Item_Price__c = eorderItem.Item_Price__c;
                    //lineItem.Order_Request__c = eorderItem.Order_Request__c;
                    lineItem.eOrder_Item__c = eorderItem.id;
                    lineItem.eOrder__c = eOrder.id;
                    //lineItem.Ownerid = eorderItem.Order_Request__r.Ownerid;
                    lineItem.Ownerid = eOrder.Ownerid;
                    lineItem.RecordTypeId = recordTypeId;
                    itemToInsert.add(lineItem);
                }
                
            }
            if(!eOrderItemUpdate.IsEmpty()){
                Database.update(eOrderItemUpdate);
            }
            if(!itemToInsert.IsEmpty()){
                Database.SaveResult[] savedResults = Database.insert(itemToInsert, false);
                Boolean someFailure = false;
                for (Database.SaveResult sr : savedResults) 
                {
                    if(sr.isSuccess())
                    {
                        System.debug('All Cylinder records inserted successfully');
                    }                   
                }
            }
        }
    }
    public static Line_Item__c getLineItems(){
        Line_Item__c lineItem = new Line_Item__c();
        return lineItem;
        
    }
}