objects/EPA_Agreement__c.object
<CustomObject>
    <fields>
        <fullName>EPA_File_2__c</fullName>
        <description>FTTA Application.</description>
        <externalId>true</externalId>
        <label>EPA File #</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Used in FTTA Application</description>
        <inlineHelpText>Agreement Status</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                    <color>#E27001</color>
                    <default>true</default>
                    <label>Created</label>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                    <color>#78C953</color>
                    <label>Assigned</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Review in process</fullName>
                </value>
                <value>
                    <fullName>OGC review</fullName>
                    <color>#66E9BD</color>
                    <label>OGC review</label>
                </value>
                <value>
                    <fullName>OGC Concurrence</fullName>
                    <color>#A53711</color>
                    <label>OGC Concurrence</label>
                </value>
                <value>
                    <fullName>Signature Prep</fullName>
                </value>
                <value>
                    <fullName>At Signature</fullName>
                    <color>#0B24BE</color>
                    <label>At Signature</label>
                </value>
                <value>
                    <fullName>Out for Sign</fullName>
                </value>
                <value>
                    <fullName>Signed</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <color>#0B6FCE</color>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Not Pursued</fullName>
                    <color>#F3D904</color>
                    <label>Not Pursued</label>
                </value>
                <value>
                    <fullName>Expired</fullName>
                    <color>#A845DC</color>
                    <label>Expired</label>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                    <color>#641CCF</color>
                    <label>Terminated</label>
                </value>
                <value>
                    <fullName>Active-Amending</fullName>
                    <isActive>false</isActive>
                    <label>Active-Amending</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Information on an EPA Agreement, initially used for FTTA, but also available for other uses.  (Note that the similarly named Agreement object has a Master-Detail relationship with Project, which limits the breadth of its potential use, whereas this object has no such Master-Detail relationship, so it can be used in more situations.)</description>
    <label>EPA Agreement</label>
    <nameField>
        <displayFormat>EPA-{0000000}</displayFormat>
        <label>Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EPA Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>FTTA_EPA_Agreement</fullName>
        <active>true</active>
        <label>FTTA Agreement/Amendment</label>
    </recordTypes>
</CustomObject>

classes/FTTA_CreateActivityForInboundMailTest.cls
/**********************************************************************
Name: FTTA_CreateActivityForInboundMailTest()
======================================================
======================================================
Purpose: Created to test the FTTA_CreateActivityForInboundMailTest class.
-------
======================================================
======================================================
History
-------
VERSION  AUTHOR        DATE       DETAIL              FEATURES/CSR/TTP
1.0 -    Mounika Suram 09/11/2018 INITIAL DEVELOPMENT CSR:FTTA

***********************************************************************/
@isTest(seeAlldata=true)
public class FTTA_CreateActivityForInboundMailTest {
    private static id agreementRecordTypeId = [select id from RecordType where sobjectType='EPA_Agreement__C' and developerName='FTTA_EPA_Agreement'].id;
    static testMethod void TestinBoundEmail()
    {
       	Messaging.InboundEmail email = new Messaging.InboundEmail() ;
        Messaging.InboundEnvelope env = new Messaging.InboundEnvelope();
    	EPA_Agreement__C agreement = new EPA_Agreement__C();
        agreement.RecordTypeId=agreementRecordTypeId;
        agreement.Status__c='Created';
        insert agreement;
        EPA_Agreement__c agreement1 =[select id,EPA_File_2__c from EPA_Agreement__c where id =:agreement.Id limit 1 ];
        email.subject = 'EPA File # '+agreement1.EPA_File_2__c+' :';
        email.fromAddress = 'someaddress@email.com';
        email.plainTextBody = 'Testing the Inbound Email service'; 
        email.htmlBody='Testing the Inbound Email service';  
        FTTA_CreateActivityForInboundMail  testInbound=new FTTA_CreateActivityForInboundMail();
        testInbound.handleInboundEmail(email, env);     
     
   
   }
}