objects/EPA_Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Used in FTTA Application</description>
        <inlineHelpText>Agreement Status</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                    <color>#E27001</color>
                    <default>true</default>
                    <label>Created</label>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                    <color>#78C953</color>
                    <label>Assigned</label>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Review in process</fullName>
                </value>
                <value>
                    <fullName>OGC review</fullName>
                    <color>#66E9BD</color>
                    <label>OGC review</label>
                </value>
                <value>
                    <fullName>OGC Concurrence</fullName>
                    <color>#A53711</color>
                    <label>OGC Concurrence</label>
                </value>
                <value>
                    <fullName>Signature Prep</fullName>
                </value>
                <value>
                    <fullName>At Signature</fullName>
                    <color>#0B24BE</color>
                    <label>At Signature</label>
                </value>
                <value>
                    <fullName>Out for Sign</fullName>
                </value>
                <value>
                    <fullName>Signed</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <color>#0B6FCE</color>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Not Pursued</fullName>
                    <color>#F3D904</color>
                    <label>Not Pursued</label>
                </value>
                <value>
                    <fullName>Expired</fullName>
                    <color>#A845DC</color>
                    <label>Expired</label>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                    <color>#641CCF</color>
                    <label>Terminated</label>
                </value>
                <value>
                    <fullName>Active-Amending</fullName>
                    <isActive>false</isActive>
                    <label>Active-Amending</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Information on an EPA Agreement, initially used for FTTA, but also available for other uses.  (Note that the similarly named Agreement object has a Master-Detail relationship with Project, which limits the breadth of its potential use, whereas this object has no such Master-Detail relationship, so it can be used in more situations.)</description>
    <label>EPA Agreement</label>
    <nameField>
        <displayFormat>EPA-{0000000}</displayFormat>
        <label>Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EPA Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>FTTA_EPA_Agreement</fullName>
        <active>true</active>
        <label>FTTA Agreement/Amendment</label>
    </recordTypes>
</CustomObject>

objects/Task.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>FTTA_Tasks</fullName>
        <active>true</active>
        <description>FTTA Application Tasks</description>
        <label>FTTA Tasks</label>
    </recordTypes>
</CustomObject>

classes/FTTA_SendEmailOnTaskUpdateTest.cls
/**********************************************************************
Name: FTTA_SendEmailOnTaskUpdateTest()

======================================================
======================================================
Purpose: FTTA. Created to test the class FTTA_SendEmailOnTaskUpdate.
-------
======================================================
======================================================
History
-------
VERSION AUTHOR        DATE       DETAIL              FEATURES/CSR/TTP
1.0 -   Mounika Suram 09/06/2018 INITIAL DEVELOPMENT CSR:FTTA

***********************************************************************/
@isTest
public class FTTA_SendEmailOnTaskUpdateTest {
    private static id agreementRecordTypeId = [select id from RecordType where sobjectType='EPA_Agreement__C' and developerName='FTTA_EPA_Agreement'].id;
    private static id taskId = [select id from RecordType where sobjectType='Task' and developerName='FTTA_Tasks'].Id;
    @isTest
    private static void WhenTaskComplted(){
        system.debug('In FTTA_RecordLockOnStatusTerminatedTest:InsertAgreement');
        EPA_Agreement__C agreement = new EPA_Agreement__C();
        agreement.RecordTypeId=agreementRecordTypeId;
        agreement.Status__c='Created';
        insert agreement;
        system.debug('Status'+agreement.Status__c);
        Task task= new task(Subject='Test',WhatId=agreement.id,priority='low',recordTypeId=taskId);
        insert task;
        task.Priority ='high';
        update task;
        task.Status='Completed';
        update task;  
    }

}