objects/EPA_Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Total_Ordered__c</fullName>
        <defaultValue>0</defaultValue>
        <description>** Automatically Calculated ** Aggregate of the Order Ceiling amounts associated with a Funding Period or a Total of all Order Ceilings associated with a Master Contract via associated funding periods.</description>
        <label>Total Ordered</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <description>Information on an EPA Agreement, initially used for FTTA, but also available for other uses.  (Note that the similarly named Agreement object has a Master-Detail relationship with Project, which limits the breadth of its potential use, whereas this object has no such Master-Detail relationship, so it can be used in more situations.)</description>
    <label>EPA Agreement</label>
    <nameField>
        <displayFormat>EPA-{0000000}</displayFormat>
        <label>Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EPA Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EPA_Order__c.object
<CustomObject>
    <fields>
        <fullName>Contract_Vehicle2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The contract vehicle to which the order belongs.</description>
        <label>Contract Vehicle</label>
        <referenceTo>EPA_Agreement__c</referenceTo>
        <relationshipLabel>DCR EPA Orders</relationshipLabel>
        <relationshipName>DCR_EPA_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Ceiling__c</fullName>
        <description>Order or work assignment ceiling.</description>
        <inlineHelpText>Please enter the order or work assignment ceiling.</inlineHelpText>
        <label>Order Ceiling</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <description>Information on task orders, delivery orders, work assignments, BPA calls, etc. on contract vehicles. (Not to be confused with the standard object Orders, which is reserved for specific Salesforce CRM licenses)</description>
    <label>EPA Order</label>
    <nameField>
        <displayFormat>EPA-Order-{000000}</displayFormat>
        <label>Order ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EPA Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/EpaOrderTriggerHelper.cls
public class EpaOrderTriggerHelper {
    // Record type map for easy identification of DCR record types and Ids
    public static Map<Id, RecordType> dcrEpaOrderRecordTypesByIds = new Map<Id, RecordType>([
            SELECT Id, Name
            FROM RecordType
            WHERE SobjectType = 'EPA_Order__c'
            AND Name IN ('DCR Order')
    ]);

    public static void calculateOrderTotalsOnAgreements(List<EPA_Order__c> orders) {
        for (EPA_Order__c order : orders) {
            List<Id> contractIds = new List<Id>();

            if (String.isNotEmpty(order.Contract_Vehicle2__c) && dcrEpaOrderRecordTypesByIds.containsKey(order.RecordTypeId)) {
                contractIds.add(order.Contract_Vehicle2__c);
            }

            if (!contractIds.isEmpty()) {
                AggregateResult[] queryResults = [
                        SELECT Contract_Vehicle2__c, SUM(Order_Ceiling__c) totalAmount
                        FROM EPA_Order__c
                        WHERE Contract_Vehicle2__c IN :contractIds
                        GROUP BY Contract_Vehicle2__c
                ];

                List<EPA_Agreement__c> contracts = new List<EPA_Agreement__c>();
                for (AggregateResult result : queryResults) {
                    EPA_Agreement__c tempContract = new EPA_Agreement__c();
                    tempContract.Total_Ordered__c = (Decimal) result.get('totalAmount');
                    tempContract.Id = (Id) result.get('Contract_Vehicle2__c');

                    contracts.add(tempContract);
                }

                if (!contracts.isEmpty()) {
                    update contracts;
                }
            }
        }
    }
}