objects/EPA_Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Contract_Ceiling__c</fullName>
        <description>Contract ceiling amount</description>
        <inlineHelpText>Please enter the contract-level ceiling amount</inlineHelpText>
        <label>Contract Ceiling</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Ordered__c</fullName>
        <defaultValue>0</defaultValue>
        <description>** Automatically Calculated ** Aggregate of the Order Ceiling amounts associated with a Funding Period or a Total of all Order Ceilings associated with a Master Contract via associated funding periods.</description>
        <label>Total Ordered</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <description>Information on an EPA Agreement, initially used for FTTA, but also available for other uses.  (Note that the similarly named Agreement object has a Master-Detail relationship with Project, which limits the breadth of its potential use, whereas this object has no such Master-Detail relationship, so it can be used in more situations.)</description>
    <label>EPA Agreement</label>
    <nameField>
        <displayFormat>EPA-{0000000}</displayFormat>
        <label>Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EPA Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/EPA_Order__c.object
<CustomObject>
    <fields>
        <fullName>Contract_Vehicle2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The contract vehicle to which the order belongs.</description>
        <label>Contract Vehicle</label>
        <referenceTo>EPA_Agreement__c</referenceTo>
        <relationshipLabel>DCR EPA Orders</relationshipLabel>
        <relationshipName>DCR_EPA_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Ceiling__c</fullName>
        <description>Order or work assignment ceiling.</description>
        <inlineHelpText>Please enter the order or work assignment ceiling.</inlineHelpText>
        <label>Order Ceiling</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <description>Information on task orders, delivery orders, work assignments, BPA calls, etc. on contract vehicles. (Not to be confused with the standard object Orders, which is reserved for specific Salesforce CRM licenses)</description>
    <label>EPA Order</label>
    <nameField>
        <displayFormat>EPA-Order-{000000}</displayFormat>
        <label>Order ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EPA Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/EpaOrderTriggerHelper_Test.cls
@IsTest
public class EpaOrderTriggerHelper_Test {
    @IsTest
    public static void testOrderCalculations() {
        EPA_Agreement__c contract = new EPA_Agreement__c();
        contract.Contract_Ceiling__c = 100000;
        contract.RecordTypeId = Schema.SObjectType.EPA_Agreement__c.getRecordTypeInfosByName().get('DCR - Contract Vehicle').getRecordTypeId();
        insert contract;

        EPA_Order__c order = new EPA_Order__c();
        order.Contract_Vehicle2__c = contract.Id;
        order.RecordTypeId = Schema.SObjectType.EPA_Order__c.getRecordTypeInfosByName().get('DCR Order').getRecordTypeId();
        insert order;

        Test.startTest();
        EPA_Order__c tempOrder = new EPA_Order__c();
        tempOrder.Order_Ceiling__c = 10000;
        update order;
        Test.stopTest();

        EPA_Agreement__c updatedContract = [
                SELECT Id, Total_Ordered__c
                FROM EPA_Agreement__c
                WHERE Id = :contract.Id
                LIMIT 1
        ];

        System.assertEquals(order.Order_Ceiling__c, updatedContract.Total_Ordered__c);
    }

}