objects/EPA_Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>FTTA Soft Delete feature.</description>
        <inlineHelpText>Uncheck the record for Soft Delete.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <description>Information on an EPA Agreement, initially used for FTTA, but also available for other uses.  (Note that the similarly named Agreement object has a Master-Detail relationship with Project, which limits the breadth of its potential use, whereas this object has no such Master-Detail relationship, so it can be used in more situations.)</description>
    <label>EPA Agreement</label>
    <nameField>
        <displayFormat>EPA-{0000000}</displayFormat>
        <label>Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EPA Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>FTTA_EPA_Agreement</fullName>
        <active>true</active>
        <label>FTTA Agreement/Amendment</label>
    </recordTypes>
    <recordTypes>
        <fullName>FTTA_License</fullName>
        <active>true</active>
        <description>FTTA License</description>
        <label>FTTA License</label>
    </recordTypes>
</CustomObject>

classes/FTTA_UpdateActiveStatusForAgreement.cls
/**********************************************************************
Name: FTTA_UpdateActiveStatusForAgreement
======================================================
======================================================
Purpose: 
-------
======================================================
======================================================
History
-------
VERSION AUTHOR 		  DATE 		 DETAIL 			 FEATURES/CSR/TTP
1.0 	Mounika Suram 04/3/2019 INITIAL DEVELOPMENT CSR:FTTA Application
***********************************************************************/
public class FTTA_UpdateActiveStatusForAgreement implements Database.Batchable<sObject> {
 	Private String ageementRTName='FTTA_EPA_Agreement';
    Private String licenseRTName='FTTA_License';

    public final String query = 'select id,Name,active__C,recordType.DeveloperName from epa_Agreement__c where recordType.developerName =:ageementRTName OR recordType.developerName =:licenseRTName';
    public Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(query);
    }
    public void execute(Database.BatchableContext BC, List<EPA_Agreement__C> scope){
        for (EPA_Agreement__C agreement:scope){
            agreement.active__C =true;
        }
        update scope;
    }
    public void finish(Database.BatchableContext BC){}

}