objects/EPA_Agreement__c.object
<CustomObject>
    <fields>
        <fullName>EPA_File_2__c</fullName>
        <description>FTTA Application.</description>
        <externalId>true</externalId>
        <label>EPA File #</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EPA_File__c</fullName>
        <formula>IF(TEXT( Agreement_Type__c ) = 'Amendment', 
EPA_Amendment_2__c ,
IF(Case_Id_2__c != null,Case_Id_2__c ,Case_Id__c )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>EPA File # 2</label>
        <type>Text</type>
    </fields>
    <description>Information on an EPA Agreement, initially used for FTTA, but also available for other uses.  (Note that the similarly named Agreement object has a Master-Detail relationship with Project, which limits the breadth of its potential use, whereas this object has no such Master-Detail relationship, so it can be used in more situations.)</description>
    <label>EPA Agreement</label>
    <nameField>
        <displayFormat>EPA-{0000000}</displayFormat>
        <label>Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EPA Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/FTTA_CopyEPAFileBatch.cls
/**********************************************************************
Name: FTTA_CopyEPAFileBatch
======================================================
======================================================
Purpose: FTTA Application. This batch script runs one time for copying the values from 
the EPA file# formula to the EPA File #(text) which is created for the sequencing of the agreement,amendment and license.
-------
======================================================
======================================================
History
-------
VERSION AUTHOR 		  DATE 		 DETAIL 			 FEATURES/CSR/TTP
1.0 	Mounika Suram 02/13/2019 INITIAL DEVELOPMENT CSR:FTTA Application
***********************************************************************/
public class FTTA_CopyEPAFileBatch implements Database.Batchable<sObject> {
    public final String query = 'select id,Name,EPA_File__c,EPA_File_2__c from EPA_Agreement__C where EPA_File_2__c = null';
    public Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(query);
    }
    public void execute(Database.BatchableContext BC, List<EPA_Agreement__C> scope){
        for (EPA_Agreement__C agreement:scope){
            agreement.EPA_File_2__c =agreement.EPA_File__c;
        }
        update scope;
    }
    public void finish(Database.BatchableContext BC){}
}