objects/EPA_Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Contract_Ceiling__c</fullName>
        <description>Contract ceiling amount</description>
        <inlineHelpText>Please enter the contract-level ceiling amount</inlineHelpText>
        <label>Contract Ceiling</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Line_Item_Total__c</fullName>
        <defaultValue>0</defaultValue>
        <description>** Automatically Calculated ** SUM amount of all related line items. Used to calculate the ceiling remainders for IA, Grants, and Contracts.</description>
        <label>Line Item Total</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Master_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the master contract record that is then split-out by funding periods.</description>
        <inlineHelpText>Lookup the Master Contract record.</inlineHelpText>
        <label>Master Contract</label>
        <referenceTo>EPA_Agreement__c</referenceTo>
        <relationshipLabel>EPA Agreements</relationshipLabel>
        <relationshipName>Master_Contract</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Ordered__c</fullName>
        <defaultValue>0</defaultValue>
        <description>** Automatically Calculated ** Aggregate of the Order Ceiling amounts associated with a Funding Period or a Total of all Order Ceilings associated with a Master Contract via associated funding periods.</description>
        <label>Total Ordered</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <description>Information on an EPA Agreement, initially used for FTTA, but also available for other uses.  (Note that the similarly named Agreement object has a Master-Detail relationship with Project, which limits the breadth of its potential use, whereas this object has no such Master-Detail relationship, so it can be used in more situations.)</description>
    <label>EPA Agreement</label>
    <nameField>
        <displayFormat>EPA-{0000000}</displayFormat>
        <label>Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EPA Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/EpaAgreementTriggerHelper_Test.cls
@IsTest
public with sharing class EpaAgreementTriggerHelper_Test {

    @IsTest
    public static void calculateMasterContractTotals() {
        EPA_Agreement__c masterContract = new EPA_Agreement__c();
        masterContract.Contract_Ceiling__c = 100000;
        masterContract.RecordTypeId = Schema.SObjectType.EPA_Agreement__c.getRecordTypeInfosByName().get('DCR - Contract Vehicle').getRecordTypeId();
        insert masterContract;

        EPA_Agreement__c contract = new EPA_Agreement__c();
        contract.Contract_Ceiling__c = 10000;
        contract.Master_Contract__c = masterContract.Id;
        contract.RecordTypeId = Schema.SObjectType.EPA_Agreement__c.getRecordTypeInfosByName().get('DCR - Contract Vehicle Funding Period').getRecordTypeId();
        contract.Total_Ordered__c = 5000;
        insert contract;

        Line_Item__c lineItem = new Line_Item__c();
        lineItem.Vehicle_Record2__c = contract.Id;
        lineItem.RecordTypeId = Schema.SObjectType.Line_Item__c.getRecordTypeInfosByName().get('DCR Contract Line Item').getRecordTypeId();
        lineItem.Amount__c = 500;

        Test.startTest();
        insert lineItem;
        Test.stopTest();

        EPA_Agreement__c updatedMasterContract = [
                SELECT Id, Line_Item_Total__c, Total_Ordered__c
                FROM EPA_Agreement__c
                WHERE Id = :masterContract.Id
                LIMIT 1
        ];

        System.assertEquals(lineItem.Amount__c, updatedMasterContract.Line_Item_Total__c);
        System.assertEquals(contract.Total_Ordered__c, updatedMasterContract.Total_Ordered__c);
    }
}