objects/EPA_Agreement__c.object
<CustomObject>
    <fields>
        <fullName>Line_Item_Total__c</fullName>
        <defaultValue>0</defaultValue>
        <description>** Automatically Calculated ** SUM amount of all related line items. Used to calculate the ceiling remainders for IA, Grants, and Contracts.</description>
        <label>Line Item Total</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Master_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the master contract record that is then split-out by funding periods.</description>
        <inlineHelpText>Lookup the Master Contract record.</inlineHelpText>
        <label>Master Contract</label>
        <referenceTo>EPA_Agreement__c</referenceTo>
        <relationshipLabel>EPA Agreements</relationshipLabel>
        <relationshipName>Master_Contract</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Ordered__c</fullName>
        <defaultValue>0</defaultValue>
        <description>** Automatically Calculated ** Aggregate of the Order Ceiling amounts associated with a Funding Period or a Total of all Order Ceilings associated with a Master Contract via associated funding periods.</description>
        <label>Total Ordered</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <description>Information on an EPA Agreement, initially used for FTTA, but also available for other uses.  (Note that the similarly named Agreement object has a Master-Detail relationship with Project, which limits the breadth of its potential use, whereas this object has no such Master-Detail relationship, so it can be used in more situations.)</description>
    <label>EPA Agreement</label>
    <nameField>
        <displayFormat>EPA-{0000000}</displayFormat>
        <label>Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EPA Agreements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/EpaAgreementTriggerHelper.cls
public class EpaAgreementTriggerHelper {
    public static Map<Id, RecordType> dcrAgreemenRecordTypesByIds = new Map<Id, RecordType>([
            SELECT Id, Name
            FROM RecordType
            WHERE SobjectType = 'EPA_Agreement__c'
            AND Name IN ('DCR - Contract Vehicle','DCR - Contract Vehicle Funding Period','DCR - Grant','DCR - IA','DCR Contract Line Item')
    ]);

    public static void updateMasterContractLineItemTotal(List<EPA_Agreement__c> contracts) {
        List<Id> masterContractIds = new List<Id>();
        
        for (EPA_Agreement__c contract : contracts) {
            if (String.isNotBlank(contract.Master_Contract__c) && dcrAgreemenRecordTypesByIds.containsKey(contract.RecordTypeId)) {
                masterContractIds.add(contract.Master_Contract__c);
            }
        }
        
        if (!masterContractIds.isEmpty()) {
            List<EPA_Agreement__c> updatedContracts = calculateLineItemTotalsFromContracts(masterContractIds);
            
            update updatedContracts;
        }
    }
    
    private static List<EPA_Agreement__c> calculateLineItemTotalsFromContracts(List<Id> contractIds) {
        List<EPA_Agreement__c> contractsToUpdate = new List<EPA_Agreement__c>();
        
        AggregateResult[] queryResults = [
            SELECT Master_Contract__c, SUM(Line_Item_Total__c) lineItemTotals, SUM(Total_Ordered__c) orderTotals
            FROM EPA_Agreement__c
            WHERE Master_Contract__c IN :contractIds
            GROUP BY Master_Contract__c
        ];
        
        for (AggregateResult result : queryResults) {
            EPA_Agreement__c tempContract = new EPA_Agreement__c();
            tempContract.Id = (Id) result.get('Master_Contract__c');
            tempContract.Line_Item_Total__c = (Decimal) result.get('lineItemTotals');
            tempContract.Total_Ordered__c = (Decimal) result.get('orderTotals');
            
            contractsToUpdate.add(tempContract);
        }
        
        return contractsToUpdate;
    }
}