objects/Forms_URL__c.object
<CustomObject>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <label>Forms URL</label>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>LAN_ID__c</fullName>
        <externalId>true</externalId>
        <label>LAN ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Session_Environment__c</fullName>
        <label>Session Environment</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Session_IP__c</fullName>
        <label>Session IP</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Session_Timestamp__c</fullName>
        <label>Session Timestamp</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Session_Token__c</fullName>
        <label>Session Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/initSession_Test.cls
@isTest
public class initSession_Test {

    @isTest
    static void testController(){
        insert new Forms_URL__c(name='Form URL', URL__c = 'https://oeiodsta-oeiodstadev.cs33.force.com/FormPage'); // URL from Custom Setting
        initSession controller = new initSession();
        controller.uID = [select id from User where isActive = true limit 1].ID;
        controller.onLoad();
    }
    
    @isTest
    static void testControllerB(){
        insert new Forms_URL__c(name='Form URL', URL__c = 'https://oeiodsta-oeiodstadev.cs33.force.com/FormPage'); // URL from Custom Setting
        initSession controller = new initSession();
        
        Profile p = [select id, name from profile where name = 'EPA BAP Forms Profile'];        
            
        User u = new User(FirstName='Bob', LastName='Smith', profileID=p.id, Username='test@fake.ccc', 
              email='test@fake.ccc', Alias='testU', CommunityNickname='testU', TimeZoneSidKey= 'America/Los_Angeles',
              LocaleSidKey='en_US', EmailEncodingKey='UTF-8', LanguageLocaleKey='en_US');
        insert u;
        u.Session_Token__c = '12345';
        u.Session_IP__c = '111-111-1111';
        u.Session_Environment__c = 'chrome';
        u.Session_Timestamp__c = datetime.now().addMinutes(-1);
        u.Lan_ID__c = 'testLan';
        update u;
    
    controller.onLoad();
        
    }
}