objects/Metadata__c.object
<CustomObject>
    <fields>
        <fullName>API_Name__c</fullName>
        <description>API Name, BAP Provisioning, 2018.07.16</description>
        <label>API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Action_Date__c</fullName>
        <label>Action Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Activate</fullName>
                </value>
                <value>
                    <fullName>Deactivate</fullName>
                </value>
                <value>
                    <fullName>Freeze</fullName>
                </value>
                <value>
                    <fullName>Unfreeze</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Label__c</fullName>
        <description>Label found on the metadata, BAP Metadata, 2018.07.16</description>
        <label>Label</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Original_SF_ID__c</fullName>
        <description>Original copied SF ID, BAP Metadata, 2018.07.18</description>
        <label>Original SF ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Metadata</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>Metadata object for loading data to report on BAP itself</description>
    <label>Metadata</label>
    <nameField>
        <label>Metadata Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metadata</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>LAN_ID__c</fullName>
        <externalId>true</externalId>
        <label>LAN ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/UserLogHandler.cls
public class UserLogHandler implements Queueable {
    private List<User> userIDs;
    
    public UserLogHandler (List<User> recs) {
        this.userIDs = recs;
    }
    
    public void execute(QueueableContext context) {
        List<User> uList= [select Id, email,isactive,alias,LAN_ID__c,EmployeeNumber from user where Id = :userIDs];
        Id rtID = Schema.SObjectType.Metadata__c.getRecordTypeInfosByName().get('User History').getRecordTypeId();
        List<Metadata__c> insertMetadataList = new List<Metadata__c>();
        
        for (User u : uList) {            
            if (u.isActive == True) {
                Metadata__c m = new Metadata__C (recordtypeid=rtID,name=u.email,action__c='Activate',action_date__c=Datetime.now(),user__c=u.id,
                                                original_sf_id__c=u.id,label__c=u.LAN_ID__c,API_Name__c=u.EmployeeNumber);
                insertMetadataList.add(m);
            } else if (u.isActive == False){
                Metadata__c m = new Metadata__C (recordtypeid=rtID,name=u.email,action__c='Deactivate',action_date__c=Datetime.now(),user__c=u.id,
                                                original_sf_id__c=u.id,label__c=u.LAN_ID__c,API_Name__c=u.EmployeeNumber);
                insertMetadataList.add(m);
            }
        }
        try {
             insert insertMetadataList;
             if(Test.isRunningTest()) {
                CalloutException e = new CalloutException();
                e.setMessage('This is a constructed exception for testing and code coverage');
                throw e;
             }
        } catch (Exception e){
            System.debug('Exception: ' + e);
        }
    }
}