objects/Metadata__c.object
<CustomObject>
    <fields>
        <fullName>API_Name__c</fullName>
        <description>API Name, BAP Provisioning, 2018.07.16</description>
        <label>API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Action_Date__c</fullName>
        <label>Action Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Activate</fullName>
                </value>
                <value>
                    <fullName>Deactivate</fullName>
                </value>
                <value>
                    <fullName>Freeze</fullName>
                </value>
                <value>
                    <fullName>Unfreeze</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Label__c</fullName>
        <description>Label found on the metadata, BAP Metadata, 2018.07.16</description>
        <label>Label</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Original_SF_ID__c</fullName>
        <description>Original copied SF ID, BAP Metadata, 2018.07.18</description>
        <label>Original SF ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Metadata</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>Metadata object for loading data to report on BAP itself</description>
    <label>Metadata</label>
    <nameField>
        <label>Metadata Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metadata</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>LAN_ID__c</fullName>
        <externalId>true</externalId>
        <label>LAN ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/UserDeprovisioning.cls
/*
* @author Omer
* @description Batch Class to freeze user accounts if lastlogindate is 105 days
* @date Created at 2019-10
*/

global class UserDeprovisioning implements Database.Batchable<sObject> {
    
    global Set<id> allFailedId=new Set<id>();
    global List<id> allSuccessId=new List<id>();
    public Boolean isTest=false;
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        String dateTimeFormat = DateTime.now().addDays(-105).format('yyyy-MM-dd\'T\'hh:mm:ss\'Z\'');
        String query = 'SELECT IsFrozen,UserId FROM UserLogin WHERE IsFrozen=false AND UserId IN ';
        query+='(SELECT Id FROM User WHERE Profile.Name != \'System Administrator\' ';
        query+='AND LastLoginDate<='+dateTimeFormat+' AND IsActive=True)';
        /*if(Test.isRunningTest()){
query+=' limit 1';
}else{
query+=' limit 10000';
}*/
        Integer queryLimit = Test.IsRunningTest() ? 1:10000;
        query+=' limit '+queryLimit;
        
        System.debug('Query'+query);
        System.debug(Database.getQueryLocator(query));
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<UserLogin> userList) {
        
        // process each batch of records
        allFailedId=new Set<id>();
        allSuccessId=new List<id>();
        List<String> userIds = new List<String>();
        for(UserLogin user : userList)
        {        
            user.IsFrozen=true;
            userIds.add(user.userId);
            
        }
        try {
            database.SaveResult[] updateResults=database.update(userList,false);
            Id rtID = Schema.SObjectType.Metadata__c.getRecordTypeInfosByName().get('User History').getRecordTypeId();
            List<Metadata__c> insertMetadataList = new List<Metadata__c>();
            for(User user:[select Id,LAN_ID__c,EmployeeNumber,email from user where Id IN :userIds]){
                // Log action
                Metadata__c m = new Metadata__C (RecordTypeId=rtID,name=user.email,action__c='Freeze',action_date__c=Datetime.now(),user__c=user.id,
                                                 original_sf_id__c=user.id,label__c=user.LAN_ID__c,API_Name__c=user.EmployeeNumber);
                insertMetadataList.add(m);
            }
            insert insertMetadataList;
            
            if(Test.isRunningTest()) {
                CalloutException e = new CalloutException();
                e.setMessage('This is a constructed exception for testing and code coverage');
                throw e;
            }
            } catch(Exception e) {
                System.Debug('Exception: ' + e);
            }
        }   
        
        global void finish(Database.BatchableContext BC) {
        }
    }