objects/Snippet__c.object
<CustomObject>
    <fields>
        <fullName>Document_Number__c</fullName>
        <label>Document Number</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Extracted_Text__c</fullName>
        <label>Extracted Text</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Related_Reference__c</fullName>
        <label>Related Reference</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <label>Response</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Submission_Number__c</fullName>
        <formula>Submission__r.Submission_Number__c</formula>
        <label>Submission Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Submission__c</fullName>
        <label>Submission</label>
        <referenceTo>Submission__c</referenceTo>
        <relationshipLabel>Snippets</relationshipLabel>
        <relationshipName>Snippets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Topic__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Topic</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Record_Type_Pick__c</field>
                <operation>equals</operation>
                <valueField>Topic__c.Record_Type_Pick__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Topic__c</referenceTo>
        <relationshipLabel>Snippets</relationshipLabel>
        <relationshipName>Substantive_Contents</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>A piece extracted from something larger, like text extracted from a document, initially used for text extracted from comments submitted by the public on dockets.</description>
    <label>Snippet</label>
    <nameField>
        <displayFormat>SBC-{000000}</displayFormat>
        <label>Snippet ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Snippets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Submission__c.object
<CustomObject>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Submission_Number__c</fullName>
        <externalId>true</externalId>
        <label>Submission Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Topic__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Topic</label>
        <referenceTo>Topic__c</referenceTo>
        <relationshipName>Comments</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>Submissions of information, documents, questions, comments, etc.  Initially used for DCM to capture information on submissions of comments on dockets.  Also used for submission of inquiries to the Customer Experience team in the CX Action Tracker (CXAT).</description>
    <label>Submission</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Submission ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Topic__c.object
<CustomObject>
    <fields>
        <fullName>Agency_Comment_Response__c</fullName>
        <label>Agency Topic Response</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Comment_Summary__c</fullName>
        <label>Comment Summary</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Topic_Number__c</fullName>
        <label>Topic Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <description>Topics of discussion, conversation, documents, comments, etc., useful for tracking, reporting, categorization, other organization, or other use of the material.  Initially used to categorize snippets of text extracted from submissions of comments on dockets.</description>
    <label>Topic</label>
    <nameField>
        <label>Topic Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Topics</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/SnippetDownloader.cls
public class SnippetDownloader {
    
    public Map<String,String> requests { get; set; }
    public List<Snippet__c> snippets {get; set;}
    
	public Id Id { get; set; }
    public Snippet__c snippet { get; set; }
    public String userText = '';
    
    public SnippetDownloader(ApexPages.StandardController standardController)
    {                        
        snippet = (Snippet__c) standardController.getRecord();
        Id = snippet.Id;       
        requests = new Map<String,String>();
    }
  
    public SnippetDownloader()
    {
        requests = new Map<String,String>();         
		snippets = [SELECT Submission_Number__c,Response__c,Submission__c,	Notes__c,Related_Reference__c,Document_Number__c,Name,Topic__c,Topic__r.Name,Extracted_Text__c,Topic__r.Topic_Number__c,Topic__r.Comment_Summary__c,Topic__r.Agency_Comment_Response__c FROM Snippet__c ORDER BY Topic__r.Topic_Number__c ASC];
    }
         
	public PageReference printView() {        
     requests.put('userText', userText);
   	 PageReference oPageRef = Page.TopicDownloadPage;
     oPageRef.setRedirect(false);
     return oPageRef;
	}
}