objects/Submission__c.object
<CustomObject>
    <fields>
        <fullName>Abbrv_Customer_Inquiry_Input__c</fullName>
        <defaultValue>"(blank)"</defaultValue>
        <description>CX Tracker</description>
        <label>Abbrv Customer Inquiry/Input</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Abbrv_SME_Response__c</fullName>
        <defaultValue>"(blank)"</defaultValue>
        <description>CX Tracker</description>
        <label>Abbrv SME Response</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CX_POC_Comments__c</fullName>
        <description>CX Tracker</description>
        <inlineHelpText>Notes from the CX Team assigned to the Issue</inlineHelpText>
        <label>CX POC Comments</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Category_OCAPPM__c</fullName>
        <description>CX Tracker</description>
        <inlineHelpText>Issue Category assigned by Point of Contact</inlineHelpText>
        <label>Inquiry Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Software</fullName>
                </value>
                <value>
                    <fullName>Hardware</fullName>
                </value>
                <value>
                    <fullName>Mobile Devices</fullName>
                </value>
                <value>
                    <fullName>Security</fullName>
                </value>
                <value>
                    <fullName>Contracts</fullName>
                </value>
                <value>
                    <fullName>Network</fullName>
                </value>
                <value>
                    <fullName>Records Management</fullName>
                </value>
                <value>
                    <fullName>Policy</fullName>
                </value>
                <value>
                    <fullName>Communication</fullName>
                </value>
                <value>
                    <fullName>Need More Data</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer_Inquiry_Input__c</fullName>
        <description>CX Tracker</description>
        <inlineHelpText>Text of the issue.</inlineHelpText>
        <label>Customer Inquiry/Input</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Inquirer_Email__c</fullName>
        <description>CX Tracker</description>
        <formula>Inquirer__r.Email</formula>
        <label>Inquirer's Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Inquirer_Phone__c</fullName>
        <description>CX Tracker</description>
        <formula>Inquirer__r.Phone</formula>
        <label>Inquirer's Phone</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Inquirer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>CX Tracker</description>
        <inlineHelpText>Name of the person raising the issue.</inlineHelpText>
        <label>Inquirer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissionsa441z</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Inquiry_Closeout_Date__c</fullName>
        <description>CX Tracker</description>
        <label>Inquiry Closeout Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Inquiry_Date_Formatted__c</fullName>
        <description>CX Tracker</description>
        <formula>TEXT(MONTH(Inquiry_Date__c)) +'/'+ TEXT(DAY(Inquiry_Date__c)) +'/'+ TEXT(YEAR(Inquiry_Date__c))</formula>
        <label>Inquiry Date Formatted</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Inquiry_Date__c</fullName>
        <description>CX Tracker</description>
        <label>Inquiry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Organization_Full_Name__c</fullName>
        <description>CX Tracker</description>
        <formula>Inquirer__r.Account.Name</formula>
        <label>Organization Full Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RPIO_Name__c</fullName>
        <description>CX Tracker</description>
        <formula>Inquirer__r.Company_Name__c</formula>
        <label>RPIO Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Responsible_OEI_Office__c</fullName>
        <description>CX Tracker</description>
        <formula>SME_New__r.Department</formula>
        <label>Responsible OEI Office</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SME_Notification_Date__c</fullName>
        <description>CX Tracker</description>
        <label>SME Notification Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SME_Response_Date__c</fullName>
        <description>CX Tracker</description>
        <label>SME Response Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SME_Response__c</fullName>
        <description>CX Tracker</description>
        <inlineHelpText>Response from Subject Matter Expert assisting the Issue</inlineHelpText>
        <label>SME Response</label>
        <length>7500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status_OCAPPM__c</fullName>
        <description>CX Tracker</description>
        <label>Inquiry Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Pending SME</fullName>
                </value>
                <value>
                    <fullName>Long Term Solution Needed</fullName>
                </value>
                <value>
                    <fullName>Need More Info</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Category_OCAPPM__c</fullName>
        <description>CX Tracker</description>
        <inlineHelpText>Issue Sub-Category assigned by OCAPPM Staff. Available options for this is based on the Category selected.</inlineHelpText>
        <label>Inquiry Sub-Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Category_OCAPPM__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>508 Compliance</fullName>
                </value>
                <value>
                    <fullName>Agile Blanket Purchase Agreement</fullName>
                </value>
                <value>
                    <fullName>Applications Development</fullName>
                </value>
                <value>
                    <fullName>Architecture Input</fullName>
                </value>
                <value>
                    <fullName>CDM</fullName>
                </value>
                <value>
                    <fullName>Cloud</fullName>
                </value>
                <value>
                    <fullName>Collaboration Services</fullName>
                </value>
                <value>
                    <fullName>CPIC</fullName>
                </value>
                <value>
                    <fullName>Data Analytics Services</fullName>
                </value>
                <value>
                    <fullName>Data Integration</fullName>
                </value>
                <value>
                    <fullName>Data Management Services</fullName>
                </value>
                <value>
                    <fullName>Data Warehousing</fullName>
                </value>
                <value>
                    <fullName>Desktop Services</fullName>
                </value>
                <value>
                    <fullName>Development (Apps)</fullName>
                </value>
                <value>
                    <fullName>Digital Services</fullName>
                </value>
                <value>
                    <fullName>e-Discovery</fullName>
                </value>
                <value>
                    <fullName>Enterprise Hosting</fullName>
                </value>
                <value>
                    <fullName>e-Reporting</fullName>
                </value>
                <value>
                    <fullName>FITARA Reviews</fullName>
                </value>
                <value>
                    <fullName>FOIA</fullName>
                </value>
                <value>
                    <fullName>Identity Management</fullName>
                </value>
                <value>
                    <fullName>Information Directives</fullName>
                </value>
                <value>
                    <fullName>Information Exchange</fullName>
                </value>
                <value>
                    <fullName>Lotus Notes</fullName>
                </value>
                <value>
                    <fullName>Need More Data</fullName>
                </value>
                <value>
                    <fullName>Office 365</fullName>
                </value>
                <value>
                    <fullName>Paperless</fullName>
                </value>
                <value>
                    <fullName>Printer Services</fullName>
                </value>
                <value>
                    <fullName>Quality Management System</fullName>
                </value>
                <value>
                    <fullName>Records Management System</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Submissions of information, documents, questions, comments, etc.  Initially used for DCM to capture information on submissions of comments on dockets.  Also used for submission of inquiries to the Customer Experience team in the CX Action Tracker (CXAT).</description>
    <label>Submission</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Submission ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>CX_Tracker</fullName>
        <active>true</active>
        <description>OCAPPM's Customer Experience Inquiry Tracker</description>
        <label>CX Tracker</label>
    </recordTypes>
</CustomObject>

classes/BAP_OCAPPM_Data_PageController2.cls
public class BAP_OCAPPM_Data_PageController2{
    public string sID {get;set;}
    public boolean valid {get;set;}
    public id uID {get;set;}
    public String licName {get;set;}
    public Boolean t1User {get;set;}
    
    public String sortField {get;set;}
        {sortField = 'Inquiry_Date__c';}
    
    public Boolean sortOrderASC {get;set;}
        {sortOrderASC = true;}
    
    public String fileName {get;set;}
        {fileName = 'OCAPPM Export - '+system.today().format();}
            
    private String sortOrder = 'ASC';
    
    public BAP_OCAPPM_Data_PageController2(){
        ID userID = UserInfo.getUserID();
        licName = UtilityMethods.getLicName(userID);
        
        if(licName != 'Guest User License'){t1User=false;}
        else{t1User=true;}
        if(t1User){
        valid = false;
        // Get session ID from URL parameters, get user ID from the matching session
        sID = UtilityMethods.getSessionID();
        uID = UtilityMethods.getUserID(sID);
        
        // Validate Session, temporarily disabled until more user data from proxy 
        valid = UtilityMethods.validateSession(sID, uID);
          }
        else {uID = UserInfo.getUserId(); valid= true;}
    }
    
    public PageReference validateOrRedirect() {
        // 9/21/2017 - Larry Spackman - Disabled for deployment to Production because HeaderLogs custom object not being deployed
        /*
        // Log Header & Parameters
        UtilityMethods.logHeaders();
        // End Log Header & Parameters
        */
       
        // Valid value from Verify Session call above
        if (!valid) {
            PageReference retURL = new PageReference('/');
            return retURL;
        }
        else { return null; }       
    }
    
    public list<submission__c> getissues(){
        
        if(sortOrderASC){sortOrder = 'ASC';}
           else{sortOrder = 'DESC';}
        id rtid = [select id, developername, name, sObjectType from recordtype where sObjectType = 'Submission__c' and developername = 'CX_Tracker' limit 1].id;
        
        list<submission__c> results = Database.query('select id, '+
                                'Name, '+
                                'Inquirer__c, '+
                                'RPIO_Name__c, '+
                                'Organization_Full_Name__c, '+
                                'Inquirer_Phone__c, '+
                                'Inquirer_Email__c, '+
                                'Customer_Inquiry_Input__c, '+
                                'Category_OCAPPM__c, '+
                                'Sub_Category_OCAPPM__c, '+
                                'Responsible_OEI_Office__c, '+
                                'Inquiry_Date__c, '+
                                'SME_Notification_Date__c, '+
                                'SME_Response_Date__c, '+
                                'SME_Response__c, '+
                                'CX_POC_Comments__c, '+
                                'Inquiry_Closeout_Date__c, '+
                                'Status_OCAPPM__c, '+
                                'Abbrv_Customer_Inquiry_Input__c, '+
                                'Abbrv_SME_Response__c, '+
                                'Inquiry_Date_Formatted__c '+
                                'From submission__c '+
                                'WHERE recordtypeid = :rtid '+
                                'Order By '+ sortField + ' ' + sortOrder);  
                                 
                        return results;
        }
    
    public pagereference download(){
        return page.BAP_OCAPPM_Data_Excel3;
    }
    
    public pagereference save(){
        return null;
    }
    
    public pagereference cancel(){
        return null;
    }
    
    public void sortByCustomerInquiryInput() {
        if(sortOrderASC){sortOrderASC=false;}
            else{sortOrderASC=true;}
        this.sortField = 'Abbrv_Customer_Inquiry_Input__c';
        sortField = 'Abbrv_Customer_Inquiry_Input__c';
    }
    
    public void sortByInquiryDate() {
        if(sortOrderASC){sortOrderASC=false;}
            else{sortOrderASC=true;}
        this.sortField = 'Inquiry_Date__c';
        sortField = 'Inquiry_Date__c';
    }
    
    public void sortByInquiryCategory() {
        if(sortOrderASC){sortOrderASC=false;}
            else{sortOrderASC=true;}
        this.sortField = 'Category_OCAPPM__c';
        sortField = 'Category_OCAPPM__c';
    }
    
    public void sortBySMEResponse() {
        if(sortOrderASC){sortOrderASC=false;}
            else{sortOrderASC=true;}
        this.sortField = 'Abbrv_SME_Response__c';
        sortField = 'Abbrv_SME_Response__c';
    }
    
    public void sortByStatus() {
        if(sortOrderASC){sortOrderASC=false;}
            else{sortOrderASC=true;}
        this.sortField = 'Status_OCAPPM__c';
        sortField = 'Status_OCAPPM__c';
    }
    
    public void sortByRPIO() {
        if(sortOrderASC){sortOrderASC=false;}
            else{sortOrderASC=true;}
        this.sortField = 'RPIO_Name__c';
        sortField = 'RPIO_Name__c';
    }
    
}